// Day 8: 프로젝트 관리 & 일정 (Project Management & Schedule) - 441~510
SENTENCES.push(
    { id: 441, day: 8, en: "The project milestone is set for March 15th.", ko: "프로젝트 마일스톤은 3월 15일로 설정되어 있습니다." },
    { id: 442, day: 8, en: "We are currently in the design validation phase.", ko: "현재 설계 검증 단계에 있습니다." },
    { id: 443, day: 8, en: "The SOP date is scheduled for Q3 next year.", ko: "SOP 일정은 내년 3분기로 예정되어 있습니다." },
    { id: 444, day: 8, en: "The tooling lead time is 12 weeks.", ko: "금형 리드 타임은 12주입니다." },
    { id: 445, day: 8, en: "We need to freeze the design by end of this month.", ko: "이번 달 말까지 설계를 확정해야 합니다." },
    { id: 446, day: 8, en: "The design change request has been submitted.", ko: "설계 변경 요청서가 제출되었습니다." },
    { id: 447, day: 8, en: "The ECN needs approval from the customer.", ko: "ECN은 고객의 승인이 필요합니다." },
    { id: 448, day: 8, en: "We are tracking 15 open issues in the action list.", ko: "액션 리스트에 15개의 미해결 이슈를 추적하고 있습니다." },
    { id: 449, day: 8, en: "The risk assessment has been updated.", ko: "리스크 평가가 업데이트되었습니다." },
    { id: 450, day: 8, en: "We identified three critical path items.", ko: "3개의 크리티컬 패스 항목을 확인했습니다." },
    { id: 451, day: 8, en: "The budget for prototype tooling is approved.", ko: "프로토타입 금형 예산이 승인되었습니다." },
    { id: 452, day: 8, en: "The cost reduction target is 10% per unit.", ko: "단위당 원가 절감 목표는 10%입니다." },
    { id: 453, day: 8, en: "The BOM needs to be finalized before ordering.", ko: "발주 전에 BOM을 확정해야 합니다." },
    { id: 454, day: 8, en: "The part number has been assigned.", ko: "품번이 부여되었습니다." },
    { id: 455, day: 8, en: "The drawing release is pending engineering approval.", ko: "도면 출도가 엔지니어링 승인 대기 중입니다." },
    { id: 456, day: 8, en: "We submitted the quotation to the purchasing team.", ko: "구매팀에 견적서를 제출했습니다." },
    { id: 457, day: 8, en: "The lead time from the supplier is 8 weeks.", ko: "공급업체 리드 타임은 8주입니다." },
    { id: 458, day: 8, en: "We need to place the order by next Friday.", ko: "다음 주 금요일까지 발주해야 합니다." },
    { id: 459, day: 8, en: "The delivery date has been pushed back by two weeks.", ko: "납품일이 2주 연기되었습니다." },
    { id: 460, day: 8, en: "Can we expedite the shipment?", ko: "납품을 앞당길 수 있나요?" },
    { id: 461, day: 8, en: "The project status is yellow due to the delay.", ko: "지연으로 인해 프로젝트 상태가 옐로우입니다." },
    { id: 462, day: 8, en: "We need a recovery plan to meet the deadline.", ko: "마감일을 맞추기 위한 복구 계획이 필요합니다." },
    { id: 463, day: 8, en: "The resource allocation needs to be reviewed.", ko: "자원 배분을 재검토해야 합니다." },
    { id: 464, day: 8, en: "We are short on manpower for this project.", ko: "이 프로젝트에 인력이 부족합니다." },
    { id: 465, day: 8, en: "The Gantt chart has been updated with the latest schedule.", ko: "간트 차트가 최신 일정으로 업데이트되었습니다." },
    { id: 466, day: 8, en: "The weekly status report is due every Monday.", ko: "주간 현황 보고서는 매주 월요일 마감입니다." },
    { id: 467, day: 8, en: "The customer visit is planned for next Wednesday.", ko: "고객 방문이 다음 주 수요일로 계획되어 있습니다." },
    { id: 468, day: 8, en: "We need to prepare the presentation for the review.", ko: "리뷰를 위한 발표 자료를 준비해야 합니다." },
    { id: 469, day: 8, en: "The design review gate has been passed.", ko: "설계 리뷰 게이트를 통과했습니다." },
    { id: 470, day: 8, en: "The lessons learned should be documented.", ko: "교훈 사항을 문서화해야 합니다." },
    { id: 471, day: 8, en: "The change management process must be followed.", ko: "변경 관리 프로세스를 따라야 합니다." },
    { id: 472, day: 8, en: "The project charter will be signed by both parties.", ko: "프로젝트 차터를 양측이 서명할 것입니다." },
    { id: 473, day: 8, en: "The scope needs to be clearly defined.", ko: "범위를 명확히 정의해야 합니다." },
    { id: 474, day: 8, en: "This is out of scope for this project phase.", ko: "이것은 이번 프로젝트 단계의 범위 밖입니다." },
    { id: 475, day: 8, en: "We need to negotiate the specification change.", ko: "사양 변경을 협의해야 합니다." },
    { id: 476, day: 8, en: "The prototype samples will be shipped by air.", ko: "프로토타입 샘플은 항공으로 발송됩니다." },
    { id: 477, day: 8, en: "The A-sample delivery is confirmed for April.", ko: "A 샘플 납품이 4월로 확정되었습니다." },
    { id: 478, day: 8, en: "The B-sample incorporates all the design changes.", ko: "B 샘플에 모든 설계 변경이 반영되어 있습니다." },
    { id: 479, day: 8, en: "The C-sample is the mass production intent.", ko: "C 샘플은 양산 의도 사양입니다." },
    { id: 480, day: 8, en: "The pilot production run is scheduled for 500 units.", ko: "파일럿 생산은 500개로 예정되어 있습니다." },
    { id: 481, day: 8, en: "The production ramp-up plan is being reviewed.", ko: "양산 증대 계획을 검토 중입니다." },
    { id: 482, day: 8, en: "The initial production capacity is 5000 units per month.", ko: "초기 생산 능력은 월 5000개입니다." },
    { id: 483, day: 8, en: "We need to secure a second source for this component.", ko: "이 부품의 세컨드 소스를 확보해야 합니다." },
    { id: 484, day: 8, en: "The supplier audit is planned for next quarter.", ko: "공급업체 감사가 다음 분기에 계획되어 있습니다." },
    { id: 485, day: 8, en: "The quality agreement has been signed.", ko: "품질 협약서가 서명되었습니다." },
    { id: 486, day: 8, en: "The non-conformance report needs to be closed.", ko: "부적합 보고서를 종결해야 합니다." },
    { id: 487, day: 8, en: "The corrective action must be implemented within 30 days.", ko: "시정 조치를 30일 이내에 시행해야 합니다." },
    { id: 488, day: 8, en: "The 8D report is due by end of this week.", ko: "8D 보고서가 이번 주 말까지 마감입니다." },
    { id: 489, day: 8, en: "We are preparing for the IATF 16949 audit.", ko: "IATF 16949 심사를 준비하고 있습니다." },
    { id: 490, day: 8, en: "The customer complaint has been registered.", ko: "고객 클레임이 등록되었습니다." },
    { id: 491, day: 8, en: "The rework rate must be reduced to below 1%.", ko: "재작업률을 1% 이하로 줄여야 합니다." },
    { id: 492, day: 8, en: "The scrap cost is too high for this process.", ko: "이 공정의 스크랩 비용이 너무 높습니다." },
    { id: 493, day: 8, en: "The process capability study results are attached.", ko: "공정 능력 연구 결과가 첨부되어 있습니다." },
    { id: 494, day: 8, en: "The control plan needs to include the new parameter.", ko: "관리 계획에 새 파라미터를 포함해야 합니다." },
    { id: 495, day: 8, en: "The work instruction has been revised.", ko: "작업 지침서가 개정되었습니다." },
    { id: 496, day: 8, en: "The operator training is completed.", ko: "작업자 교육이 완료되었습니다." },
    { id: 497, day: 8, en: "The poka-yoke system prevents assembly errors.", ko: "포카요케 시스템이 조립 오류를 방지합니다." },
    { id: 498, day: 8, en: "The visual inspection criteria need to be updated.", ko: "외관 검사 기준을 업데이트해야 합니다." },
    { id: 499, day: 8, en: "The inventory level is below the safety stock.", ko: "재고 수준이 안전 재고 이하입니다." },
    { id: 500, day: 8, en: "We need to issue a deviation approval for this batch.", ko: "이 배치에 대한 이탈 승인을 발행해야 합니다." },
    { id: 501, day: 8, en: "The project is on track for the planned delivery.", ko: "프로젝트가 계획된 납품에 맞게 진행 중입니다." },
    { id: 502, day: 8, en: "The stakeholder meeting is scheduled for this afternoon.", ko: "이해관계자 회의가 오늘 오후로 예정되어 있습니다." },
    { id: 503, day: 8, en: "Let me share the project dashboard.", ko: "프로젝트 대시보드를 공유하겠습니다." },
    { id: 504, day: 8, en: "The test plan needs to be signed off by the customer.", ko: "테스트 계획서를 고객이 서명해야 합니다." },
    { id: 505, day: 8, en: "The design freeze is effective from today.", ko: "설계 동결이 오늘부터 유효합니다." },
    { id: 506, day: 8, en: "Any further changes require a formal change request.", ko: "추가 변경은 공식적인 변경 요청이 필요합니다." },
    { id: 507, day: 8, en: "The intellectual property belongs to the customer.", ko: "지식 재산권은 고객에게 귀속됩니다." },
    { id: 508, day: 8, en: "The NDA has been signed by both companies.", ko: "양사가 NDA에 서명했습니다." },
    { id: 509, day: 8, en: "Let me check the project timeline and get back to you.", ko: "프로젝트 타임라인을 확인하고 연락드리겠습니다." },
    { id: 510, day: 8, en: "The project review meeting is held bi-weekly.", ko: "프로젝트 리뷰 회의는 격주로 진행됩니다." }
);

DAY_NAMES[8] = "프로젝트 관리 & 일정";
DAY_NAMES_EN[8] = "Project Management & Schedule";
