// EPS 컨퍼런스콜 영어 마스터 - 300문장 데이터
const SENTENCES = [
  // Day 1: 회의 시작 & 기술적 점검 (Opening & Tech Check) - 1~60
  { id: 1, day: 1, en: "Hello everyone, this is Yeongmin from the ES Development Team 2.", ko: "안녕하세요, ES 개발 2팀의 영민입니다." },
  { id: 2, day: 1, en: "Thank you all for joining on time.", ko: "정시에 참석해 주셔서 감사합니다." },
  { id: 3, day: 1, en: "Is everyone on the line?", ko: "모두 접속하셨나요?" },
  { id: 4, day: 1, en: "Who just joined?", ko: "방금 누가 들어오셨나요?" },
  { id: 5, day: 1, en: "Who do we have on the line from the Europe team?", ko: "유럽 팀에서 누가 접속해 계신가요?" },
  { id: 6, day: 1, en: "We are waiting for a few more engineers.", ko: "엔지니어 분들을 몇 분 더 기다리고 있습니다." },
  { id: 7, day: 1, en: "Let's wait a couple of minutes for everyone to join.", ko: "모두 들어올 때까지 2~3분만 기다립시다." },
  { id: 8, day: 1, en: "While we wait, let's do a quick sound check.", ko: "기다리는 동안 사운드 체크 좀 할게요." },
  { id: 9, day: 1, en: "Can everyone hear me clearly?", ko: "제 목소리 잘 들리시나요?" },
  { id: 10, day: 1, en: "Are you able to hear me?", ko: "제 말 들리세요?" },
  { id: 11, day: 1, en: "Loud and clear.", ko: "아주 잘 들립니다." },
  { id: 12, day: 1, en: "I can hear you just fine.", ko: "저는 잘 들려요." },
  { id: 13, day: 1, en: "Can you see my screen?", ko: "제 화면 보이시나요?" },
  { id: 14, day: 1, en: "I'm sharing my screen with the CATIA model now.", ko: "지금 카티아 모델 화면 공유하겠습니다." },
  { id: 15, day: 1, en: "Can everyone see the slide deck?", ko: "슬라이드 자료 보이시나요?" },
  { id: 16, day: 1, en: "Please let me know if you can't see the drawing.", ko: "도면이 안 보이면 말씀해 주세요." },
  { id: 17, day: 1, en: "I think the screen has frozen.", ko: "화면이 멈춘 것 같아요." },
  { id: 18, day: 1, en: "You are on mute.", ko: "음소거 상태이신 것 같아요." },
  { id: 19, day: 1, en: "Could you unmute your microphone?", ko: "마이크 켜주시겠어요?" },
  { id: 20, day: 1, en: "Please mute your microphone when you're not speaking.", ko: "말씀 안 하실 때는 음소거 부탁드립니다." },
  { id: 21, day: 1, en: "There is a lot of background noise.", ko: "주변 소음이 좀 심하네요." },
  { id: 22, day: 1, en: "There is an echo.", ko: "소리가 울려요." },
  { id: 23, day: 1, en: "Your voice is breaking up.", ko: "목소리가 자꾸 끊겨요." },
  { id: 24, day: 1, en: "You're cutting out.", ko: "소리가 끊깁니다." },
  { id: 25, day: 1, en: "We lost you for a second.", ko: "잠깐 소리가 안 들렸어요." },
  { id: 26, day: 1, en: "Could you say that again? The connection is bad.", ko: "다시 말씀해 주시겠어요? 연결이 안 좋네요." },
  { id: 27, day: 1, en: "Let me try reconnecting.", ko: "제가 다시 접속해 볼게요." },
  { id: 28, day: 1, en: "Is the connection better now?", ko: "지금은 연결이 좀 나아졌나요?" },
  { id: 29, day: 1, en: "I'm having trouble connecting to the server.", ko: "서버 접속하는 데 문제가 좀 있네요." },
  { id: 30, day: 1, en: "Let's get started.", ko: "시작합시다." },
  { id: 31, day: 1, en: "Shall we begin?", ko: "시작할까요?" },
  { id: 32, day: 1, en: "Since everyone is here, let's start the design review.", ko: "다 오신 것 같으니 설계 검토 시작하죠." },
  { id: 33, day: 1, en: "First, let's go around the table and introduce ourselves.", ko: "먼저 돌아가며 자기소개합시다." },
  { id: 34, day: 1, en: "Let's do a quick round of introductions.", ko: "빠르게 자기소개 한 번 하죠." },
  { id: 35, day: 1, en: "Please state your name and role.", ko: "이름과 역할을 말씀해 주세요." },
  { id: 36, day: 1, en: "I'll start. I'm Yeongmin, responsible for motor mechanism design.", ko: "제가 먼저 하죠. 저는 모터 기구 설계를 맡은 영민입니다." },
  { id: 37, day: 1, en: "We have a new member joining us today.", ko: "오늘 새로 합류하신 분이 계십니다." },
  { id: 38, day: 1, en: "I'd like to welcome Mr. Schmidt to the team.", ko: "슈미트 님을 환영합니다." },
  { id: 39, day: 1, en: "It's a pleasure to welcome everyone.", ko: "모두 환영합니다." },
  { id: 40, day: 1, en: "I appreciate you all taking the time to join.", ko: "시간 내서 참석해 주셔서 감사합니다." },
  { id: 41, day: 1, en: "Thank you for joining on such short notice.", ko: "갑작스러운 요청에도 참석해 주셔서 감사합니다." },
  { id: 42, day: 1, en: "Does everyone know each other?", ko: "다들 서로 아시나요?" },
  { id: 43, day: 1, en: "I don't think we've met before.", ko: "우리 초면인 것 같네요." },
  { id: 44, day: 1, en: "Nice to meet you all virtually.", ko: "화상으로 뵙게 되어 반갑습니다." },
  { id: 45, day: 1, en: "How was your weekend?", ko: "주말 잘 보내셨나요?" },
  { id: 46, day: 1, en: "How is the weather in Germany?", ko: "독일 날씨는 어떤가요?" },
  { id: 47, day: 1, en: "I hope everyone is safe and healthy.", ko: "모두 건강하시길 바랍니다." },
  { id: 48, day: 1, en: "Is the Project Manager joining us today?", ko: "오늘 PM님도 들어오시나요?" },
  { id: 49, day: 1, en: "We are missing the validation engineer.", ko: "검증 엔지니어분이 아직 안 오셨네요." },
  { id: 50, day: 1, en: "He is having technical difficulties.", ko: "그분이 기술적 문제가 있다고 합니다." },
  { id: 51, day: 1, en: "She cannot make it today.", ko: "그분은 오늘 참석 못 하십니다." },
  { id: 52, day: 1, en: "Let's proceed without him.", ko: "그분 없이 진행합시다." },
  { id: 53, day: 1, en: "I have a hard stop at 5 PM.", ko: "저는 5시에 무조건 나가봐야 합니다." },
  { id: 54, day: 1, en: "I need to jump to another call in 10 minutes.", ko: "10분 뒤에 다른 콜에 들어가야 해요." },
  { id: 55, day: 1, en: "Let's keep this meeting short.", ko: "오늘 회의 짧게 합시다." },
  { id: 56, day: 1, en: "We have a lot to cover today regarding the NVH data.", ko: "오늘 NVH 데이터 관련해서 다룰 내용이 많습니다." },
  { id: 57, day: 1, en: "I'll keep this brief.", ko: "간단히 하겠습니다." },
  { id: 58, day: 1, en: "Please turn on your camera if possible.", ko: "가능하면 카메라를 켜주세요." },
  { id: 59, day: 1, en: "Is it okay if I turn off my video to save bandwidth?", ko: "연결 안정화를 위해 비디오를 꺼도 될까요?" },
  { id: 60, day: 1, en: "Let's kick off the meeting.", ko: "자, 회의를 시작합시다." },

  // Day 2: 안건 진행 & 발표 (Agenda & Presentation) - 61~120
  { id: 61, day: 2, en: "The purpose of today's meeting is to discuss the motor noise issue.", ko: "오늘 회의 목적은 모터 소음 문제를 논의하는 것입니다." },
  { id: 62, day: 2, en: "We are here today to discuss the AI analysis results.", ko: "오늘 AI 분석 결과를 논의하려고 모였습니다." },
  { id: 63, day: 2, en: "Let me walk you through the agenda.", ko: "오늘 안건을 훑어드리겠습니다." },
  { id: 64, day: 2, en: "First, we will cover the NVH results, then move to the design changes.", ko: "먼저 NVH 결과를 다루고, 그다음 설계 변경으로 넘어가겠습니다." },
  { id: 65, day: 2, en: "Does everyone have a copy of the agenda?", ko: "모두 아젠다 받으셨나요?" },
  { id: 66, day: 2, en: "Let's start with the first item.", ko: "첫 번째 안건부터 시작하죠." },
  { id: 67, day: 2, en: "Let's get straight down to business.", ko: "바로 본론으로 들어갑시다." },
  { id: 68, day: 2, en: "I'll give you a quick rundown of the situation.", ko: "상황을 빠르게 설명해 드릴게요." },
  { id: 69, day: 2, en: "Please look at the slide on the screen.", ko: "화면의 슬라이드를 봐주세요." },
  { id: 70, day: 2, en: "As you can see on the graph, the noise level has decreased.", ko: "그래프에서 보시다시피 소음 레벨이 감소했습니다." },
  { id: 71, day: 2, en: "I'd like to hand it over to our software engineer.", ko: "소프트웨어 엔지니어에게 마이크를 넘기겠습니다." },
  { id: 72, day: 2, en: "Mr. Kim, over to you.", ko: "김 선임님, 말씀해 주세요." },
  { id: 73, day: 2, en: "Thanks, Yeongmin. Taking over from here...", ko: "감사합니다, 영민 님. 이어서 제가 하겠습니다..." },
  { id: 74, day: 2, en: "Let's move on to the next topic.", ko: "다음 주제로 넘어갑시다." },
  { id: 75, day: 2, en: "Are there any questions so far regarding the logic?", ko: "로직 관련해서 지금까지 질문 있나요?" },
  { id: 76, day: 2, en: "Let me elaborate on that design choice.", ko: "그 설계 선택에 대해 좀 더 부연 설명하겠습니다." },
  { id: 77, day: 2, en: "To put it simply, it improves durability.", ko: "간단히 말하자면, 내구성을 향상시킵니다." },
  { id: 78, day: 2, en: "In other words, we need to modify the housing.", ko: "다시 말해서, 하우징을 수정해야 합니다." },
  { id: 79, day: 2, en: "This leads me to my next point about cost.", ko: "이것이 제 다음 요점인 비용 문제로 이어집니다." },
  { id: 80, day: 2, en: "I'd like to point out that the tolerance is tight.", ko: "공차가 타이트하다는 점을 지적하고 싶습니다." },
  { id: 81, day: 2, en: "It is important to note that this is a safety part.", ko: "이것이 보안 부품이라는 점을 유의해야 합니다." },
  { id: 82, day: 2, en: "Let's focus on the main issue: vibration.", ko: "주요 쟁점인 진동 문제에 집중합시다." },
  { id: 83, day: 2, en: "We are getting off track.", ko: "주제가 좀 빗나간 것 같네요." },
  { id: 84, day: 2, en: "Let's get back to the topic of the controller.", ko: "다시 제어기 주제로 돌아갑시다." },
  { id: 85, day: 2, en: "We can discuss the timeline later.", ko: "일정은 나중에 논의하죠." },
  { id: 86, day: 2, en: "Let's take that offline.", ko: "그건 회의 끝나고 따로 이야기하죠." },
  { id: 87, day: 2, en: "We are running out of time.", ko: "시간이 부족하네요." },
  { id: 88, day: 2, en: "Let's speed things up a little.", ko: "속도를 좀 냅시다." },
  { id: 89, day: 2, en: "I'll skip this slide about the background.", ko: "배경 설명 슬라이드는 건너뛰겠습니다." },
  { id: 90, day: 2, en: "Can you engage in this part regarding the simulation?", ko: "시뮬레이션 관련해서 설명해 주실 수 있나요?" },
  { id: 91, day: 2, en: "Who is going to cover the Top-Down design process?", ko: "Top-Down 설계 프로세스는 누가 다루나요?" },
  { id: 92, day: 2, en: "Does anyone have anything to add?", ko: "추가하실 말씀 있나요?" },
  { id: 93, day: 2, en: "I have a question about this slide.", ko: "이 슬라이드에 질문 있습니다." },
  { id: 94, day: 2, en: "Could you go back to the previous slide?", ko: "이전 장으로 돌아가 주실래요?" },
  { id: 95, day: 2, en: "Please turn to page 5.", ko: "5페이지를 펴주세요." },
  { id: 96, day: 2, en: "The main takeaway here is the ndc value.", ko: "여기서 핵심은 ndc 값입니다." },
  { id: 97, day: 2, en: "Based on the NVH data...", ko: "NVH 데이터에 근거하면..." },
  { id: 98, day: 2, en: "From my perspective as a designer...", ko: "설계자로서 제 관점에서는..." },
  { id: 99, day: 2, en: "The bottom line is we passed the test.", ko: "결론은 우리가 테스트를 통과했다는 것입니다." },
  { id: 100, day: 2, en: "Let's pause here for a moment.", ko: "잠깐 여기서 멈춥시다." },
  { id: 101, day: 2, en: "I'd like to highlight the efficiency improvement.", ko: "효율 개선을 강조하고 싶습니다." },
  { id: 102, day: 2, en: "Are we on the same page?", ko: "우리 같은 생각인 거 맞죠?" },
  { id: 103, day: 2, en: "Does that make sense?", ko: "이해가 되시나요?" },
  { id: 104, day: 2, en: "Am I making myself clear?", ko: "제 말이 명확한가요?" },
  { id: 105, day: 2, en: "I hope I explained the mechanism clearly.", ko: "메커니즘 설명이 잘 되었길 바랍니다." },
  { id: 106, day: 2, en: "Basically, what this means is we need a new mold.", ko: "기본적으로 이게 무슨 뜻이냐면 금형을 새로 파야 한다는 겁니다." },
  { id: 107, day: 2, en: "Let me give you an example of a similar case.", ko: "비슷한 사례를 하나 들어보겠습니다." },
  { id: 108, day: 2, en: "For instance, the Project A motor.", ko: "예를 들어, 프로젝트 A 모터의 경우입니다." },
  { id: 109, day: 2, en: "Moving on to the compliance matrix.", ko: "규제 준수 매트릭스로 넘어가겠습니다." },
  { id: 110, day: 2, en: "That covers the first item.", ko: "첫 번째 안건은 이걸로 마칩니다." },
  { id: 111, day: 2, en: "Let's turn to the next item: power pack design.", ko: "다음 안건인 파워팩 설계로 넘어갑시다." },
  { id: 112, day: 2, en: "We need to prioritize this task.", ko: "이 업무의 우선순위를 정해야 합니다." },
  { id: 113, day: 2, en: "What is the timeline on that?", ko: "그 건의 일정은 어떻게 되나요?" },
  { id: 114, day: 2, en: "When can we expect this simulation to be done?", ko: "시뮬레이션이 언제 완료될 것으로 예상하나요?" },
  { id: 115, day: 2, en: "Is everything going according to plan?", ko: "계획대로 진행되고 있나요?" },
  { id: 116, day: 2, en: "We are behind schedule due to the holiday.", ko: "휴일 때문에 일정이 지연되고 있습니다." },
  { id: 117, day: 2, en: "We are ahead of schedule.", ko: "일정이 앞당겨지고 있습니다." },
  { id: 118, day: 2, en: "Can you update us on the status of the prototype?", ko: "프로토타입 현황 업데이트 좀 해주시겠어요?" },
  { id: 119, day: 2, en: "Please fill us in on the details.", ko: "세부 사항 좀 알려주세요." },
  { id: 120, day: 2, en: "Let's wrap up this section.", ko: "이 섹션은 마무리하죠." },

  // Day 3: 토론, 의견 교환 & 끼어들기 (Discussion & Interaction) - 121~180
  { id: 121, day: 3, en: "What are your thoughts on this design change?", ko: "이 설계 변경에 대해 어떻게 생각하세요?" },
  { id: 122, day: 3, en: "I'd like to hear your opinion.", ko: "당신의 의견을 듣고 싶습니다." },
  { id: 123, day: 3, en: "Any comments on the Python script results?", ko: "파이썬 스크립트 결과에 대해 코멘트 있으신가요?" },
  { id: 124, day: 3, en: "The floor is yours.", ko: "발언하시죠." },
  { id: 125, day: 3, en: "May I say something regarding the motor specs?", ko: "모터 사양 관련해서 한마디 해도 될까요?" },
  { id: 126, day: 3, en: "Can I add something here?", ko: "여기에 덧붙여도 될까요?" },
  { id: 127, day: 3, en: "I have a point to make about the controller.", ko: "제어기에 대해 드릴 말씀이 있습니다." },
  { id: 128, day: 3, en: "Sorry to interrupt, but I have a question.", ko: "끼어들어서 죄송합니다만 질문이 있습니다." },
  { id: 129, day: 3, en: "May I jump in for a second?", ko: "잠깐 끼어들어도 될까요?" },
  { id: 130, day: 3, en: "Could I interrupt you for a minute?", ko: "잠시 말 좀 끊어도 될까요?" },
  { id: 131, day: 3, en: "Sorry, go ahead.", ko: "죄송합니다. 먼저 말씀하세요." },
  { id: 132, day: 3, en: "Please go on.", ko: "계속하세요." },
  { id: 133, day: 3, en: "After you.", ko: "먼저 하세요." },
  { id: 134, day: 3, en: "I agree with you on the tolerance issue.", ko: "공차 문제에 대해 동의합니다." },
  { id: 135, day: 3, en: "I couldn't agree more.", ko: "전적으로 동의합니다." },
  { id: 136, day: 3, en: "You have a point there regarding safety.", ko: "안전과 관련해 일리 있는 말씀입니다." },
  { id: 137, day: 3, en: "That sounds good to me.", ko: "좋습니다." },
  { id: 138, day: 3, en: "I'm with you on that strategy.", ko: "저도 그 전략에 동의합니다." },
  { id: 139, day: 3, en: "That's exactly how I feel.", ko: "제 생각이 바로 그겁니다." },
  { id: 140, day: 3, en: "That's a great idea to use AI.", ko: "AI를 사용하자는 건 좋은 생각이네요." },
  { id: 141, day: 3, en: "I'm afraid I disagree with the cost estimation.", ko: "유감스럽지만 비용 추정에 동의하지 않습니다." },
  { id: 142, day: 3, en: "I see your point, but it risks quality.", ko: "무슨 말씀인지는 알겠지만 품질 위험이 있습니다." },
  { id: 143, day: 3, en: "I have a slightly different view on the layout.", ko: "레이아웃에 대해 저는 견해가 조금 다릅니다." },
  { id: 144, day: 3, en: "That's not entirely true based on the data.", ko: "데이터에 따르면 전적으로 사실인 건 아닙니다." },
  { id: 145, day: 3, en: "I'm not sure about that specification.", ko: "그 사양은 확신이 안 서네요." },
  { id: 146, day: 3, en: "With all due respect, the drawing is correct.", ko: "외람된 말씀이지만, 도면은 맞습니다." },
  { id: 147, day: 3, en: "Can we consider another option for the material?", ko: "재질에 대해 다른 옵션을 고려해 볼 수 있을까요?" },
  { id: 148, day: 3, en: "What if we try the skeleton modeling instead?", ko: "대신 스켈레톤 모델링을 써보면 어떨까요?" },
  { id: 149, day: 3, en: "I suggest we update the firmware.", ko: "펌웨어를 업데이트하는 것을 제안합니다." },
  { id: 150, day: 3, en: "My recommendation is to re-run the test.", ko: "제 추천은 테스트를 다시 돌리는 것입니다." },
  { id: 151, day: 3, en: "Why don't we check the NG product samples?", ko: "NG 제품 샘플을 확인해보는 게 어때요?" },
  { id: 152, day: 3, en: "How about applying a fail-safe logic to the control algorithm?", ko: "제어 알고리즘에 페일세이프(Fail-safe) 로직을 적용해보는 건 어때요?" },
  { id: 153, day: 3, en: "Are there any objections to this layout?", ko: "이 레이아웃에 반대 있으신가요?" },
  { id: 154, day: 3, en: "If there are no objections, let's proceed with tooling.", ko: "이의 없으시면 금형 제작 진행하겠습니다." },
  { id: 155, day: 3, en: "Let's take a vote.", ko: "투표로 결정하죠." },
  { id: 156, day: 3, en: "All in favor?", ko: "찬성하시는 분?" },
  { id: 157, day: 3, en: "Any opposing views?", ko: "반대 의견 있나요?" },
  { id: 158, day: 3, en: "It seems we have a consensus on the design.", ko: "설계에 대해 합의가 된 것 같군요." },
  { id: 159, day: 3, en: "We seem to be split on this issue.", ko: "이 문제에 대해 의견이 갈리는 것 같네요." },
  { id: 160, day: 3, en: "Let's compromise on the deadline.", ko: "마감일에 대해 타협점을 찾읍시다." },
  { id: 161, day: 3, en: "Let's find a middle ground.", ko: "절충안을 찾읍시다." },
  { id: 162, day: 3, en: "Let's hold off on that discussion until we have data.", ko: "데이터가 나올 때까지 그 논의는 보류하죠." },
  { id: 163, day: 3, en: "Let's circle back to that later.", ko: "나중에 다시 이야기하죠." },
  { id: 164, day: 3, en: "Let's park this idea for now.", ko: "이 아이디어는 일단 킵해둡시다." },
  { id: 165, day: 3, en: "I'd appreciate your input on this NVH issue.", ko: "이 NVH 문제에 대한 조언 부탁드립니다." },
  { id: 166, day: 3, en: "Could you be more specific about the error code?", ko: "에러 코드에 대해 좀 더 구체적으로 말씀해 주시겠어요?" },
  { id: 167, day: 3, en: "Could you clarify the requirement?", ko: "요구사항을 명확하게 설명해 주시겠어요?" },
  { id: 168, day: 3, en: 'What do you mean exactly by "power loss"?', ko: '"전력 손실"이 정확히 무슨 뜻인가요?' },
  { id: 169, day: 3, en: "Can you give me an example of the defect?", ko: "불량 예시를 들어 주실 수 있나요?" },
  { id: 170, day: 3, en: "I'm curious to hear your point of view as a client.", ko: "고객으로서의 관점이 궁금합니다." },
  { id: 171, day: 3, en: "Let's brainstorm some ideas for cost reduction.", ko: "원가 절감을 위해 아이디어를 좀 모아봅시다." },
  { id: 172, day: 3, en: "Think outside the box.", ko: "창의적으로 생각해 보세요." },
  { id: 173, day: 3, en: "Let's look at the bigger picture.", ko: "큰 그림을 봅시다." },
  { id: 174, day: 3, en: "Let's weigh the pros and cons of the new motor.", ko: "새 모터의 장단점을 따져봅시다." },
  { id: 175, day: 3, en: "Let's not jump to conclusions.", ko: "속단하지 맙시다." },
  { id: 176, day: 3, en: "That's a valid point regarding heat dissipation.", ko: "방열과 관련해 타당한 지적입니다." },
  { id: 177, day: 3, en: "I appreciate your feedback.", ko: "피드백 감사합니다." },
  { id: 178, day: 3, en: "Thank you for bringing that up.", ko: "그 점을 언급해 주셔서 감사합니다." },
  { id: 179, day: 3, en: "That's an excellent question regarding the controller.", ko: "제어기에 대한 아주 좋은 질문입니다." },
  { id: 180, day: 3, en: "I'm glad you asked that.", ko: "물어봐 주셔서 감사합니다." },

  // Day 4: 문제 해결 & 다시 묻기 (Problem Solving & Clarification) - 181~240
  { id: 181, day: 4, en: "Sorry, I didn't get that.", ko: "죄송합니다. 못 알아들었어요." },
  { id: 182, day: 4, en: "Could you say that again?", ko: "다시 말씀해 주시겠어요?" },
  { id: 183, day: 4, en: "Could you repeat that, please?", ko: "반복해 주시겠어요?" },
  { id: 184, day: 4, en: "Would you mind repeating that technical term?", ko: "방금 그 전문 용어 다시 말씀해 주실 수 있을까요?" },
  { id: 185, day: 4, en: "I missed the last part about the spec.", ko: "사양에 대한 마지막 부분을 놓쳤습니다." },
  { id: 186, day: 4, en: "Could you speak a little louder?", ko: "좀 더 크게 말씀해 주시겠어요?" },
  { id: 187, day: 4, en: "Could you speak more slowly?", ko: "좀 더 천천히 말씀해 주시겠어요?" },
  { id: 188, day: 4, en: "My English is a bit rusty, so bear with me.", ko: "제 영어가 좀 서툴러서요, 양해 부탁드립니다." },
  { id: 189, day: 4, en: "Please bear with me.", ko: "조금만 양해해 주세요." },
  { id: 190, day: 4, en: "Could you explain that in layman's terms?", ko: "비전문가도 알기 쉽게 설명해 주시겠어요?" },
  { id: 191, day: 4, en: "Could you spell that for me?", ko: "스펠링 좀 알려주시겠어요?" },
  { id: 192, day: 4, en: "So, what you're saying is we need to change the PCB. Right?", ko: "그러니까 PCB를 바꿔야 한다는 거죠, 맞나요?" },
  { id: 193, day: 4, en: "Let me check if I understood correctly.", ko: "제대로 이해했는지 확인해 볼게요." },
  { id: 194, day: 4, en: "If I understood you correctly, you mean the ndc value is too low.", ko: "제가 제대로 이해했다면, ndc 값이 너무 낮다는 뜻이군요." },
  { id: 195, day: 4, en: "Sorry, I was on mute.", ko: "죄송해요, 음소거 상태였네요." },
  { id: 196, day: 4, en: "My connection is unstable.", ko: "제 연결이 불안정합니다." },
  { id: 197, day: 4, en: "I'm experiencing some technical issues.", ko: "기술적인 문제가 좀 있습니다." },
  { id: 198, day: 4, en: "I'll have to restart my computer.", ko: "컴퓨터를 재부팅해야 할 것 같아요." },
  { id: 199, day: 4, en: "Can you hear me now?", ko: "이제 들리세요?" },
  { id: 200, day: 4, en: "Is that better?", ko: "이제 좀 낫나요?" },
  { id: 201, day: 4, en: "The audio is out of sync.", ko: "오디오 싱크가 안 맞아요." },
  { id: 202, day: 4, en: "Can you type that in the chat box?", ko: "채팅창에 써주시겠어요?" },
  { id: 203, day: 4, en: "I'll send the CATIA file via email.", ko: "이메일로 카티아 파일 보내드릴게요." },
  { id: 204, day: 4, en: "I don't have access to that file.", ko: "그 파일에 접근 권한이 없어요." },
  { id: 205, day: 4, en: "Could you grant me access to the server?", ko: "서버 접근 권한 좀 주시겠어요?" },
  { id: 206, day: 4, en: "There seems to be a delay.", ko: "지연이 좀 있는 것 같네요." },
  { id: 207, day: 4, en: "Let's wait for the PM to rejoin.", ko: "PM님이 다시 들어오길 기다리죠." },
  { id: 208, day: 4, en: "Let's try turning off the video.", ko: "비디오를 끄고 해봅시다." },
  { id: 209, day: 4, en: "We have a problem with the durability test.", ko: "내구 테스트에 문제가 있습니다." },
  { id: 210, day: 4, en: "This is a critical issue for mass production.", ko: "이건 양산에 있어 치명적인 문제입니다." },
  { id: 211, day: 4, en: "We need to address this noise immediately.", ko: "즉시 이 소음 문제를 해결해야 합니다." },
  { id: 212, day: 4, en: "What is the root cause of the vibration?", ko: "진동의 근본 원인이 뭔가요?" },
  { id: 213, day: 4, en: "How do we fix this bug?", ko: "이 버그를 어떻게 고치죠?" },
  { id: 214, day: 4, en: "I have a solution using the new logic.", ko: "새 로직을 이용한 해결책이 있습니다." },
  { id: 215, day: 4, en: "It's a temporary fix.", ko: "임시방편입니다." },
  { id: 216, day: 4, en: "We need a long-term solution.", ko: "장기적인 해결책이 필요합니다." },
  { id: 217, day: 4, en: "I'm not in a position to decide on the budget.", ko: "제가 예산을 결정할 위치가 아닙니다." },
  { id: 218, day: 4, en: "I need to check with my team leader.", ko: "팀장님과 확인해 봐야 합니다." },
  { id: 219, day: 4, en: "Let me find out and get back to you.", ko: "알아보고 다시 연락드릴게요." },
  { id: 220, day: 4, en: "I'll get back to you on that data.", ko: "그 데이터는 나중에 다시 말씀드릴게요." },
  { id: 221, day: 4, en: "That's a good point, but it's expensive.", ko: "좋은 지적입니다만, 비쌉니다." },
  { id: 222, day: 4, en: "I understand your concern about delivery.", ko: "납품에 대한 우려 이해합니다." },
  { id: 223, day: 4, en: "Let's look for alternatives.", ko: "대안을 찾아봅시다." },
  { id: 224, day: 4, en: "We are running into some trouble with the supplier.", ko: "공급업체와 몇 가지 문제가 생겼습니다." },
  { id: 225, day: 4, en: "It's not feasible within this week.", ko: "이번 주 내로는 불가능합니다." },
  { id: 226, day: 4, en: "It's out of our hands.", ko: "우리 손을 떠난 문제입니다." },
  { id: 227, day: 4, en: "Let's escalate this issue to management.", ko: "이 문제를 경영진에 보고합시다." },
  { id: 228, day: 4, en: "Who is responsible for the analysis?", ko: "분석 담당자가 누구죠?" },
  { id: 229, day: 4, en: "Can you take care of this error?", ko: "이 에러 처리해 주실 수 있나요?" },
  { id: 230, day: 4, en: "I'll handle the drawing modification.", ko: "도면 수정은 제가 처리하겠습니다." },
  { id: 231, day: 4, en: "Leave it with me.", ko: "저에게 맡겨주세요." },
  { id: 232, day: 4, en: "I'll look into the code.", ko: "제가 코드를 살펴보겠습니다." },
  { id: 233, day: 4, en: "We need more NVH data.", ko: "NVH 데이터가 더 필요합니다." },
  { id: 234, day: 4, en: "Let's proceed with caution.", ko: "신중하게 진행합시다." },
  { id: 235, day: 4, en: "Let's minimize the risk of failure.", ko: "실패 위험을 최소화합시다." },
  { id: 236, day: 4, en: "Are there any other issues with the prototype?", ko: "프로토타입에 다른 문제 있나요?" },
  { id: 237, day: 4, en: "Let's resolve this quickly.", ko: "빨리 해결합시다." },
  { id: 238, day: 4, en: "Thank you for your patience.", ko: "기다려 주셔서 감사합니다." },
  { id: 239, day: 4, en: "Sorry for the confusion regarding the version.", ko: "버전 관련해 혼란을 드려 죄송합니다." },
  { id: 240, day: 4, en: "Let's clear this up.", ko: "이 문제를 명확히 해결합시다." },

  // Day 5: 마무리 & 후속 조치 (Closing & Follow-up) - 241~300
  { id: 241, day: 5, en: "I think we've covered everything regarding the EPS.", ko: "EPS 관련해서 다룰 내용은 다 다룬 것 같네요." },
  { id: 242, day: 5, en: "That wraps up our agenda.", ko: "이것으로 안건을 마칩니다." },
  { id: 243, day: 5, en: "Let's summarize the main points.", ko: "주요 내용을 요약해 봅시다." },
  { id: 244, day: 5, en: "To recap, we will modify the motor housing.", ko: "요약하자면, 모터 하우징을 수정하기로 했습니다." },
  { id: 245, day: 5, en: "So, we decided to use the AI program.", ko: "그래서, 우리는 AI 프로그램을 사용하기로 결정했습니다." },
  { id: 246, day: 5, en: "Let's go over the action items.", ko: "실행 과제들을 점검해 봅시다." },
  { id: 247, day: 5, en: "Who is doing what by when?", ko: "누가 언제까지 무엇을 하나요?" },
  { id: 248, day: 5, en: "Yeongmin, you will take care of the CATIA modeling, right?", ko: "영민 님, CATIA 모델링 맡으시는 거 맞죠?" },
  { id: 249, day: 5, en: "Please send me the report by Friday.", ko: "금요일까지 보고서 보내주세요." },
  { id: 250, day: 5, en: "The deadline is next Monday.", ko: "마감은 다음 주 월요일입니다." },
  { id: 251, day: 5, en: "Can you meet the deadline?", ko: "마감일 맞출 수 있나요?" },
  { id: 252, day: 5, en: "I'll send out the meeting minutes.", ko: "회의록 보내드리겠습니다." },
  { id: 253, day: 5, en: "I'll email you the summary.", ko: "요약본 이메일로 보낼게요." },
  { id: 254, day: 5, en: "Let's schedule a follow-up meeting to check the status.", ko: "현황 체크를 위해 후속 회의 일정을 잡읍시다." },
  { id: 255, day: 5, en: "When is our next meeting?", ko: "다음 회의는 언제인가요?" },
  { id: 256, day: 5, en: "Same time next week?", ko: "다음 주 같은 시간 어때요?" },
  { id: 257, day: 5, en: "I'll send a calendar invite.", ko: "캘린더 초대장 보내드릴게요." },
  { id: 258, day: 5, en: "Does anyone have any final questions?", ko: "마지막으로 질문 있나요?" },
  { id: 259, day: 5, en: "Any last thoughts?", ko: "마지막으로 하실 말씀?" },
  { id: 260, day: 5, en: "If there are no further questions, we can end here.", ko: "더 이상 질문이 없으시면 여기서 마치죠." },
  { id: 261, day: 5, en: "Let's call it a day.", ko: "오늘은 여기까지 하죠." },
  { id: 262, day: 5, en: "Let's wrap it up here.", ko: "여기서 마무리합시다." },
  { id: 263, day: 5, en: "Thank you for your time today.", ko: "오늘 시간 내주셔서 감사합니다." },
  { id: 264, day: 5, en: "Thank you for your contribution to the project.", ko: "프로젝트에 기여해 주셔서 감사합니다." },
  { id: 265, day: 5, en: "It was a productive meeting.", ko: "생산적인 회의였습니다." },
  { id: 266, day: 5, en: "Good job everyone.", ko: "모두 수고하셨습니다." },
  { id: 267, day: 5, en: "Have a great day.", ko: "좋은 하루 보내세요." },
  { id: 268, day: 5, en: "Have a good evening.", ko: "좋은 저녁 보내세요." },
  { id: 269, day: 5, en: "Enjoy your weekend.", ko: "주말 잘 보내세요." },
  { id: 270, day: 5, en: "Speak to you soon.", ko: "조만간 또 이야기하죠." },
  { id: 271, day: 5, en: "See you next time.", ko: "다음에 뵙겠습니다." },
  { id: 272, day: 5, en: "I look forward to our next meeting.", ko: "다음 회의 기대하겠습니다." },
  { id: 273, day: 5, en: "Please stay on the line for a moment.", ko: "잠시만 끊지 말고 기다려 주세요." },
  { id: 274, day: 5, en: "You may disconnect now.", ko: "이제 나가셔도 됩니다." },
  { id: 275, day: 5, en: "I'm signing off now.", ko: "저 이제 로그아웃합니다." },
  { id: 276, day: 5, en: "Bye for now.", ko: "안녕히 계세요." },
  { id: 277, day: 5, en: "Take care.", ko: "건강하세요." },
  { id: 278, day: 5, en: "I'll keep you posted on the test results.", ko: "테스트 결과 계속 알려드릴게요." },
  { id: 279, day: 5, en: "Please keep me in the loop regarding the client's feedback.", ko: "고객 피드백에 대해 저에게도 계속 공유해 주세요." },
  { id: 280, day: 5, en: "Let's keep in touch.", ko: "계속 연락합시다." },
  { id: 281, day: 5, en: "Don't hesitate to contact me if you have issues.", ko: "문제 있으면 주저 말고 연락 주세요." },
  { id: 282, day: 5, en: "Feel free to email me.", ko: "편하게 이메일 주세요." },
  { id: 283, day: 5, en: "I'll verify and confirm via email.", ko: "확인 후 이메일로 확답 드릴게요." },
  { id: 284, day: 5, en: "Let's finalize this by email.", ko: "이메일로 최종 마무리하죠." },
  { id: 285, day: 5, en: "I'll share the recording of this call.", ko: "이번 콜 녹화본 공유하겠습니다." },
  { id: 286, day: 5, en: "Is there anything else?", ko: "다른 거 더 있나요?" },
  { id: 287, day: 5, en: "That should be all.", ko: "그게 다인 것 같네요." },
  { id: 288, day: 5, en: "We made good progress today.", ko: "오늘 진전이 많이 있었네요." },
  { id: 289, day: 5, en: "I appreciate your hard work.", ko: "노고에 감사드립니다." },
  { id: 290, day: 5, en: "Let's close the meeting.", ko: "회의 마칩시다." },
  { id: 291, day: 5, en: "Meeting adjourned.", ko: "회의 종료합니다." },
  { id: 292, day: 5, en: "I have to run to another meeting.", ko: "전 다른 회의가 있어서 이만 가봐야겠습니다." },
  { id: 293, day: 5, en: "Catch you later.", ko: "나중에 봐요." },
  { id: 294, day: 5, en: "Talk to you later.", ko: "나중에 얘기해요." },
  { id: 295, day: 5, en: "Cheers.", ko: "감사합니다." },
  { id: 296, day: 5, en: "Thanks everyone.", ko: "모두 감사합니다." },
  { id: 297, day: 5, en: "Good bye everyone.", ko: "모두 안녕히 계세요." },
  { id: 298, day: 5, en: "Looking forward to your feedback on the drawing.", ko: "도면에 대한 피드백 기다리겠습니다." },
  { id: 299, day: 5, en: "Please review the attached document.", ko: "첨부된 문서를 검토해 주세요." },
  { id: 300, day: 5, en: "That's a wrap.", ko: "마무리합시다." }
];

const DAY_NAMES = {
  1: "회의 시작 & 기술 점검",
  2: "안건 진행 & 발표",
  3: "토론 & 의견 교환",
  4: "문제 해결 & 확인",
  5: "마무리 & 후속 조치"
};

const DAY_NAMES_EN = {
  1: "Opening & Tech Check",
  2: "Agenda & Presentation",
  3: "Discussion & Interaction",
  4: "Problem Solving & Clarification",
  5: "Closing & Follow-up"
};
