// ✈️ 여행 영어 마스터 - 275문장 (5일 과정)
const SENTENCES_TRAVEL = [
    // ===== Day 1: 공항 & 입국심사 (Airport & Immigration) — 55문장 =====
    { id: 1, day: 1, en: "Where is the check-in counter for my flight?", ko: "제 항공편 체크인 카운터가 어디에 있나요?" },
    { id: 2, day: 1, en: "I'd like a window seat, please.", ko: "창가 좌석으로 부탁드립니다." },
    { id: 3, day: 1, en: "Can I get an aisle seat instead?", ko: "통로 좌석으로 바꿀 수 있나요?" },
    { id: 4, day: 1, en: "How many bags can I check in?", ko: "수하물 몇 개까지 부칠 수 있나요?" },
    { id: 5, day: 1, en: "My luggage is overweight. How much is the extra fee?", ko: "짐이 초과됐어요. 추가 요금이 얼마인가요?" },
    { id: 6, day: 1, en: "Is this bag small enough for carry-on?", ko: "이 가방은 기내 반입이 가능한 크기인가요?" },
    { id: 7, day: 1, en: "Where is the departure gate?", ko: "출발 게이트가 어디인가요?" },
    { id: 8, day: 1, en: "What time does boarding start?", ko: "탑승은 몇 시에 시작하나요?" },
    { id: 9, day: 1, en: "Is my flight on time?", ko: "제 항공편은 정시 출발인가요?" },
    { id: 10, day: 1, en: "My flight has been delayed.", ko: "제 항공편이 지연되었습니다." },
    { id: 11, day: 1, en: "How long is the delay?", ko: "얼마나 지연되나요?" },
    { id: 12, day: 1, en: "Where is the duty-free shop?", ko: "면세점은 어디에 있나요?" },
    { id: 13, day: 1, en: "Can I use this lounge with my boarding pass?", ko: "이 탑승권으로 라운지 이용이 가능한가요?" },
    { id: 14, day: 1, en: "Where can I charge my phone?", ko: "휴대폰은 어디서 충전할 수 있나요?" },
    { id: 15, day: 1, en: "Is there free Wi-Fi at the airport?", ko: "공항에 무료 와이파이가 있나요?" },
    { id: 16, day: 1, en: "I need to transfer to another flight.", ko: "다른 비행기로 환승해야 합니다." },
    { id: 17, day: 1, en: "Where is the transit area?", ko: "환승 구역이 어디인가요?" },
    { id: 18, day: 1, en: "How much time do I have for my connection?", ko: "환승 시간이 얼마나 되나요?" },
    { id: 19, day: 1, en: "I missed my connecting flight.", ko: "환승편을 놓쳤습니다." },
    { id: 20, day: 1, en: "Can you rebook me on the next available flight?", ko: "다음 가능한 항공편으로 재예약해 주시겠어요?" },
    { id: 21, day: 1, en: "Excuse me, can I have a blanket?", ko: "실례합니다, 담요 하나 주시겠어요?" },
    { id: 22, day: 1, en: "Could I have some water, please?", ko: "물 좀 주시겠어요?" },
    { id: 23, day: 1, en: "What do you have for the in-flight meal?", ko: "기내식 메뉴가 뭐가 있나요?" },
    { id: 24, day: 1, en: "I'll have the chicken, please.", ko: "치킨으로 주세요." },
    { id: 25, day: 1, en: "Could I have a cup of coffee?", ko: "커피 한 잔 주시겠어요?" },
    { id: 26, day: 1, en: "Can I recline my seat?", ko: "좌석을 뒤로 젖혀도 될까요?" },
    { id: 27, day: 1, en: "How much longer until we land?", ko: "착륙까지 얼마나 남았나요?" },
    { id: 28, day: 1, en: "What is the local time at our destination?", ko: "목적지 현지 시간이 어떻게 되나요?" },
    { id: 29, day: 1, en: "Do I need to fill out an arrival card?", ko: "입국신고서를 작성해야 하나요?" },
    { id: 30, day: 1, en: "Could you help me fill out this form?", ko: "이 양식 작성하는 것 좀 도와주시겠어요?" },
    { id: 31, day: 1, en: "What is the purpose of your visit?", ko: "방문 목적이 무엇인가요?" },
    { id: 32, day: 1, en: "I'm here on vacation.", ko: "관광 목적으로 왔습니다." },
    { id: 33, day: 1, en: "I'm here for sightseeing.", ko: "여행하러 왔습니다." },
    { id: 34, day: 1, en: "I'm traveling for business.", ko: "출장으로 왔습니다." },
    { id: 35, day: 1, en: "How long will you be staying?", ko: "얼마나 머무르실 건가요?" },
    { id: 36, day: 1, en: "I'll be staying for five days.", ko: "5일 동안 머무를 예정입니다." },
    { id: 37, day: 1, en: "Where will you be staying?", ko: "어디에서 머무르실 건가요?" },
    { id: 38, day: 1, en: "I'm staying at the Hilton Hotel.", ko: "힐튼 호텔에 머무릅니다." },
    { id: 39, day: 1, en: "Do you have anything to declare?", ko: "신고할 물품이 있으신가요?" },
    { id: 40, day: 1, en: "No, I have nothing to declare.", ko: "아니요, 신고할 것이 없습니다." },
    { id: 41, day: 1, en: "Please open your bag for inspection.", ko: "검사를 위해 가방을 열어주세요." },
    { id: 42, day: 1, en: "These are personal items.", ko: "이것들은 개인 물품입니다." },
    { id: 43, day: 1, en: "This is a gift for my friend.", ko: "이것은 친구에게 줄 선물입니다." },
    { id: 44, day: 1, en: "Where is the baggage claim area?", ko: "수하물 찾는 곳이 어디인가요?" },
    { id: 45, day: 1, en: "Which carousel is for flight KE012?", ko: "KE012편 수하물은 몇 번 벨트인가요?" },
    { id: 46, day: 1, en: "My suitcase hasn't come out yet.", ko: "제 캐리어가 아직 안 나왔어요." },
    { id: 47, day: 1, en: "I think my luggage is lost.", ko: "제 수하물이 분실된 것 같아요." },
    { id: 48, day: 1, en: "Could you help me find my bag?", ko: "제 가방을 찾는 것 좀 도와주시겠어요?" },
    { id: 49, day: 1, en: "Here is my baggage claim tag.", ko: "여기 수하물 태그입니다." },
    { id: 50, day: 1, en: "Where can I get a SIM card?", ko: "유심칩을 어디서 살 수 있나요?" },
    { id: 51, day: 1, en: "Where is the currency exchange?", ko: "환전소가 어디에 있나요?" },
    { id: 52, day: 1, en: "I'd like to exchange Korean won for dollars.", ko: "한국 원화를 달러로 환전하고 싶습니다." },
    { id: 53, day: 1, en: "What is the exchange rate today?", ko: "오늘 환율이 어떻게 되나요?" },
    { id: 54, day: 1, en: "Where is the taxi stand?", ko: "택시 승강장이 어디인가요?" },
    { id: 55, day: 1, en: "Is there an airport shuttle to the city center?", ko: "시내로 가는 공항 셔틀이 있나요?" },

    // ===== Day 2: 교통 & 길찾기 (Transportation & Directions) — 55문장 =====
    { id: 56, day: 2, en: "How do I get to the subway station?", ko: "지하철역은 어떻게 가나요?" },
    { id: 57, day: 2, en: "Where is the nearest bus stop?", ko: "가장 가까운 버스 정류장이 어디인가요?" },
    { id: 58, day: 2, en: "Which bus goes to the city center?", ko: "시내로 가는 버스가 어떤 건가요?" },
    { id: 59, day: 2, en: "How much is a one-way ticket?", ko: "편도 요금이 얼마인가요?" },
    { id: 60, day: 2, en: "I'd like a round-trip ticket, please.", ko: "왕복 티켓 주세요." },
    { id: 61, day: 2, en: "Can I buy a day pass?", ko: "1일 이용권을 살 수 있나요?" },
    { id: 62, day: 2, en: "Where can I buy a transit card?", ko: "교통카드를 어디서 살 수 있나요?" },
    { id: 63, day: 2, en: "How do I top up my transit card?", ko: "교통카드를 어떻게 충전하나요?" },
    { id: 64, day: 2, en: "Which line should I take to get to the museum?", ko: "박물관에 가려면 몇 호선을 타야 하나요?" },
    { id: 65, day: 2, en: "Do I need to transfer?", ko: "환승해야 하나요?" },
    { id: 66, day: 2, en: "Where do I transfer to Line 3?", ko: "3호선으로 어디서 환승하나요?" },
    { id: 67, day: 2, en: "How many stops is it from here?", ko: "여기서 몇 정거장인가요?" },
    { id: 68, day: 2, en: "Is this the right platform for downtown?", ko: "시내 방면 승강장이 여기 맞나요?" },
    { id: 69, day: 2, en: "Does this train go to Central Station?", ko: "이 기차가 중앙역에 가나요?" },
    { id: 70, day: 2, en: "What is the next stop?", ko: "다음 정거장이 어디인가요?" },
    { id: 71, day: 2, en: "Excuse me, I need to get off here.", ko: "실례합니다, 여기서 내려야 합니다." },
    { id: 72, day: 2, en: "I think I'm on the wrong train.", ko: "기차를 잘못 탄 것 같아요." },
    { id: 73, day: 2, en: "Could you tell me when we reach the market?", ko: "시장에 도착하면 알려주시겠어요?" },
    { id: 74, day: 2, en: "I'd like to go to this address, please.", ko: "이 주소로 가주세요." },
    { id: 75, day: 2, en: "How long does it take to get there by taxi?", ko: "택시로 거기까지 얼마나 걸리나요?" },
    { id: 76, day: 2, en: "About how much will the fare be?", ko: "요금이 대략 얼마 정도 나올까요?" },
    { id: 77, day: 2, en: "Can you turn on the meter, please?", ko: "미터기를 켜주시겠어요?" },
    { id: 78, day: 2, en: "Could you drop me off at the corner?", ko: "모퉁이에서 내려주시겠어요?" },
    { id: 79, day: 2, en: "Keep the change.", ko: "잔돈은 가지세요." },
    { id: 80, day: 2, en: "Can I get a receipt?", ko: "영수증 주시겠어요?" },
    { id: 81, day: 2, en: "I'd like to rent a car.", ko: "렌터카를 빌리고 싶습니다." },
    { id: 82, day: 2, en: "Do I need an international driver's license?", ko: "국제 운전면허증이 필요한가요?" },
    { id: 83, day: 2, en: "Does the rental include insurance?", ko: "렌트에 보험이 포함되어 있나요?" },
    { id: 84, day: 2, en: "Where should I return the car?", ko: "차를 어디에 반납하면 되나요?" },
    { id: 85, day: 2, en: "Is there a gas station nearby?", ko: "근처에 주유소가 있나요?" },
    { id: 86, day: 2, en: "Excuse me, how do I get to the Eiffel Tower?", ko: "실례합니다, 에펠탑에 어떻게 가나요?" },
    { id: 87, day: 2, en: "Is it within walking distance?", ko: "걸어갈 수 있는 거리인가요?" },
    { id: 88, day: 2, en: "Go straight and turn left at the traffic light.", ko: "직진하시다가 신호등에서 좌회전하세요." },
    { id: 89, day: 2, en: "It's on your right-hand side.", ko: "오른쪽에 있습니다." },
    { id: 90, day: 2, en: "It's about a ten-minute walk from here.", ko: "여기서 걸어서 약 10분 거리입니다." },
    { id: 91, day: 2, en: "Am I going in the right direction?", ko: "제가 맞는 방향으로 가고 있나요?" },
    { id: 92, day: 2, en: "I think I'm lost.", ko: "길을 잃은 것 같아요." },
    { id: 93, day: 2, en: "Can you show me on the map?", ko: "지도에서 보여주시겠어요?" },
    { id: 94, day: 2, en: "Where am I on this map?", ko: "지도에서 제가 어디에 있나요?" },
    { id: 95, day: 2, en: "Is there a landmark nearby?", ko: "근처에 랜드마크가 있나요?" },
    { id: 96, day: 2, en: "How far is it from here?", ko: "여기서 얼마나 먼가요?" },
    { id: 97, day: 2, en: "Can I walk there or should I take a cab?", ko: "걸어갈 수 있나요, 아니면 택시를 타야 하나요?" },
    { id: 98, day: 2, en: "What is the fastest way to get there?", ko: "거기에 가장 빨리 가는 방법은 뭔가요?" },
    { id: 99, day: 2, en: "I need to get to the airport by 3 PM.", ko: "오후 3시까지 공항에 가야 합니다." },
    { id: 100, day: 2, en: "Is there a lot of traffic at this hour?", ko: "이 시간에 차가 많이 막히나요?" },
    { id: 101, day: 2, en: "Can you recommend a ride-hailing app?", ko: "택시 호출 앱을 추천해 주시겠어요?" },
    { id: 102, day: 2, en: "Where is the bike rental station?", ko: "자전거 대여소가 어디인가요?" },
    { id: 103, day: 2, en: "Is parking available near the hotel?", ko: "호텔 근처에 주차가 가능한가요?" },
    { id: 104, day: 2, en: "Where can I find a luggage locker?", ko: "짐 보관함은 어디서 찾을 수 있나요?" },
    { id: 105, day: 2, en: "I'm looking for the hop-on hop-off bus.", ko: "시티투어 버스를 찾고 있어요." },
    { id: 106, day: 2, en: "Does the tour bus stop at the palace?", ko: "투어 버스가 궁전에 정차하나요?" },
    { id: 107, day: 2, en: "When is the last train?", ko: "막차가 몇 시인가요?" },
    { id: 108, day: 2, en: "I left my bag in the taxi.", ko: "택시에 가방을 놓고 내렸어요." },
    { id: 109, day: 2, en: "Where is the lost and found?", ko: "분실물 센터가 어디인가요?" },
    { id: 110, day: 2, en: "Which exit should I take?", ko: "몇 번 출구로 나가야 하나요?" },

    // ===== Day 3: 호텔 & 숙소 (Hotel & Accommodation) — 55문장 =====
    { id: 111, day: 3, en: "I have a reservation under the name Kim.", ko: "김 이름으로 예약이 되어 있습니다." },
    { id: 112, day: 3, en: "I'd like to check in, please.", ko: "체크인하고 싶습니다." },
    { id: 113, day: 3, en: "Here is my booking confirmation.", ko: "여기 예약 확인서입니다." },
    { id: 114, day: 3, en: "What time is check-in?", ko: "체크인 시간이 몇 시인가요?" },
    { id: 115, day: 3, en: "Is early check-in available?", ko: "조기 체크인이 가능한가요?" },
    { id: 116, day: 3, en: "Can I store my luggage until check-in time?", ko: "체크인 시간까지 짐을 맡길 수 있나요?" },
    { id: 117, day: 3, en: "I'd like a non-smoking room.", ko: "금연 객실로 부탁드립니다." },
    { id: 118, day: 3, en: "Do you have a room with a view?", ko: "전망 좋은 방이 있나요?" },
    { id: 119, day: 3, en: "Can I upgrade to a suite?", ko: "스위트룸으로 업그레이드할 수 있나요?" },
    { id: 120, day: 3, en: "How much is it per night?", ko: "1박에 얼마인가요?" },
    { id: 121, day: 3, en: "Is breakfast included?", ko: "조식이 포함되어 있나요?" },
    { id: 122, day: 3, en: "What time is breakfast served?", ko: "조식은 몇 시에 제공되나요?" },
    { id: 123, day: 3, en: "Where is the breakfast buffet?", ko: "조식 뷔페가 어디인가요?" },
    { id: 124, day: 3, en: "What is the Wi-Fi password?", ko: "와이파이 비밀번호가 뭔가요?" },
    { id: 125, day: 3, en: "The Wi-Fi isn't working in my room.", ko: "방에서 와이파이가 안 됩니다." },
    { id: 126, day: 3, en: "Can I have an extra pillow?", ko: "베개를 하나 더 주시겠어요?" },
    { id: 127, day: 3, en: "Could I get some extra towels?", ko: "수건을 더 받을 수 있을까요?" },
    { id: 128, day: 3, en: "The air conditioning is not working.", ko: "에어컨이 작동하지 않습니다." },
    { id: 129, day: 3, en: "The hot water isn't running.", ko: "온수가 안 나옵니다." },
    { id: 130, day: 3, en: "There's a problem with the shower.", ko: "샤워기에 문제가 있어요." },
    { id: 131, day: 3, en: "The room hasn't been cleaned yet.", ko: "아직 객실 청소가 안 되어 있어요." },
    { id: 132, day: 3, en: "Could you send housekeeping?", ko: "객실 청소를 보내주시겠어요?" },
    { id: 133, day: 3, en: "I locked myself out of my room.", ko: "방에 키를 놓고 잠겼습니다." },
    { id: 134, day: 3, en: "Can I get a new key card?", ko: "키카드를 새로 받을 수 있나요?" },
    { id: 135, day: 3, en: "My room is too noisy. Can I change rooms?", ko: "방이 너무 시끄러워요. 방을 바꿀 수 있나요?" },
    { id: 136, day: 3, en: "Is there a safe in the room?", ko: "방에 금고가 있나요?" },
    { id: 137, day: 3, en: "How do I use the room safe?", ko: "금고는 어떻게 사용하나요?" },
    { id: 138, day: 3, en: "Does the hotel have a gym?", ko: "호텔에 헬스장이 있나요?" },
    { id: 139, day: 3, en: "What time does the pool close?", ko: "수영장은 몇 시에 닫나요?" },
    { id: 140, day: 3, en: "Is there a business center?", ko: "비즈니스 센터가 있나요?" },
    { id: 141, day: 3, en: "Can you call a taxi for me?", ko: "택시를 불러주시겠어요?" },
    { id: 142, day: 3, en: "I'd like a wake-up call at 7 AM.", ko: "아침 7시에 모닝콜 부탁드립니다." },
    { id: 143, day: 3, en: "Do you have a laundry service?", ko: "세탁 서비스가 있나요?" },
    { id: 144, day: 3, en: "How long does laundry take?", ko: "세탁 시간이 얼마나 걸리나요?" },
    { id: 145, day: 3, en: "Is there an iron I can borrow?", ko: "빌릴 수 있는 다리미가 있나요?" },
    { id: 146, day: 3, en: "Can I have room service?", ko: "룸서비스를 시킬 수 있나요?" },
    { id: 147, day: 3, en: "I'd like to order dinner to my room.", ko: "방으로 저녁식사를 주문하고 싶습니다." },
    { id: 148, day: 3, en: "Where is the nearest ATM?", ko: "가장 가까운 ATM이 어디인가요?" },
    { id: 149, day: 3, en: "Can you recommend a nearby restaurant?", ko: "근처 맛집을 추천해 주시겠어요?" },
    { id: 150, day: 3, en: "What places do you recommend visiting?", ko: "어디를 방문하는 게 좋을까요?" },
    { id: 151, day: 3, en: "I'd like to extend my stay for one more night.", ko: "하루 더 연장하고 싶습니다." },
    { id: 152, day: 3, en: "What time is check-out?", ko: "체크아웃 시간이 몇 시인가요?" },
    { id: 153, day: 3, en: "Can I have a late check-out?", ko: "늦은 체크아웃이 가능한가요?" },
    { id: 154, day: 3, en: "I'd like to check out now.", ko: "지금 체크아웃하겠습니다." },
    { id: 155, day: 3, en: "Can I leave my bags here after check-out?", ko: "체크아웃 후에 짐을 맡길 수 있나요?" },
    { id: 156, day: 3, en: "Can you print my boarding pass?", ko: "탑승권을 출력해 주실 수 있나요?" },
    { id: 157, day: 3, en: "Is there a shuttle to the airport?", ko: "공항까지 셔틀이 있나요?" },
    { id: 158, day: 3, en: "I think there's an error on my bill.", ko: "청구서에 오류가 있는 것 같습니다." },
    { id: 159, day: 3, en: "I didn't use the minibar.", ko: "미니바를 사용하지 않았습니다." },
    { id: 160, day: 3, en: "Can I pay by credit card?", ko: "신용카드로 결제할 수 있나요?" },
    { id: 161, day: 3, en: "Could you arrange a tour for me?", ko: "투어를 예약해 주시겠어요?" },
    { id: 162, day: 3, en: "Do you have a map of the city?", ko: "도시 지도가 있나요?" },
    { id: 163, day: 3, en: "Where can I buy an adapter plug?", ko: "어댑터 플러그를 어디서 살 수 있나요?" },
    { id: 164, day: 3, en: "What voltage does this country use?", ko: "이 나라의 전압은 몇 볼트인가요?" },
    { id: 165, day: 3, en: "I forgot my charger. Do you have a spare one?", ko: "충전기를 깜빡했는데, 여분이 있으신가요?" },

    // ===== Day 4: 식당 & 음식 주문 (Restaurant & Food) — 55문장 =====
    { id: 166, day: 4, en: "Do you have a table for two?", ko: "2인 테이블이 있나요?" },
    { id: 167, day: 4, en: "I'd like to make a reservation for tonight.", ko: "오늘 저녁 예약하고 싶습니다." },
    { id: 168, day: 4, en: "How long is the wait?", ko: "대기 시간이 얼마나 되나요?" },
    { id: 169, day: 4, en: "Can we sit outside?", ko: "야외에 앉을 수 있나요?" },
    { id: 170, day: 4, en: "Could we have a quiet table, please?", ko: "조용한 자리로 부탁드립니다." },
    { id: 171, day: 4, en: "Can I see the menu, please?", ko: "메뉴 좀 볼 수 있을까요?" },
    { id: 172, day: 4, en: "Do you have an English menu?", ko: "영어 메뉴판이 있나요?" },
    { id: 173, day: 4, en: "What do you recommend?", ko: "추천 메뉴가 뭔가요?" },
    { id: 174, day: 4, en: "What is the most popular dish here?", ko: "여기서 가장 인기 있는 요리는 뭔가요?" },
    { id: 175, day: 4, en: "What's the special today?", ko: "오늘의 특선 메뉴는 뭔가요?" },
    { id: 176, day: 4, en: "I'll have the steak, medium rare.", ko: "스테이크 미디엄 레어로 주세요." },
    { id: 177, day: 4, en: "I'd like the pasta, please.", ko: "파스타로 주세요." },
    { id: 178, day: 4, en: "Can I have the same thing, please?", ko: "같은 걸로 주세요." },
    { id: 179, day: 4, en: "I'm allergic to peanuts.", ko: "저는 땅콩 알레르기가 있습니다." },
    { id: 180, day: 4, en: "Does this contain gluten?", ko: "이 음식에 글루텐이 들어있나요?" },
    { id: 181, day: 4, en: "I'm vegetarian. What can I order?", ko: "저는 채식주의자입니다. 뭘 주문할 수 있나요?" },
    { id: 182, day: 4, en: "Is this dish spicy?", ko: "이 요리가 매운가요?" },
    { id: 183, day: 4, en: "Can you make it less spicy?", ko: "덜 맵게 해주실 수 있나요?" },
    { id: 184, day: 4, en: "No ice in my drink, please.", ko: "음료에 얼음 빼주세요." },
    { id: 185, day: 4, en: "I'd like a glass of red wine.", ko: "레드 와인 한 잔 주세요." },
    { id: 186, day: 4, en: "What kind of beer do you have?", ko: "어떤 종류의 맥주가 있나요?" },
    { id: 187, day: 4, en: "Can I have a refill?", ko: "리필해 주시겠어요?" },
    { id: 188, day: 4, en: "This is not what I ordered.", ko: "이건 제가 주문한 게 아닌데요." },
    { id: 189, day: 4, en: "Excuse me, we've been waiting a long time.", ko: "실례합니다, 저희가 오래 기다리고 있습니다." },
    { id: 190, day: 4, en: "Could we have some more bread?", ko: "빵 좀 더 주시겠어요?" },
    { id: 191, day: 4, en: "Could I have some ketchup, please?", ko: "케첩 좀 주시겠어요?" },
    { id: 192, day: 4, en: "This is delicious!", ko: "정말 맛있어요!" },
    { id: 193, day: 4, en: "Can I take the rest to go?", ko: "남은 것 포장할 수 있나요?" },
    { id: 194, day: 4, en: "Could we have the check, please?", ko: "계산서 좀 주시겠어요?" },
    { id: 195, day: 4, en: "Can we split the bill?", ko: "계산을 나눠서 할 수 있나요?" },
    { id: 196, day: 4, en: "I'll pay for everything.", ko: "제가 다 계산할게요." },
    { id: 197, day: 4, en: "Do you accept credit cards?", ko: "신용카드 되나요?" },
    { id: 198, day: 4, en: "Is the tip included?", ko: "팁이 포함되어 있나요?" },
    { id: 199, day: 4, en: "How much should I tip?", ko: "팁을 얼마나 줘야 하나요?" },
    { id: 200, day: 4, en: "I'd like to order a coffee to go.", ko: "커피 테이크아웃으로 주세요." },
    { id: 201, day: 4, en: "Can I have a large latte with oat milk?", ko: "라지 사이즈 귀리 우유 라떼 주세요." },
    { id: 202, day: 4, en: "For here or to go?", ko: "매장에서 드시나요, 가져가시나요?" },
    { id: 203, day: 4, en: "For here, please.", ko: "매장에서 먹을게요." },
    { id: 204, day: 4, en: "I'd like to try the local food.", ko: "현지 음식을 먹어보고 싶어요." },
    { id: 205, day: 4, en: "Where can I find good street food?", ko: "맛있는 길거리 음식은 어디서 먹을 수 있나요?" },
    { id: 206, day: 4, en: "Is this halal?", ko: "이것은 할랄 음식인가요?" },
    { id: 207, day: 4, en: "Do you have a kids' menu?", ko: "아이 메뉴가 있나요?" },
    { id: 208, day: 4, en: "Can I have a high chair for my child?", ko: "유아용 의자를 주시겠어요?" },
    { id: 209, day: 4, en: "What time do you close?", ko: "몇 시에 닫나요?" },
    { id: 210, day: 4, en: "Is there a supermarket nearby?", ko: "근처에 슈퍼마켓이 있나요?" },
    { id: 211, day: 4, en: "Where can I buy bottled water?", ko: "생수를 어디서 살 수 있나요?" },
    { id: 212, day: 4, en: "Do you have any vegan options?", ko: "비건 메뉴가 있나요?" },
    { id: 213, day: 4, en: "Can I have the dessert menu?", ko: "디저트 메뉴판 주시겠어요?" },
    { id: 214, day: 4, en: "I'll have the chocolate cake, please.", ko: "초콜릿 케이크로 주세요." },
    { id: 215, day: 4, en: "That was a wonderful meal. Thank you!", ko: "정말 훌륭한 식사였습니다. 감사합니다!" },
    { id: 216, day: 4, en: "Could you wrap this up for me?", ko: "이것 좀 싸주시겠어요?" },
    { id: 217, day: 4, en: "Do you deliver to hotels?", ko: "호텔로 배달되나요?" },
    { id: 218, day: 4, en: "I'd like to order room service.", ko: "룸서비스를 주문하고 싶습니다." },
    { id: 219, day: 4, en: "Is tap water safe to drink here?", ko: "여기 수돗물을 마셔도 되나요?" },
    { id: 220, day: 4, en: "Could I have still water instead of sparkling?", ko: "탄산수 대신 일반 물로 주시겠어요?" },

    // ===== Day 5: 쇼핑 & 긴급상황 (Shopping & Emergencies) — 55문장 =====
    { id: 221, day: 5, en: "I'm just looking, thank you.", ko: "그냥 구경하는 거예요, 감사합니다." },
    { id: 222, day: 5, en: "How much is this?", ko: "이거 얼마예요?" },
    { id: 223, day: 5, en: "Can I try this on?", ko: "이거 입어봐도 되나요?" },
    { id: 224, day: 5, en: "Where is the fitting room?", ko: "탈의실이 어디인가요?" },
    { id: 225, day: 5, en: "Do you have this in a smaller size?", ko: "이거 더 작은 사이즈 있나요?" },
    { id: 226, day: 5, en: "Do you have this in a different color?", ko: "이거 다른 색상 있나요?" },
    { id: 227, day: 5, en: "It doesn't fit. It's too tight.", ko: "안 맞아요. 너무 꽉 끼네요." },
    { id: 228, day: 5, en: "I'll take it.", ko: "이걸로 할게요." },
    { id: 229, day: 5, en: "Can I get a discount?", ko: "할인 받을 수 있나요?" },
    { id: 230, day: 5, en: "Is this on sale?", ko: "이건 세일 중인가요?" },
    { id: 231, day: 5, en: "Can I pay in cash?", ko: "현금으로 결제 가능한가요?" },
    { id: 232, day: 5, en: "Do you accept Apple Pay?", ko: "애플페이 되나요?" },
    { id: 233, day: 5, en: "Can I get a tax refund?", ko: "세금 환급을 받을 수 있나요?" },
    { id: 234, day: 5, en: "Could you wrap this as a gift?", ko: "선물용으로 포장해 주시겠어요?" },
    { id: 235, day: 5, en: "Do you have a bag I can use?", ko: "가방이 있나요?" },
    { id: 236, day: 5, en: "I'd like to return this.", ko: "이것을 반품하고 싶습니다." },
    { id: 237, day: 5, en: "Can I exchange this for a different size?", ko: "다른 사이즈로 교환할 수 있나요?" },
    { id: 238, day: 5, en: "Do you have a refund policy?", ko: "환불 정책이 있나요?" },
    { id: 239, day: 5, en: "I'd like to buy a souvenir.", ko: "기념품을 사고 싶어요." },
    { id: 240, day: 5, en: "What is a popular local product?", ko: "인기 있는 현지 상품은 뭔가요?" },
    { id: 241, day: 5, en: "I need to find a pharmacy.", ko: "약국을 찾아야 합니다." },
    { id: 242, day: 5, en: "Do you have medicine for a headache?", ko: "두통약 있나요?" },
    { id: 243, day: 5, en: "I have a stomachache.", ko: "배가 아픕니다." },
    { id: 244, day: 5, en: "I feel dizzy.", ko: "어지럽습니다." },
    { id: 245, day: 5, en: "I need to see a doctor.", ko: "병원에 가봐야 할 것 같아요." },
    { id: 246, day: 5, en: "Where is the nearest hospital?", ko: "가장 가까운 병원이 어디인가요?" },
    { id: 247, day: 5, en: "I need to call an ambulance.", ko: "구급차를 불러야 합니다." },
    { id: 248, day: 5, en: "Please help me!", ko: "도와주세요!" },
    { id: 249, day: 5, en: "I lost my passport.", ko: "여권을 잃어버렸습니다." },
    { id: 250, day: 5, en: "My wallet was stolen.", ko: "지갑을 도난당했습니다." },
    { id: 251, day: 5, en: "I need to go to the police station.", ko: "경찰서에 가야 합니다." },
    { id: 252, day: 5, en: "Can you help me file a report?", ko: "신고서 작성하는 것 좀 도와주시겠어요?" },
    { id: 253, day: 5, en: "I need to contact my embassy.", ko: "대사관에 연락해야 합니다." },
    { id: 254, day: 5, en: "Where is the Korean Embassy?", ko: "한국 대사관이 어디에 있나요?" },
    { id: 255, day: 5, en: "Can you call the police?", ko: "경찰을 불러주시겠어요?" },
    { id: 256, day: 5, en: "Does anyone here speak Korean?", ko: "여기 한국어 할 수 있는 분 계신가요?" },
    { id: 257, day: 5, en: "I have travel insurance.", ko: "여행자 보험이 있습니다." },
    { id: 258, day: 5, en: "I need to cancel my credit card.", ko: "신용카드를 정지시켜야 합니다." },
    { id: 259, day: 5, en: "Where can I get a temporary passport?", ko: "임시 여권을 어디서 발급받을 수 있나요?" },
    { id: 260, day: 5, en: "I slipped and hurt my ankle.", ko: "미끄러져서 발목을 다쳤어요." },
    { id: 261, day: 5, en: "I got sunburned.", ko: "햇볕에 탔어요." },
    { id: 262, day: 5, en: "Do you have sunscreen?", ko: "선크림 있나요?" },
    { id: 263, day: 5, en: "I need a Band-Aid.", ko: "반창고가 필요합니다." },
    { id: 264, day: 5, en: "Is there a convenience store around here?", ko: "이 근처에 편의점이 있나요?" },
    { id: 265, day: 5, en: "What's the emergency number in this country?", ko: "이 나라의 긴급전화번호가 뭔가요?" },
    { id: 266, day: 5, en: "There's been an accident.", ko: "사고가 났습니다." },
    { id: 267, day: 5, en: "I left something in the restaurant.", ko: "식당에 물건을 놓고 왔어요." },
    { id: 268, day: 5, en: "Can you write down the address for me?", ko: "주소를 적어주시겠어요?" },
    { id: 269, day: 5, en: "How do I make an international call?", ko: "국제전화는 어떻게 걸나요?" },
    { id: 270, day: 5, en: "What's the best way to stay connected here?", ko: "여기서 인터넷 연결을 유지하는 가장 좋은 방법은 뭔가요?" },
    { id: 271, day: 5, en: "Thank you so much for your help.", ko: "도와주셔서 정말 감사합니다." },
    { id: 272, day: 5, en: "It was a pleasure meeting you.", ko: "만나서 반가웠습니다." },
    { id: 273, day: 5, en: "I had a great time here.", ko: "여기서 정말 좋은 시간을 보냈어요." },
    { id: 274, day: 5, en: "I hope to come back someday.", ko: "언젠가 다시 오고 싶어요." },
    { id: 275, day: 5, en: "Have a nice day!", ko: "좋은 하루 보내세요!" }
];
