// Day 13: 양산 & 품질 관리 (Production & Quality) - 791~860
SENTENCES.push(
    { id: 791, day: 13, en: "The mass production line is ready for ramp-up.", ko: "양산 라인이 증대 준비 완료되었습니다." },
    { id: 792, day: 13, en: "The cycle time for assembly is 45 seconds.", ko: "조립 사이클 타임은 45초입니다." },
    { id: 793, day: 13, en: "The OEE target is 85% for this line.", ko: "이 라인의 OEE 목표는 85%입니다." },
    { id: 794, day: 13, en: "The yield rate improved to 99.2% last month.", ko: "지난 달 수율이 99.2%로 개선되었습니다." },
    { id: 795, day: 13, en: "The defect rate is tracked daily on the shop floor.", ko: "불량률은 현장에서 매일 추적됩니다." },
    { id: 796, day: 13, en: "The top defect mode is connector insertion failure.", ko: "주요 불량 모드는 커넥터 삽입 불량입니다." },
    { id: 797, day: 13, en: "The containment action has been implemented.", ko: "유출 방지 조치가 시행되었습니다." },
    { id: 798, day: 13, en: "The sorted stock needs 100% inspection.", ko: "분류된 재고는 전수 검사가 필요합니다." },
    { id: 799, day: 13, en: "The incoming inspection detected out-of-spec parts.", ko: "수입 검사에서 사양 이탈 부품이 감지되었습니다." },
    { id: 800, day: 13, en: "The supplier will implement a countermeasure.", ko: "공급업체가 대책을 시행할 것입니다." },
    { id: 801, day: 13, en: "The production volume for this month is 10,000 units.", ko: "이번 달 생산 물량은 10,000개입니다." },
    { id: 802, day: 13, en: "The changeover time between models is 30 minutes.", ko: "모델 간 전환 시간은 30분입니다." },
    { id: 803, day: 13, en: "The automated optical inspection catches solder defects.", ko: "자동 광학 검사가 솔더 결함을 검출합니다." },
    { id: 804, day: 13, en: "The torque verification station checks every assembly.", ko: "토크 검증 스테이션이 모든 조립을 확인합니다." },
    { id: 805, day: 13, en: "The leak test must pass before final assembly.", ko: "최종 조립 전에 누설 테스트를 통과해야 합니다." },
    { id: 806, day: 13, en: "The shipping label must include the batch number.", ko: "배송 라벨에 배치 번호를 포함해야 합니다." },
    { id: 807, day: 13, en: "The customer raised a quality concern on the last shipment.", ko: "고객이 마지막 출하에 대해 품질 우려를 제기했습니다." },
    { id: 808, day: 13, en: "The complaint investigation is in progress.", ko: "클레임 조사가 진행 중입니다." },
    { id: 809, day: 13, en: "We found the root cause using the fishbone diagram.", ko: "특성 요인도를 사용하여 근본 원인을 찾았습니다." },
    { id: 810, day: 13, en: "The 5-Why analysis points to a material issue.", ko: "5-Why 분석이 재료 문제를 지목합니다." },
    { id: 811, day: 13, en: "The PDCA cycle must be followed for improvement.", ko: "개선을 위해 PDCA 사이클을 따라야 합니다." },
    { id: 812, day: 13, en: "The continuous improvement activity saved significant cost.", ko: "지속적 개선 활동으로 상당한 비용을 절약했습니다." },
    { id: 813, day: 13, en: "The Kaizen event is scheduled for next week.", ko: "카이젠 이벤트가 다음 주로 예정되어 있습니다." },
    { id: 814, day: 13, en: "The Six Sigma project reduced variation by 40%.", ko: "식스 시그마 프로젝트가 변동을 40% 줄였습니다." },
    { id: 815, day: 13, en: "The process FMEA severity rating is 8.", ko: "공정 FMEA 심각도 등급은 8입니다." },
    { id: 816, day: 13, en: "The prevention method must be updated.", ko: "예방 방법을 업데이트해야 합니다." },
    { id: 817, day: 13, en: "The detection method uses 100% electrical testing.", ko: "검출 방법은 전수 전기 테스트를 사용합니다." },
    { id: 818, day: 13, en: "The RPN value decreased from 180 to 60.", ko: "RPN 값이 180에서 60으로 감소했습니다." },
    { id: 819, day: 13, en: "The safe launch plan includes additional inspections.", ko: "안전 출하 계획에 추가 검사가 포함됩니다." },
    { id: 820, day: 13, en: "The customer PPAP submission is due next month.", ko: "고객 PPAP 제출이 다음 달 마감입니다." },
    { id: 821, day: 13, en: "The PSW needs customer signature for approval.", ko: "PSW에 고객 서명이 승인을 위해 필요합니다." },
    { id: 822, day: 13, en: "The process flow diagram has been updated.", ko: "공정 흐름도가 업데이트되었습니다." },
    { id: 823, day: 13, en: "The reaction plan defines actions for out-of-control conditions.", ko: "대응 계획이 관리 이탈 조건에 대한 조치를 정의합니다." },
    { id: 824, day: 13, en: "The operator must follow the standard work procedure.", ko: "작업자는 표준 작업 절차를 따라야 합니다." },
    { id: 825, day: 13, en: "The mistake-proofing device needs maintenance.", ko: "실수 방지 장치의 유지보수가 필요합니다." },
    { id: 826, day: 13, en: "The traceability matrix links each unit to its components.", ko: "추적 매트릭스가 각 유닛을 부품과 연결합니다." },
    { id: 827, day: 13, en: "The serial number is laser-engraved on the housing.", ko: "시리얼 번호가 하우징에 레이저 각인됩니다." },
    { id: 828, day: 13, en: "The packaging specification follows the customer standard.", ko: "포장 사양이 고객 표준을 따릅니다." },
    { id: 829, day: 13, en: "The returnable container system reduces waste.", ko: "회수 용기 시스템이 폐기물을 줄입니다." },
    { id: 830, day: 13, en: "The ESD protection must be maintained during assembly.", ko: "조립 중 정전기 보호를 유지해야 합니다." },
    { id: 831, day: 13, en: "The clean room assembly area meets ISO class 8.", ko: "청정실 조립 영역이 ISO 클래스 8을 충족합니다." },
    { id: 832, day: 13, en: "The torque wrench is calibrated monthly.", ko: "토크 렌치는 매월 교정됩니다." },
    { id: 833, day: 13, en: "The production line audit found two minor findings.", ko: "생산 라인 감사에서 2건의 경미한 발견사항이 있었습니다." },
    { id: 834, day: 13, en: "The layered process audit is conducted weekly.", ko: "계층별 공정 감사가 매주 시행됩니다." },
    { id: 835, day: 13, en: "The safety stock level is set to one week of production.", ko: "안전 재고 수준이 1주일 생산량으로 설정되어 있습니다." },
    { id: 836, day: 13, en: "The JIT delivery system minimizes inventory.", ko: "JIT 납품 시스템이 재고를 최소화합니다." },
    { id: 837, day: 13, en: "The Kanban system triggers material replenishment.", ko: "칸반 시스템이 자재 보충을 유발합니다." },
    { id: 838, day: 13, en: "The material handling procedure prevents damage.", ko: "자재 취급 절차가 손상을 방지합니다." },
    { id: 839, day: 13, en: "The line stop authority is given to each operator.", ko: "라인 정지 권한이 각 작업자에게 주어집니다." },
    { id: 840, day: 13, en: "The escalation procedure is displayed at each station.", ko: "에스컬레이션 절차가 각 스테이션에 게시되어 있습니다." },
    { id: 841, day: 13, en: "The daily production meeting is held at 8 AM.", ko: "일일 생산 회의는 오전 8시에 진행됩니다." },
    { id: 842, day: 13, en: "The shift handover report must be completed.", ko: "교대 인수인계 보고서를 작성해야 합니다." },
    { id: 843, day: 13, en: "The preventive maintenance schedule is posted.", ko: "예방 보전 일정이 게시되어 있습니다." },
    { id: 844, day: 13, en: "The machine downtime target is less than 2%.", ko: "설비 가동 중지 목표는 2% 미만입니다." },
    { id: 845, day: 13, en: "The energy consumption has been reduced by 15%.", ko: "에너지 소비가 15% 감소했습니다." },
    { id: 846, day: 13, en: "The waste segregation follows environmental regulations.", ko: "폐기물 분리가 환경 규정을 따릅니다." },
    { id: 847, day: 13, en: "The ISO 14001 audit is coming up in April.", ko: "ISO 14001 감사가 4월에 예정되어 있습니다." },
    { id: 848, day: 13, en: "The safety incident was reported immediately.", ko: "안전 사고가 즉시 보고되었습니다." },
    { id: 849, day: 13, en: "The near-miss event has been documented.", ko: "아차 사고가 문서화되었습니다." },
    { id: 850, day: 13, en: "The PPE requirements are posted at the entrance.", ko: "개인 보호장비 요구사항이 입구에 게시되어 있습니다." },
    { id: 851, day: 13, en: "The 5S audit score improved to 95%.", ko: "5S 감사 점수가 95%로 향상되었습니다." },
    { id: 852, day: 13, en: "The visual management board is updated daily.", ko: "가시적 관리 보드가 매일 업데이트됩니다." },
    { id: 853, day: 13, en: "The standard work combination sheet is posted.", ko: "표준 작업 조합표가 게시되어 있습니다." },
    { id: 854, day: 13, en: "The capacity analysis shows we need a second shift.", ko: "능력 분석에서 2교대가 필요함을 보여줍니다." },
    { id: 855, day: 13, en: "The new equipment installation is planned for May.", ko: "신규 장비 설치가 5월로 계획되어 있습니다." },
    { id: 856, day: 13, en: "The automation level of this process is 80%.", ko: "이 공정의 자동화율은 80%입니다." },
    { id: 857, day: 13, en: "The robot programming needs modification for the new model.", ko: "새 모델을 위해 로봇 프로그래밍 수정이 필요합니다." },
    { id: 858, day: 13, en: "The fixture design is being reviewed.", ko: "치구 설계가 검토 중입니다." },
    { id: 859, day: 13, en: "The gauge R&R study must be completed before production.", ko: "양산 전 게이지 R&R 연구를 완료해야 합니다." },
    { id: 860, day: 13, en: "Quality is everyone's responsibility.", ko: "품질은 모든 사람의 책임입니다." }
);

// Day 14: 비즈니스 & 일반 회의 (Business & General) - 861~930
SENTENCES.push(
    { id: 861, day: 14, en: "Could we reschedule the meeting to next Tuesday?", ko: "회의를 다음 주 화요일로 변경할 수 있을까요?" },
    { id: 862, day: 14, en: "I have a conflict with another meeting at that time.", ko: "그 시간에 다른 회의와 겹칩니다." },
    { id: 863, day: 14, en: "What time works best for the European colleagues?", ko: "유럽 쪽 동료들에게 가장 좋은 시간은 언제인가요?" },
    { id: 864, day: 14, en: "Considering the time difference, 3 PM KST works.", ko: "시차를 고려하면 한국 시간 오후 3시가 좋겠습니다." },
    { id: 865, day: 14, en: "I will be on vacation from the 10th to the 14th.", ko: "10일부터 14일까지 휴가입니다." },
    { id: 866, day: 14, en: "My colleague will cover for me during my absence.", ko: "부재 중에 동료가 대신해 줄 것입니다." },
    { id: 867, day: 14, en: "Please direct all inquiries to Mr. Park.", ko: "모든 문의는 박 대리에게 해주세요." },
    { id: 868, day: 14, en: "I just got back from a business trip to Germany.", ko: "독일 출장에서 막 돌아왔습니다." },
    { id: 869, day: 14, en: "The meeting will be held in a hybrid format.", ko: "회의는 하이브리드 형식으로 진행됩니다." },
    { id: 870, day: 14, en: "Can we extend the meeting by 15 minutes?", ko: "회의를 15분 연장할 수 있나요?" },
    { id: 871, day: 14, en: "Let me take a quick break before we continue.", ko: "계속하기 전에 잠깐 쉬겠습니다." },
    { id: 872, day: 14, en: "Let's take a 5-minute break.", ko: "5분간 휴식합시다." },
    { id: 873, day: 14, en: "I need to step out for a moment.", ko: "잠시 자리를 비워야 합니다." },
    { id: 874, day: 14, en: "Sorry, I had another call running in parallel.", ko: "죄송합니다, 다른 콜이 동시에 있었습니다." },
    { id: 875, day: 14, en: "Can we set up a separate session for this topic?", ko: "이 주제에 대해 별도 세션을 잡을 수 있나요?" },
    { id: 876, day: 14, en: "I will set up a workshop to address this issue.", ko: "이 이슈를 다루기 위해 워크숍을 마련하겠습니다." },
    { id: 877, day: 14, en: "The annual team building event is in September.", ko: "연례 팀빌딩 행사가 9월입니다." },
    { id: 878, day: 14, en: "Congratulations on the successful project launch.", ko: "프로젝트 성공적인 출시를 축하합니다." },
    { id: 879, day: 14, en: "The new organization structure takes effect in April.", ko: "신규 조직 구조가 4월부터 적용됩니다." },
    { id: 880, day: 14, en: "The reporting line has been changed.", ko: "보고 체계가 변경되었습니다." },
    { id: 881, day: 14, en: "We have a new director for the engineering division.", ko: "엔지니어링 본부에 새 상무가 오셨습니다." },
    { id: 882, day: 14, en: "The R&D budget for next year is under review.", ko: "내년 R&D 예산이 검토 중입니다." },
    { id: 883, day: 14, en: "The capital expenditure request has been approved.", ko: "자본 지출 요청이 승인되었습니다." },
    { id: 884, day: 14, en: "We are hiring two new engineers for the EPS team.", ko: "EPS 팀에 신규 엔지니어 2명을 채용합니다." },
    { id: 885, day: 14, en: "The market share for EPS is growing steadily.", ko: "EPS 시장 점유율이 꾸준히 성장하고 있습니다." },
    { id: 886, day: 14, en: "The industry trend is moving towards steer-by-wire.", ko: "산업 트렌드가 스티어 바이 와이어로 이동하고 있습니다." },
    { id: 887, day: 14, en: "The autonomous driving feature requires advanced EPS.", ko: "자율주행 기능에 고급 EPS가 필요합니다." },
    { id: 888, day: 14, en: "The electric vehicle platform has different requirements.", ko: "전기차 플랫폼은 다른 요구사항이 있습니다." },
    { id: 889, day: 14, en: "We need to develop a next-generation controller.", ko: "차세대 제어기를 개발해야 합니다." },
    { id: 890, day: 14, en: "The benchmark study against competitors is complete.", ko: "경쟁사 대비 벤치마크 연구가 완료되었습니다." },
    { id: 891, day: 14, en: "Our technology level is competitive in the market.", ko: "우리 기술 수준은 시장에서 경쟁력이 있습니다." },
    { id: 892, day: 14, en: "The strategic partnership will strengthen both companies.", ko: "전략적 파트너십이 양사를 강화할 것입니다." },
    { id: 893, day: 14, en: "The joint venture proposal is being evaluated.", ko: "합작 투자 제안을 평가하고 있습니다." },
    { id: 894, day: 14, en: "The exhibition booth design is finalized.", ko: "전시 부스 디자인이 확정되었습니다." },
    { id: 895, day: 14, en: "We will showcase our latest EPS at the motor show.", ko: "모터쇼에서 최신 EPS를 선보일 것입니다." },
    { id: 896, day: 14, en: "The technical paper has been accepted for the conference.", ko: "학회 논문이 컨퍼런스에 채택되었습니다." },
    { id: 897, day: 14, en: "The training session is available online.", ko: "교육 세션은 온라인으로 참여 가능합니다." },
    { id: 898, day: 14, en: "I completed the ISO 26262 certification course.", ko: "ISO 26262 인증 과정을 수료했습니다." },
    { id: 899, day: 14, en: "The knowledge transfer session is scheduled for Friday.", ko: "지식 이전 세션이 금요일로 예정되어 있습니다." },
    { id: 900, day: 14, en: "Let me share my screen to walk through the process.", ko: "프로세스를 설명하기 위해 화면 공유하겠습니다." },
    { id: 901, day: 14, en: "Are there any other topics we should cover today?", ko: "오늘 다뤄야 할 다른 주제가 있나요?" },
    { id: 902, day: 14, en: "I think we covered everything on the agenda.", ko: "안건의 모든 내용을 다룬 것 같습니다." },
    { id: 903, day: 14, en: "Let me double-check the numbers and get back to you.", ko: "숫자를 재확인하고 다시 연락드리겠습니다." },
    { id: 904, day: 14, en: "That is a fair point.", ko: "그건 공정한 지적입니다." },
    { id: 905, day: 14, en: "I completely understand your position.", ko: "당신의 입장을 완전히 이해합니다." },
    { id: 906, day: 14, en: "Let me think about that and come back with a plan.", ko: "그것에 대해 생각해 보고 계획을 가지고 오겠습니다." },
    { id: 907, day: 14, en: "We should involve the quality team in this discussion.", ko: "이 논의에 품질팀을 참여시켜야 합니다." },
    { id: 908, day: 14, en: "The cross-functional team will address this issue.", ko: "기능 횡단 팀이 이 이슈를 다룰 것입니다." },
    { id: 909, day: 14, en: "Each department should assign a representative.", ko: "각 부서에서 대표를 지정해야 합니다." },
    { id: 910, day: 14, en: "The management decision is expected by end of week.", ko: "경영진 결정이 주말까지 예상됩니다." },
    { id: 911, day: 14, en: "We will communicate the decision via email.", ko: "이메일로 결정 사항을 전달하겠습니다." },
    { id: 912, day: 14, en: "The alignment between Korea and Germany teams is critical.", ko: "한국팀과 독일팀 간의 정렬이 중요합니다." },
    { id: 913, day: 14, en: "Let me coordinate with the headquarters.", ko: "본사와 조율하겠습니다." },
    { id: 914, day: 14, en: "The global team call is scheduled monthly.", ko: "글로벌 팀 콜이 월간으로 예정되어 있습니다." },
    { id: 915, day: 14, en: "The technology exchange program starts next quarter.", ko: "기술 교류 프로그램이 다음 분기에 시작됩니다." },
    { id: 916, day: 14, en: "Our plant in China handles the local production.", ko: "중국 공장이 현지 생산을 담당합니다." },
    { id: 917, day: 14, en: "The logistics cost needs to be factored in.", ko: "물류 비용을 반영해야 합니다." },
    { id: 918, day: 14, en: "The customs clearance process takes about one week.", ko: "통관 절차에 약 1주일이 걸립니다." },
    { id: 919, day: 14, en: "The exchange rate fluctuation affects our profitability.", ko: "환율 변동이 수익성에 영향을 줍니다." },
    { id: 920, day: 14, en: "We need to review the revenue forecast.", ko: "매출 예측을 검토해야 합니다." },
    { id: 921, day: 14, en: "The profit margin is tight on this project.", ko: "이 프로젝트는 이익률이 타이트합니다." },
    { id: 922, day: 14, en: "The annual business plan will be presented next week.", ko: "연간 사업 계획이 다음 주에 발표됩니다." },
    { id: 923, day: 14, en: "The sustainability report highlights our ESG efforts.", ko: "지속가능성 보고서가 우리의 ESG 노력을 강조합니다." },
    { id: 924, day: 14, en: "The carbon footprint reduction is a company priority.", ko: "탄소 발자국 감소가 회사 우선과제입니다." },
    { id: 925, day: 14, en: "The supplier diversity program is being implemented.", ko: "공급업체 다양성 프로그램이 시행되고 있습니다." },
    { id: 926, day: 14, en: "The employee satisfaction survey results are in.", ko: "직원 만족도 조사 결과가 나왔습니다." },
    { id: 927, day: 14, en: "The innovation award ceremony is in December.", ko: "혁신 시상식이 12월에 있습니다." },
    { id: 928, day: 14, en: "Our team received recognition for the NVH improvement.", ko: "저희 팀이 NVH 개선으로 인정을 받았습니다." },
    { id: 929, day: 14, en: "The mentor program pairs junior with senior engineers.", ko: "멘토 프로그램이 주니어와 시니어 엔지니어를 매칭합니다." },
    { id: 930, day: 14, en: "Thank you for the great teamwork on this project.", ko: "이 프로젝트에서의 훌륭한 팀워크 감사합니다." }
);

// Day 15: 심화 기술 & 최신 트렌드 (Advanced Tech & Trends) - 931~1000
SENTENCES.push(
    { id: 931, day: 15, en: "The dual pinion EPS provides higher output force.", ko: "듀얼 피니언 EPS가 더 높은 출력 힘을 제공합니다." },
    { id: 932, day: 15, en: "The rack-assist type EPS is used in heavy vehicles.", ko: "랙 어시스트 타입 EPS가 대형 차량에 사용됩니다." },
    { id: 933, day: 15, en: "The belt-driven EPS reduces gear noise.", ko: "벨트 구동 EPS가 기어 소음을 줄입니다." },
    { id: 934, day: 15, en: "The steer-by-wire eliminates the mechanical connection.", ko: "스티어 바이 와이어가 기계적 연결을 제거합니다." },
    { id: 935, day: 15, en: "The haptic feedback system simulates road feel.", ko: "햅틱 피드백 시스템이 노면 감각을 시뮬레이션합니다." },
    { id: 936, day: 15, en: "The AI-based control adapts to driver behavior.", ko: "AI 기반 제어가 운전자 행동에 적응합니다." },
    { id: 937, day: 15, en: "Machine learning improves the steering feel calibration.", ko: "머신러닝이 조향 필링 캘리브레이션을 개선합니다." },
    { id: 938, day: 15, en: "The digital twin model predicts component lifetime.", ko: "디지털 트윈 모델이 부품 수명을 예측합니다." },
    { id: 939, day: 15, en: "The predictive maintenance algorithm detects early failure.", ko: "예측 유지보수 알고리즘이 초기 고장을 감지합니다." },
    { id: 940, day: 15, en: "The SiC MOSFET improves inverter efficiency.", ko: "SiC MOSFET이 인버터 효율을 개선합니다." },
    { id: 941, day: 15, en: "The GaN transistor enables higher switching frequency.", ko: "GaN 트랜지스터가 더 높은 스위칭 주파수를 가능하게 합니다." },
    { id: 942, day: 15, en: "The integrated motor-inverter design saves space.", ko: "모터-인버터 통합 설계가 공간을 절약합니다." },
    { id: 943, day: 15, en: "The 48V system enables more powerful EPS.", ko: "48V 시스템이 더 강력한 EPS를 가능하게 합니다." },
    { id: 944, day: 15, en: "The redundant power supply meets ASIL D requirements.", ko: "이중화 전원 공급이 ASIL D 요구사항을 충족합니다." },
    { id: 945, day: 15, en: "The zonal architecture changes the EPS network topology.", ko: "존 아키텍처가 EPS 네트워크 토폴로지를 변경합니다." },
    { id: 946, day: 15, en: "The Ethernet communication replaces CAN in new platforms.", ko: "새 플랫폼에서 이더넷 통신이 CAN을 대체합니다." },
    { id: 947, day: 15, en: "The OTA update capability is mandatory for new vehicles.", ko: "새 차량에 OTA 업데이트 기능이 필수입니다." },
    { id: 948, day: 15, en: "The smart sensor integrates processing on chip.", ko: "스마트 센서가 칩 위에 처리를 통합합니다." },
    { id: 949, day: 15, en: "The additive manufacturing enables complex geometries.", ko: "적층 제조가 복잡한 형상을 가능하게 합니다." },
    { id: 950, day: 15, en: "The 3D printed prototype was delivered in 3 days.", ko: "3D 프린팅 프로토타입이 3일 만에 납품되었습니다." },
    { id: 951, day: 15, en: "The composite material reduces mass by 30%.", ko: "복합 소재가 질량을 30% 줄입니다." },
    { id: 952, day: 15, en: "The carbon fiber reinforced plastic housing is being evaluated.", ko: "탄소섬유 강화 플라스틱 하우징을 평가하고 있습니다." },
    { id: 953, day: 15, en: "The rare earth free motor design is under development.", ko: "희토류 프리 모터 설계가 개발 중입니다." },
    { id: 954, day: 15, en: "The ferrite magnet motor is a cost-effective alternative.", ko: "페라이트 자석 모터가 비용 효율적 대안입니다." },
    { id: 955, day: 15, en: "The switched reluctance motor is gaining attention.", ko: "스위치드 릴럭턴스 모터가 관심을 받고 있습니다." },
    { id: 956, day: 15, en: "The axial flux motor has a compact form factor.", ko: "축방향 자속 모터가 컴팩트한 폼 팩터를 가집니다." },
    { id: 957, day: 15, en: "The hairpin winding improves slot fill factor.", ko: "헤어핀 권선이 슬롯 충전율을 개선합니다." },
    { id: 958, day: 15, en: "The concentrated winding simplifies manufacturing.", ko: "집중 권선이 제조를 단순화합니다." },
    { id: 959, day: 15, en: "The segmented stator design reduces copper waste.", ko: "분할 고정자 설계가 동 폐기물을 줄입니다." },
    { id: 960, day: 15, en: "The thermal management system uses phase change material.", ko: "열 관리 시스템이 상변환 물질을 사용합니다." },
    { id: 961, day: 15, en: "The heat pipe technology improves cooling performance.", ko: "히트 파이프 기술이 냉각 성능을 개선합니다." },
    { id: 962, day: 15, en: "The noise cancellation algorithm is being developed.", ko: "소음 상쇄 알고리즘이 개발 중입니다." },
    { id: 963, day: 15, en: "The active noise control uses the speaker in the cabin.", ko: "능동 소음 제어가 실내 스피커를 사용합니다." },
    { id: 964, day: 15, en: "The vibration energy harvesting powers the sensor.", ko: "진동 에너지 수확이 센서에 전력을 공급합니다." },
    { id: 965, day: 15, en: "The condition monitoring system tracks motor health.", ko: "상태 모니터링 시스템이 모터 건강을 추적합니다." },
    { id: 966, day: 15, en: "The cloud-based analytics provides fleet-level insights.", ko: "클라우드 기반 분석이 플릿 수준의 인사이트를 제공합니다." },
    { id: 967, day: 15, en: "The connected vehicle data improves product development.", ko: "커넥티드 차량 데이터가 제품 개발을 개선합니다." },
    { id: 968, day: 15, en: "The simulation accuracy has improved with AI.", ko: "AI로 시뮬레이션 정확도가 향상되었습니다." },
    { id: 969, day: 15, en: "The generative design tool proposed an optimized shape.", ko: "제너레이티브 디자인 툴이 최적화된 형상을 제안했습니다." },
    { id: 970, day: 15, en: "The digital thread connects design to manufacturing.", ko: "디지털 스레드가 설계와 제조를 연결합니다." },
    { id: 971, day: 15, en: "The model-based systems engineering approach is adopted.", ko: "모델 기반 시스템 공학 접근법이 채택되었습니다." },
    { id: 972, day: 15, en: "The SysML diagram defines the system architecture.", ko: "SysML 다이어그램이 시스템 아키텍처를 정의합니다." },
    { id: 973, day: 15, en: "The agile development methodology speeds up iteration.", ko: "애자일 개발 방법론이 반복을 가속화합니다." },
    { id: 974, day: 15, en: "The sprint review showed good progress.", ko: "스프린트 리뷰에서 좋은 진행 상황을 보여주었습니다." },
    { id: 975, day: 15, en: "The backlog needs to be prioritized for the next sprint.", ko: "다음 스프린트를 위해 백로그 우선순위를 정해야 합니다." },
    { id: 976, day: 15, en: "The SOTIF analysis covers unintended behaviors.", ko: "SOTIF 분석이 의도하지 않은 동작을 다룹니다." },
    { id: 977, day: 15, en: "The validation scenario includes extreme weather conditions.", ko: "검증 시나리오에 극한 기상 조건이 포함됩니다." },
    { id: 978, day: 15, en: "The homologation process varies by country.", ko: "형식 승인 프로세스가 나라마다 다릅니다." },
    { id: 979, day: 15, en: "The UN R79 regulation requires specific steering tests.", ko: "UN R79 규정이 특정 조향 테스트를 요구합니다." },
    { id: 980, day: 15, en: "The FMVSS 111 standard applies to the US market.", ko: "FMVSS 111 표준이 미국 시장에 적용됩니다." },
    { id: 981, day: 15, en: "The Euro NCAP rating influences the EPS requirement.", ko: "유로 NCAP 등급이 EPS 요구사항에 영향을 줍니다." },
    { id: 982, day: 15, en: "The lane keeping assist relies on the EPS system.", ko: "차선 유지 보조가 EPS 시스템에 의존합니다." },
    { id: 983, day: 15, en: "The automatic parking function requires high torque.", ko: "자동 주차 기능에 높은 토크가 필요합니다." },
    { id: 984, day: 15, en: "The hands-off detection is integrated in the torque sensor.", ko: "핸즈오프 감지가 토크 센서에 통합되어 있습니다." },
    { id: 985, day: 15, en: "The driver monitoring system works with the EPS.", ko: "운전자 모니터링 시스템이 EPS와 연동됩니다." },
    { id: 986, day: 15, en: "The over-the-air calibration update is a new feature.", ko: "OTA 캘리브레이션 업데이트가 새로운 기능입니다." },
    { id: 987, day: 15, en: "The standardization of interfaces simplifies integration.", ko: "인터페이스 표준화가 통합을 단순화합니다." },
    { id: 988, day: 15, en: "The open-source software approach is being evaluated.", ko: "오픈소스 소프트웨어 접근법을 평가하고 있습니다." },
    { id: 989, day: 15, en: "The simulation platform supports multi-physics analysis.", ko: "시뮬레이션 플랫폼이 다중 물리 해석을 지원합니다." },
    { id: 990, day: 15, en: "The test automation reduces development time significantly.", ko: "테스트 자동화가 개발 시간을 크게 줄입니다." },
    { id: 991, day: 15, en: "The virtual validation replaces some physical tests.", ko: "가상 검증이 일부 물리적 테스트를 대체합니다." },
    { id: 992, day: 15, en: "The real-time simulation runs at hardware speed.", ko: "실시간 시뮬레이션이 하드웨어 속도로 실행됩니다." },
    { id: 993, day: 15, en: "The data-driven approach optimizes the development process.", ko: "데이터 기반 접근법이 개발 프로세스를 최적화합니다." },
    { id: 994, day: 15, en: "The parametric study identified the optimal design point.", ko: "파라미터 연구가 최적 설계점을 식별했습니다." },
    { id: 995, day: 15, en: "The robust design methodology ensures consistent performance.", ko: "로버스트 설계 방법론이 일관된 성능을 보장합니다." },
    { id: 996, day: 15, en: "The Taguchi method reduces the number of experiments.", ko: "다구찌 방법이 실험 횟수를 줄입니다." },
    { id: 997, day: 15, en: "The Design of Experiments approach is very efficient.", ko: "실험 계획법 접근이 매우 효율적입니다." },
    { id: 998, day: 15, en: "The response surface method maps the design space.", ko: "반응 표면법이 설계 공간을 매핑합니다." },
    { id: 999, day: 15, en: "The multi-objective optimization balances cost and performance.", ko: "다중 목적 최적화가 비용과 성능의 균형을 맞춥니다." },
    { id: 1000, day: 15, en: "The future of EPS is intelligent and connected.", ko: "EPS의 미래는 지능적이고 연결된 것입니다." }
);

DAY_NAMES[13] = "양산 & 품질 관리";
DAY_NAMES[14] = "비즈니스 & 일반 회의";
DAY_NAMES[15] = "심화 기술 & 최신 트렌드";
DAY_NAMES_EN[13] = "Production & Quality";
DAY_NAMES_EN[14] = "Business & General";
DAY_NAMES_EN[15] = "Advanced Tech & Trends";
