// Day 9: 설계 & CAD/CAE (Design & Simulation) - 511~580
SENTENCES.push(
    { id: 511, day: 9, en: "I updated the 3D model in CATIA this morning.", ko: "오늘 아침에 카티아에서 3D 모델을 업데이트했습니다." },
    { id: 512, day: 9, en: "The assembly interference check shows two clashes.", ko: "어셈블리 간섭 체크에서 2개의 충돌이 보입니다." },
    { id: 513, day: 9, en: "The cross-section view shows the internal structure.", ko: "단면도에서 내부 구조가 보입니다." },
    { id: 514, day: 9, en: "Can you zoom in on the connector area?", ko: "커넥터 부분을 확대해 주시겠어요?" },
    { id: 515, day: 9, en: "The GD&T callout needs to be revised.", ko: "기하공차 호출을 수정해야 합니다." },
    { id: 516, day: 9, en: "The tolerance stack-up analysis is complete.", ko: "공차 누적 분석이 완료되었습니다." },
    { id: 517, day: 9, en: "The worst-case clearance is 0.1mm.", ko: "최악의 경우 클리어런스는 0.1mm입니다." },
    { id: 518, day: 9, en: "We need to add a chamfer to this edge.", ko: "이 모서리에 챔퍼를 추가해야 합니다." },
    { id: 519, day: 9, en: "The fillet radius should be at least 1mm.", ko: "필렛 반경은 최소 1mm이어야 합니다." },
    { id: 520, day: 9, en: "The draft angle for the mold is 3 degrees.", ko: "금형용 구배 각도는 3도입니다." },
    { id: 521, day: 9, en: "The parting line is located here on the housing.", ko: "파팅 라인은 하우징의 여기에 위치합니다." },
    { id: 522, day: 9, en: "The gate location affects the flow pattern.", ko: "게이트 위치가 유동 패턴에 영향을 줍니다." },
    { id: 523, day: 9, en: "The mold flow analysis shows a short shot risk.", ko: "금형 유동 해석에서 숏샷 위험이 보입니다." },
    { id: 524, day: 9, en: "The weld line position needs to be moved.", ko: "웰드 라인 위치를 이동해야 합니다." },
    { id: 525, day: 9, en: "The shrinkage rate for this material is 0.6%.", ko: "이 소재의 수축률은 0.6%입니다." },
    { id: 526, day: 9, en: "The FEA mesh size is set to 2mm.", ko: "FEA 메시 크기는 2mm로 설정되어 있습니다." },
    { id: 527, day: 9, en: "The stress distribution is uniform across the part.", ko: "응력 분포가 부품 전체에 균일합니다." },
    { id: 528, day: 9, en: "The maximum von Mises stress is 180 MPa.", ko: "최대 폰 미세스 응력은 180MPa입니다." },
    { id: 529, day: 9, en: "The displacement under load is 0.05mm.", ko: "하중 하의 변위는 0.05mm입니다." },
    { id: 530, day: 9, en: "The thermal simulation shows hot spots near the coil.", ko: "열 시뮬레이션에서 코일 근처에 핫스팟이 보입니다." },
    { id: 531, day: 9, en: "The cooling channel design needs optimization.", ko: "냉각 채널 설계를 최적화해야 합니다." },
    { id: 532, day: 9, en: "The electromagnetic simulation predicts higher torque.", ko: "전자기 시뮬레이션에서 더 높은 토크를 예측합니다." },
    { id: 533, day: 9, en: "The topology optimization reduced weight by 15%.", ko: "위상 최적화로 무게가 15% 줄었습니다." },
    { id: 534, day: 9, en: "The CFD analysis shows insufficient airflow.", ko: "CFD 해석에서 불충분한 공기 흐름이 보입니다." },
    { id: 535, day: 9, en: "Let me export the STEP file for you.", ko: "STEP 파일을 내보내 드리겠습니다." },
    { id: 536, day: 9, en: "The 2D drawing follows the ISO standard.", ko: "2D 도면은 ISO 표준을 따릅니다." },
    { id: 537, day: 9, en: "The revision history is documented on the title block.", ko: "개정 이력이 타이틀 블록에 문서화되어 있습니다." },
    { id: 538, day: 9, en: "The material specification is indicated in the drawing note.", ko: "재질 사양이 도면 노트에 표시되어 있습니다." },
    { id: 539, day: 9, en: "The surface treatment is zinc plating.", ko: "표면 처리는 아연 도금입니다." },
    { id: 540, day: 9, en: "The assembly sequence is documented in the work instruction.", ko: "조립 순서가 작업 지침서에 문서화되어 있습니다." },
    { id: 541, day: 9, en: "The tightening torque for the bolt is 8 Nm.", ko: "볼트 체결 토크는 8Nm입니다." },
    { id: 542, day: 9, en: "The snap-fit design allows tool-free assembly.", ko: "스냅핏 설계로 공구 없이 조립이 가능합니다." },
    { id: 543, day: 9, en: "The potting compound protects the electronics.", ko: "포팅 컴파운드가 전자부품을 보호합니다." },
    { id: 544, day: 9, en: "The conformal coating thickness is 50 microns.", ko: "컨포멀 코팅 두께는 50마이크론입니다." },
    { id: 545, day: 9, en: "The thermal pad ensures good heat transfer.", ko: "서멀 패드가 양호한 열전달을 보장합니다." },
    { id: 546, day: 9, en: "The PCB is a 4-layer board design.", ko: "PCB는 4층 기판 설계입니다." },
    { id: 547, day: 9, en: "The minimum trace width is 0.2mm.", ko: "최소 트레이스 폭은 0.2mm입니다." },
    { id: 548, day: 9, en: "The high current traces need wider copper.", ko: "대전류 트레이스에는 더 넓은 동박이 필요합니다." },
    { id: 549, day: 9, en: "The component placement follows the EMC guidelines.", ko: "부품 배치가 EMC 가이드라인을 따릅니다." },
    { id: 550, day: 9, en: "The ground plane helps reduce electromagnetic interference.", ko: "접지면이 전자기 간섭을 줄이는 데 도움이 됩니다." },
    { id: 551, day: 9, en: "The decoupling capacitor should be placed close to the IC.", ko: "디커플링 커패시터는 IC 가까이에 배치해야 합니다." },
    { id: 552, day: 9, en: "The DFM review identified three high-risk areas.", ko: "DFM 리뷰에서 3개의 고위험 영역을 확인했습니다." },
    { id: 553, day: 9, en: "The Design for Assembly analysis suggests fewer fasteners.", ko: "DFA 분석에서 체결부품 축소를 제안합니다." },
    { id: 554, day: 9, en: "The packaging design protects the product during shipping.", ko: "포장 설계가 운송 중 제품을 보호합니다." },
    { id: 555, day: 9, en: "The label position is defined in the customer specification.", ko: "라벨 위치가 고객 사양에 정의되어 있습니다." },
    { id: 556, day: 9, en: "The barcode contains the serial number and production date.", ko: "바코드에 시리얼 번호와 생산일이 포함됩니다." },
    { id: 557, day: 9, en: "The traceability system tracks each component.", ko: "추적 시스템이 각 부품을 추적합니다." },
    { id: 558, day: 9, en: "The design review checklist has been completed.", ko: "설계 리뷰 체크리스트가 완료되었습니다." },
    { id: 559, day: 9, en: "The peer review found no critical issues.", ko: "동료 리뷰에서 심각한 문제가 발견되지 않았습니다." },
    { id: 560, day: 9, en: "The CATIA parameter table drives the model dimensions.", ko: "카티아 파라미터 테이블이 모델 치수를 구동합니다." },
    { id: 561, day: 9, en: "The master model approach ensures design consistency.", ko: "마스터 모델 접근법이 설계 일관성을 보장합니다." },
    { id: 562, day: 9, en: "The exploded view clearly shows all components.", ko: "분해도에서 모든 부품이 명확히 보입니다." },
    { id: 563, day: 9, en: "The BOM structure follows the assembly hierarchy.", ko: "BOM 구조가 조립 계층을 따릅니다." },
    { id: 564, day: 9, en: "The mass properties report is attached.", ko: "질량 속성 보고서가 첨부되어 있습니다." },
    { id: 565, day: 9, en: "The center of gravity is within the acceptable zone.", ko: "무게 중심이 허용 영역 내에 있습니다." },
    { id: 566, day: 9, en: "The moment of inertia affects the dynamic response.", ko: "관성 모멘트가 동적 응답에 영향을 줍니다." },
    { id: 567, day: 9, en: "The simulation boundary conditions need to be verified.", ko: "시뮬레이션 경계 조건을 검증해야 합니다." },
    { id: 568, day: 9, en: "The convergence criteria for the solver is set.", ko: "솔버의 수렴 조건이 설정되어 있습니다." },
    { id: 569, day: 9, en: "The correlation between simulation and test is 95%.", ko: "시뮬레이션과 테스트 간 상관성이 95%입니다." },
    { id: 570, day: 9, en: "We need to update the design guidelines document.", ko: "설계 가이드라인 문서를 업데이트해야 합니다." },
    { id: 571, day: 9, en: "The standard part library is available on the shared drive.", ko: "표준 부품 라이브러리가 공유 드라이브에 있습니다." },
    { id: 572, day: 9, en: "The PDM system manages all the CAD files.", ko: "PDM 시스템이 모든 CAD 파일을 관리합니다." },
    { id: 573, day: 9, en: "Please check in the latest version to PLM.", ko: "PLM에 최신 버전을 체크인해 주세요." },
    { id: 574, day: 9, en: "The version conflict needs to be resolved.", ko: "버전 충돌을 해결해야 합니다." },
    { id: 575, day: 9, en: "The old revision should be marked as obsolete.", ko: "구 개정판은 폐기로 표시해야 합니다." },
    { id: 576, day: 9, en: "The simulation shows the temperature rise is acceptable.", ko: "시뮬레이션에서 온도 상승이 허용 범위임을 보여줍니다." },
    { id: 577, day: 9, en: "The contact pressure between parts is too high.", ko: "부품 간 접촉 압력이 너무 높습니다." },
    { id: 578, day: 9, en: "The clearance fit allows easy disassembly.", ko: "헐거운 끼워맞춤으로 쉬운 분해가 가능합니다." },
    { id: 579, day: 9, en: "The interference fit secures the bearing in place.", ko: "억지 끼워맞춤으로 베어링을 고정합니다." },
    { id: 580, day: 9, en: "The sealing surface finish must meet the leakage requirement.", ko: "밀봉면 표면 처리가 누출 요구사항을 충족해야 합니다." }
);

// Day 10: 고객 대응 & 협상 (Customer Relations & Negotiation) - 581~650
SENTENCES.push(
    { id: 581, day: 10, en: "The customer requested a design modification.", ko: "고객이 설계 수정을 요청했습니다." },
    { id: 582, day: 10, en: "We received the updated specification from the OEM.", ko: "OEM으로부터 업데이트된 사양을 받았습니다." },
    { id: 583, day: 10, en: "The customer's requirement is very challenging.", ko: "고객의 요구사항이 매우 도전적입니다." },
    { id: 584, day: 10, en: "We need to align with the customer's expectations.", ko: "고객의 기대에 맞춰야 합니다." },
    { id: 585, day: 10, en: "The OEM approval process takes 4 weeks.", ko: "OEM 승인 프로세스에 4주가 걸립니다." },
    { id: 586, day: 10, en: "We need to submit the technical proposal by Friday.", ko: "금요일까지 기술 제안서를 제출해야 합니다." },
    { id: 587, day: 10, en: "The price negotiation is still ongoing.", ko: "가격 협상이 아직 진행 중입니다." },
    { id: 588, day: 10, en: "The unit price includes tooling amortization.", ko: "단가에 금형 상각비가 포함되어 있습니다." },
    { id: 589, day: 10, en: "The annual volume forecast is 200,000 units.", ko: "연간 물량 예측은 20만 개입니다." },
    { id: 590, day: 10, en: "The contract period is five years.", ko: "계약 기간은 5년입니다." },
    { id: 591, day: 10, en: "We are competing against two other suppliers.", ko: "다른 두 공급업체와 경쟁하고 있습니다." },
    { id: 592, day: 10, en: "Our competitive advantage is the integrated design.", ko: "우리의 경쟁 우위는 통합 설계입니다." },
    { id: 593, day: 10, en: "The customer wants a cost breakdown structure.", ko: "고객이 비용 분석 구조를 원합니다." },
    { id: 594, day: 10, en: "The value engineering proposal saves 8% per unit.", ko: "VA/VE 제안이 단위당 8%를 절감합니다." },
    { id: 595, day: 10, en: "The customer is satisfied with our quality performance.", ko: "고객이 우리의 품질 실적에 만족하고 있습니다." },
    { id: 596, day: 10, en: "We achieved zero PPM in the last quarter.", ko: "지난 분기에 제로 PPM을 달성했습니다." },
    { id: 597, day: 10, en: "The delivery performance is 99.5% on time.", ko: "납품 실적은 99.5% 정시 납품입니다." },
    { id: 598, day: 10, en: "The customer audit score was 92 points.", ko: "고객 감사 점수는 92점이었습니다." },
    { id: 599, day: 10, en: "We need to present our technology roadmap.", ko: "우리의 기술 로드맵을 발표해야 합니다." },
    { id: 600, day: 10, en: "The patent application has been filed.", ko: "특허 출원이 접수되었습니다." },
    { id: 601, day: 10, en: "This is a joint development project with the customer.", ko: "이것은 고객과의 공동 개발 프로젝트입니다." },
    { id: 602, day: 10, en: "The customer benchmark test showed positive results.", ko: "고객 벤치마크 테스트에서 긍정적 결과가 나왔습니다." },
    { id: 603, day: 10, en: "We will arrange a plant tour for the customer team.", ko: "고객팀을 위한 공장 투어를 준비하겠습니다." },
    { id: 604, day: 10, en: "The localization plan will reduce logistics costs.", ko: "현지화 계획으로 물류 비용을 줄일 것입니다." },
    { id: 605, day: 10, en: "The customer requires local technical support.", ko: "고객이 현지 기술 지원을 요구합니다." },
    { id: 606, day: 10, en: "We have a technical center in Europe.", ko: "유럽에 기술 센터가 있습니다." },
    { id: 607, day: 10, en: "The customer's vehicle platform is shared across models.", ko: "고객의 차량 플랫폼이 여러 모델에 공유됩니다." },
    { id: 608, day: 10, en: "The global production volume is expected to be 500K.", ko: "글로벌 생산 물량은 50만 개로 예상됩니다." },
    { id: 609, day: 10, en: "The warranty period is 10 years or 200,000 km.", ko: "보증 기간은 10년 또는 20만 km입니다." },
    { id: 610, day: 10, en: "The customer requires a resident engineer at their plant.", ko: "고객이 자사 공장에 상주 엔지니어를 요구합니다." },
    { id: 611, day: 10, en: "We will provide 24-hour technical support.", ko: "24시간 기술 지원을 제공하겠습니다." },
    { id: 612, day: 10, en: "The quarterly business review is next week.", ko: "분기별 사업 리뷰가 다음 주입니다." },
    { id: 613, day: 10, en: "The customer scorecard needs improvement in delivery.", ko: "고객 스코어카드에서 납품 부문 개선이 필요합니다." },
    { id: 614, day: 10, en: "We are nominated as the preferred supplier.", ko: "우리가 우선 공급업체로 선정되었습니다." },
    { id: 615, day: 10, en: "The technical feasibility has been confirmed.", ko: "기술적 타당성이 확인되었습니다." },
    { id: 616, day: 10, en: "The customer accepted our counter-proposal.", ko: "고객이 우리의 대안 제안을 수락했습니다." },
    { id: 617, day: 10, en: "We need to renegotiate the payment terms.", ko: "지불 조건을 재협상해야 합니다." },
    { id: 618, day: 10, en: "The claim for the tooling damage has been filed.", ko: "금형 파손에 대한 클레임이 접수되었습니다." },
    { id: 619, day: 10, en: "The customer wants a live demonstration.", ko: "고객이 실시간 시연을 원합니다." },
    { id: 620, day: 10, en: "We prepared a comparison table with the competitor.", ko: "경쟁사와의 비교표를 준비했습니다." },
    { id: 621, day: 10, en: "The customer emphasized the importance of weight reduction.", ko: "고객이 경량화의 중요성을 강조했습니다." },
    { id: 622, day: 10, en: "The system integration responsibility belongs to the OEM.", ko: "시스템 통합 책임은 OEM에 있습니다." },
    { id: 623, day: 10, en: "We provide a turnkey solution.", ko: "우리는 턴키 솔루션을 제공합니다." },
    { id: 624, day: 10, en: "The customer specification has been baselined.", ko: "고객 사양이 기준선으로 확정되었습니다." },
    { id: 625, day: 10, en: "Any deviation requires written customer approval.", ko: "모든 이탈은 서면 고객 승인이 필요합니다." },
    { id: 626, day: 10, en: "The commercial and technical teams need to be aligned.", ko: "영업팀과 기술팀이 일치해야 합니다." },
    { id: 627, day: 10, en: "We should set up a regular technical call with the customer.", ko: "고객과 정기적인 기술 콜을 설정해야 합니다." },
    { id: 628, day: 10, en: "The customer timeline requires immediate action.", ko: "고객 일정상 즉각적인 조치가 필요합니다." },
    { id: 629, day: 10, en: "The customer is very strict about the delivery schedule.", ko: "고객이 납품 일정에 매우 엄격합니다." },
    { id: 630, day: 10, en: "We need to manage the customer's expectations carefully.", ko: "고객의 기대치를 신중하게 관리해야 합니다." },
    { id: 631, day: 10, en: "The after-sales service agreement is being drafted.", ko: "애프터서비스 계약이 작성 중입니다." },
    { id: 632, day: 10, en: "The customer feedback was very positive on our prototype.", ko: "프로토타입에 대한 고객 피드백이 매우 긍정적이었습니다." },
    { id: 633, day: 10, en: "We should highlight our ISO 26262 certification.", ko: "우리의 ISO 26262 인증을 강조해야 합니다." },
    { id: 634, day: 10, en: "The customer platform launch date is fixed.", ko: "고객 플랫폼 출시일이 확정되었습니다." },
    { id: 635, day: 10, en: "We cannot afford any delay at this stage.", ko: "이 단계에서 지연은 용납할 수 없습니다." },
    { id: 636, day: 10, en: "The customer is evaluating our latest sample.", ko: "고객이 우리의 최신 샘플을 평가하고 있습니다." },
    { id: 637, day: 10, en: "The specification change impacts our cost structure.", ko: "사양 변경이 우리의 원가 구조에 영향을 줍니다." },
    { id: 638, day: 10, en: "We need to submit a claim for the additional cost.", ko: "추가 비용에 대한 클레임을 제출해야 합니다." },
    { id: 639, day: 10, en: "The joint validation program will start in June.", ko: "공동 검증 프로그램이 6월에 시작됩니다." },
    { id: 640, day: 10, en: "The customer wants a face-to-face meeting in Munich.", ko: "고객이 뮌헨에서 대면 회의를 원합니다." },
    { id: 641, day: 10, en: "I am available to travel to the customer site.", ko: "고객 현장으로 출장 가능합니다." },
    { id: 642, day: 10, en: "The business trip report has been submitted.", ko: "출장 보고서가 제출되었습니다." },
    { id: 643, day: 10, en: "We received positive feedback from the German team.", ko: "독일 팀으로부터 긍정적 피드백을 받았습니다." },
    { id: 644, day: 10, en: "The customer is considering expanding the project scope.", ko: "고객이 프로젝트 범위 확대를 고려하고 있습니다." },
    { id: 645, day: 10, en: "We should propose additional features for differentiation.", ko: "차별화를 위해 추가 기능을 제안해야 합니다." },
    { id: 646, day: 10, en: "The customer decision is expected by end of month.", ko: "고객 결정은 월말까지 예상됩니다." },
    { id: 647, day: 10, en: "We are confident in winning this project.", ko: "이 프로젝트 수주에 자신 있습니다." },
    { id: 648, day: 10, en: "The LOI has been received from the customer.", ko: "고객으로부터 LOI를 받았습니다." },
    { id: 649, day: 10, en: "The final contract is under legal review.", ko: "최종 계약서가 법무 검토 중입니다." },
    { id: 650, day: 10, en: "Thank you for your trust in our company.", ko: "저희 회사를 신뢰해 주셔서 감사합니다." }
);

DAY_NAMES[9] = "설계 & CAD/CAE";
DAY_NAMES[10] = "고객 대응 & 협상";
DAY_NAMES_EN[9] = "Design & Simulation";
DAY_NAMES_EN[10] = "Customer Relations & Negotiation";
