// Day 11: 소프트웨어 & 제어 알고리즘 (Software & Control) - 651~720
SENTENCES.push(
    { id: 651, day: 11, en: "The software version is 2.3.1 build 456.", ko: "소프트웨어 버전은 2.3.1 빌드 456입니다." },
    { id: 652, day: 11, en: "The firmware update fixes the torque oscillation bug.", ko: "펌웨어 업데이트로 토크 진동 버그가 수정됩니다." },
    { id: 653, day: 11, en: "The calibration parameter set has been released.", ko: "캘리브레이션 파라미터 세트가 출시되었습니다." },
    { id: 654, day: 11, en: "The PID controller gains need fine-tuning.", ko: "PID 제어기 게인을 미세 조정해야 합니다." },
    { id: 655, day: 11, en: "The control loop runs at 10 kHz.", ko: "제어 루프는 10kHz로 동작합니다." },
    { id: 656, day: 11, en: "The diagnostic trouble code is stored in memory.", ko: "진단 고장 코드가 메모리에 저장됩니다." },
    { id: 657, day: 11, en: "The UDS protocol is used for diagnostic communication.", ko: "진단 통신에 UDS 프로토콜을 사용합니다." },
    { id: 658, day: 11, en: "The bootloader supports over-the-air updates.", ko: "부트로더가 무선 업데이트를 지원합니다." },
    { id: 659, day: 11, en: "The interrupt handler processes the sensor signal.", ko: "인터럽트 핸들러가 센서 신호를 처리합니다." },
    { id: 660, day: 11, en: "The stack overflow issue has been resolved.", ko: "스택 오버플로우 문제가 해결되었습니다." },
    { id: 661, day: 11, en: "The CPU load is 85% at maximum steering speed.", ko: "최대 조향 속도에서 CPU 부하는 85%입니다." },
    { id: 662, day: 11, en: "The RAM usage needs to be optimized.", ko: "RAM 사용을 최적화해야 합니다." },
    { id: 663, day: 11, en: "The AUTOSAR architecture is implemented.", ko: "AUTOSAR 아키텍처가 구현되어 있습니다." },
    { id: 664, day: 11, en: "The software component follows MISRA C guidelines.", ko: "소프트웨어 컴포넌트가 MISRA C 가이드라인을 따릅니다." },
    { id: 665, day: 11, en: "The code review found a potential null pointer issue.", ko: "코드 리뷰에서 잠재적 널 포인터 문제를 발견했습니다." },
    { id: 666, day: 11, en: "The unit test coverage is 90%.", ko: "단위 테스트 커버리지는 90%입니다." },
    { id: 667, day: 11, en: "The integration test is scheduled for next sprint.", ko: "통합 테스트가 다음 스프린트에 예정되어 있습니다." },
    { id: 668, day: 11, en: "The software release follows the V-model process.", ko: "소프트웨어 릴리즈는 V 모델 프로세스를 따릅니다." },
    { id: 669, day: 11, en: "The ASPICE assessment is at level 2.", ko: "ASPICE 평가가 레벨 2에 있습니다." },
    { id: 670, day: 11, en: "The requirements traceability matrix is complete.", ko: "요구사항 추적 매트릭스가 완료되었습니다." },
    { id: 671, day: 11, en: "The safety monitor detects the torque sensor failure.", ko: "안전 모니터가 토크 센서 고장을 감지합니다." },
    { id: 672, day: 11, en: "The redundant channel provides backup control.", ko: "이중화 채널이 백업 제어를 제공합니다." },
    { id: 673, day: 11, en: "The safety concept document is under review.", ko: "안전 컨셉 문서가 검토 중입니다." },
    { id: 674, day: 11, en: "The hazard analysis identified 12 safety goals.", ko: "위험 분석에서 12개의 안전 목표를 식별했습니다." },
    { id: 675, day: 11, en: "The decomposition of ASIL D to ASIL B plus B is proposed.", ko: "ASIL D를 ASIL B+B로 분해하는 것을 제안합니다." },
    { id: 676, day: 11, en: "The software implements a ramp-down strategy on fault.", ko: "소프트웨어가 고장 시 램프다운 전략을 구현합니다." },
    { id: 677, day: 11, en: "The motor current is limited to prevent overheating.", ko: "과열 방지를 위해 모터 전류가 제한됩니다." },
    { id: 678, day: 11, en: "The derating function activates above 120 degrees.", ko: "120도 이상에서 디레이팅 기능이 활성화됩니다." },
    { id: 679, day: 11, en: "The signal filtering removes noise from sensor data.", ko: "신호 필터링이 센서 데이터에서 노이즈를 제거합니다." },
    { id: 680, day: 11, en: "The lookup table stores the assist torque values.", ko: "룩업 테이블에 어시스트 토크 값이 저장됩니다." },
    { id: 681, day: 11, en: "The return to center function is speed dependent.", ko: "복원 기능은 속도에 따라 달라집니다." },
    { id: 682, day: 11, en: "The active damping reduces steering oscillation.", ko: "능동 댐핑이 조향 진동을 줄입니다." },
    { id: 683, day: 11, en: "The friction compensation improves steering feel.", ko: "마찰 보상이 조향 감각을 개선합니다." },
    { id: 684, day: 11, en: "The inertia compensation is tuned for the vehicle weight.", ko: "관성 보상이 차량 중량에 맞게 튜닝되어 있습니다." },
    { id: 685, day: 11, en: "The software version management uses Git.", ko: "소프트웨어 버전 관리에 Git을 사용합니다." },
    { id: 686, day: 11, en: "The CI/CD pipeline runs automated tests.", ko: "CI/CD 파이프라인이 자동화 테스트를 실행합니다." },
    { id: 687, day: 11, en: "The defect tracking is done in JIRA.", ko: "결함 추적은 JIRA에서 수행합니다." },
    { id: 688, day: 11, en: "The software architecture review is next Tuesday.", ko: "소프트웨어 아키텍처 리뷰가 다음 주 화요일입니다." },
    { id: 689, day: 11, en: "The motor control algorithm runs on an ARM processor.", ko: "모터 제어 알고리즘이 ARM 프로세서에서 실행됩니다." },
    { id: 690, day: 11, en: "The ADC sampling rate is 100 microseconds.", ko: "ADC 샘플링 주기는 100마이크로초입니다." },
    { id: 691, day: 11, en: "The overcurrent protection trips at 120 amps.", ko: "과전류 보호가 120A에서 트립됩니다." },
    { id: 692, day: 11, en: "The voltage monitoring detects undervoltage conditions.", ko: "전압 모니터링이 저전압 상태를 감지합니다." },
    { id: 693, day: 11, en: "The flash memory stores non-volatile configuration data.", ko: "플래시 메모리에 비휘발성 설정 데이터가 저장됩니다." },
    { id: 694, day: 11, en: "The EEPROM write cycle limit is one million.", ko: "EEPROM 쓰기 사이클 제한은 100만 회입니다." },
    { id: 695, day: 11, en: "The communication timeout is set to 100 milliseconds.", ko: "통신 타임아웃은 100밀리초로 설정되어 있습니다." },
    { id: 696, day: 11, en: "The CRC check ensures data integrity.", ko: "CRC 체크가 데이터 무결성을 보장합니다." },
    { id: 697, day: 11, en: "The model-based design approach is used for development.", ko: "개발에 모델 기반 설계 접근법이 사용됩니다." },
    { id: 698, day: 11, en: "The Simulink model generates the production code.", ko: "시뮬링크 모델이 양산 코드를 생성합니다." },
    { id: 699, day: 11, en: "The hardware-in-the-loop test validates the software.", ko: "하드웨어 인 더 루프 테스트가 소프트웨어를 검증합니다." },
    { id: 700, day: 11, en: "The software-in-the-loop simulation passed successfully.", ko: "소프트웨어 인 더 루프 시뮬레이션이 성공적으로 통과했습니다." },
    { id: 701, day: 11, en: "The data logging function captures driving events.", ko: "데이터 로깅 기능이 주행 이벤트를 캡처합니다." },
    { id: 702, day: 11, en: "The end-of-line programming configures each unit.", ko: "EOL 프로그래밍이 각 유닛을 설정합니다." },
    { id: 703, day: 11, en: "The vehicle variant coding is applied via CAN.", ko: "차량 변형 코딩이 CAN으로 적용됩니다." },
    { id: 704, day: 11, en: "The speed signal comes from the vehicle CAN bus.", ko: "속도 신호는 차량 CAN 버스에서 옵니다." },
    { id: 705, day: 11, en: "The LIN communication is used for the column switch.", ko: "컬럼 스위치에 LIN 통신이 사용됩니다." },
    { id: 706, day: 11, en: "The position sensor resolution is 0.1 degrees.", ko: "위치 센서 분해능은 0.1도입니다." },
    { id: 707, day: 11, en: "The angle accuracy must be within plus or minus 0.5 degrees.", ko: "각도 정확도가 ±0.5도 이내여야 합니다." },
    { id: 708, day: 11, en: "The response time from steering input to assist is 5 ms.", ko: "조향 입력에서 어시스트까지 응답 시간은 5ms입니다." },
    { id: 709, day: 11, en: "The software safety analysis is documented in the FMEDA.", ko: "소프트웨어 안전 분석이 FMEDA에 문서화되어 있습니다." },
    { id: 710, day: 11, en: "The common cause failure analysis has been completed.", ko: "공통 원인 고장 분석이 완료되었습니다." },
    { id: 711, day: 11, en: "The safety validation test plan is approved.", ko: "안전 검증 테스트 계획이 승인되었습니다." },
    { id: 712, day: 11, en: "The freedom from interference must be demonstrated.", ko: "간섭으로부터의 자유를 입증해야 합니다." },
    { id: 713, day: 11, en: "The safety case has been compiled and reviewed.", ko: "안전 케이스가 편집되고 검토되었습니다." },
    { id: 714, day: 11, en: "The cybersecurity requirements are included.", ko: "사이버 보안 요구사항이 포함되어 있습니다." },
    { id: 715, day: 11, en: "The secure boot prevents unauthorized firmware.", ko: "보안 부팅이 허가되지 않은 펌웨어를 방지합니다." },
    { id: 716, day: 11, en: "The encryption key management follows ISO 21434.", ko: "암호화 키 관리가 ISO 21434를 따릅니다." },
    { id: 717, day: 11, en: "The threat analysis and risk assessment is in progress.", ko: "위협 분석 및 리스크 평가가 진행 중입니다." },
    { id: 718, day: 11, en: "The software complexity metric needs to be tracked.", ko: "소프트웨어 복잡도 메트릭을 추적해야 합니다." },
    { id: 719, day: 11, en: "The regression test ensures no new bugs are introduced.", ko: "회귀 테스트가 새로운 버그가 유입되지 않음을 보장합니다." },
    { id: 720, day: 11, en: "The release note documents all changes in this version.", ko: "릴리즈 노트에 이 버전의 모든 변경 사항이 문서화됩니다." }
);

// Day 12: 이메일 & 문서 (Email & Documentation) - 721~790
SENTENCES.push(
    { id: 721, day: 12, en: "Please find the attached report for your reference.", ko: "참고하시도록 보고서를 첨부합니다." },
    { id: 722, day: 12, en: "I am writing to follow up on the action items.", ko: "액션 아이템 관련하여 후속 메일 드립니다." },
    { id: 723, day: 12, en: "As per our discussion, I have updated the schedule.", ko: "논의한 대로 일정을 업데이트했습니다." },
    { id: 724, day: 12, en: "Could you please confirm receipt of this email?", ko: "이 이메일 수신 확인 부탁드립니다." },
    { id: 725, day: 12, en: "I would like to set up a call to discuss this further.", ko: "이 부분에 대해 추가 논의할 콜을 잡고 싶습니다." },
    { id: 726, day: 12, en: "Please refer to the minutes from last meeting.", ko: "지난 회의 회의록을 참조해 주세요." },
    { id: 727, day: 12, en: "I have CC'd the relevant team members.", ko: "관련 팀원들을 참조에 넣었습니다." },
    { id: 728, day: 12, en: "Please forward this to the appropriate person.", ko: "적절한 담당자에게 전달해 주세요." },
    { id: 729, day: 12, en: "Just a gentle reminder about the deadline.", ko: "마감일에 대한 간곡한 리마인드입니다." },
    { id: 730, day: 12, en: "I apologize for the late reply.", ko: "늦은 답변 죄송합니다." },
    { id: 731, day: 12, en: "Thank you for the prompt response.", ko: "신속한 답변 감사합니다." },
    { id: 732, day: 12, en: "I need your approval on the attached document.", ko: "첨부 문서에 대한 승인이 필요합니다." },
    { id: 733, day: 12, en: "The document is ready for your review and signature.", ko: "문서가 검토 및 서명을 위해 준비되었습니다." },
    { id: 734, day: 12, en: "Please note the updated deadline in red.", ko: "빨간색으로 표시된 업데이트된 마감일을 참고하세요." },
    { id: 735, day: 12, en: "I have highlighted the key changes in yellow.", ko: "주요 변경 사항을 노란색으로 표시했습니다." },
    { id: 736, day: 12, en: "The revision history is on the first page.", ko: "개정 이력이 첫 페이지에 있습니다." },
    { id: 737, day: 12, en: "Please use the latest template for the report.", ko: "보고서에 최신 양식을 사용해 주세요." },
    { id: 738, day: 12, en: "The file is too large to send by email.", ko: "파일이 이메일로 보내기에 너무 큽니다." },
    { id: 739, day: 12, en: "I uploaded the file to the shared folder.", ko: "공유 폴더에 파일을 업로드했습니다." },
    { id: 740, day: 12, en: "The download link will expire in 7 days.", ko: "다운로드 링크가 7일 후 만료됩니다." },
    { id: 741, day: 12, en: "Please sign and return the document by Wednesday.", ko: "수요일까지 문서에 서명하고 반환해 주세요." },
    { id: 742, day: 12, en: "The meeting invitation has been sent.", ko: "회의 초대장이 발송되었습니다." },
    { id: 743, day: 12, en: "Please RSVP by end of day.", ko: "오늘 중으로 참석 여부를 알려주세요." },
    { id: 744, day: 12, en: "The agenda for tomorrow's meeting is attached.", ko: "내일 회의 안건이 첨부되어 있습니다." },
    { id: 745, day: 12, en: "The action item tracker has been updated.", ko: "액션 아이템 트래커가 업데이트되었습니다." },
    { id: 746, day: 12, en: "All open items should be closed by Friday.", ko: "모든 오픈 항목이 금요일까지 종료되어야 합니다." },
    { id: 747, day: 12, en: "I will circulate the updated document tomorrow.", ko: "내일 업데이트된 문서를 회람하겠습니다." },
    { id: 748, day: 12, en: "Please review and provide comments by Thursday.", ko: "목요일까지 검토하고 의견을 주세요." },
    { id: 749, day: 12, en: "Your feedback on the draft is much appreciated.", ko: "초안에 대한 피드백 감사드립니다." },
    { id: 750, day: 12, en: "I incorporated all your comments into the final version.", ko: "모든 의견을 최종 버전에 반영했습니다." },
    { id: 751, day: 12, en: "The specification document has been baselined.", ko: "사양 문서가 기준선으로 확정되었습니다." },
    { id: 752, day: 12, en: "Please ensure all sections are filled in.", ko: "모든 섹션이 채워져 있는지 확인해 주세요." },
    { id: 753, day: 12, en: "The executive summary is on page 2.", ko: "경영 요약이 2페이지에 있습니다." },
    { id: 754, day: 12, en: "The appendix contains the raw test data.", ko: "부록에 원시 테스트 데이터가 있습니다." },
    { id: 755, day: 12, en: "Please check the table on page 15 for accuracy.", ko: "15페이지의 표를 정확도 면에서 확인해 주세요." },
    { id: 756, day: 12, en: "The graph shows the trend over the past 6 months.", ko: "그래프가 지난 6개월간의 추세를 보여줍니다." },
    { id: 757, day: 12, en: "I prepared a one-page summary for management.", ko: "경영진을 위한 1페이지 요약을 준비했습니다." },
    { id: 758, day: 12, en: "The presentation slides will be shared before the meeting.", ko: "발표 슬라이드가 회의 전에 공유됩니다." },
    { id: 759, day: 12, en: "Could you share the latest version of the document?", ko: "문서의 최신 버전을 공유해 주시겠어요?" },
    { id: 760, day: 12, en: "The translation of the document is in progress.", ko: "문서 번역이 진행 중입니다." },
    { id: 761, day: 12, en: "Please keep this information confidential.", ko: "이 정보를 기밀로 유지해 주세요." },
    { id: 762, day: 12, en: "This email is for internal use only.", ko: "이 이메일은 내부 사용 전용입니다." },
    { id: 763, day: 12, en: "I will send a formal request letter.", ko: "공식 요청서를 보내겠습니다." },
    { id: 764, day: 12, en: "The investigation report will be issued next week.", ko: "조사 보고서는 다음 주에 발행됩니다." },
    { id: 765, day: 12, en: "Please acknowledge the specification change.", ko: "사양 변경에 대해 확인해 주세요." },
    { id: 766, day: 12, en: "The document control number is DC-2026-0045.", ko: "문서 관리 번호는 DC-2026-0045입니다." },
    { id: 767, day: 12, en: "All documents must be uploaded to the ECM system.", ko: "모든 문서는 ECM 시스템에 업로드해야 합니다." },
    { id: 768, day: 12, en: "The training material has been distributed to the team.", ko: "교육 자료가 팀에 배포되었습니다." },
    { id: 769, day: 12, en: "Please complete the online training by end of month.", ko: "월말까지 온라인 교육을 완료해 주세요." },
    { id: 770, day: 12, en: "The status update is summarized in the table below.", ko: "현황 업데이트가 아래 표에 요약되어 있습니다." },
    { id: 771, day: 12, en: "I look forward to hearing from you soon.", ko: "빠른 회신 기다리겠습니다." },
    { id: 772, day: 12, en: "Please do not hesitate to reach out if you need more info.", ko: "추가 정보가 필요하시면 언제든 연락 주세요." },
    { id: 773, day: 12, en: "Best regards from the EPS development team.", ko: "EPS 개발팀에서 보내는 안부입니다." },
    { id: 774, day: 12, en: "I am out of office from March 1 to March 5.", ko: "3월 1일부터 5일까지 부재중입니다." },
    { id: 775, day: 12, en: "For urgent matters, please contact Mr. Kim.", ko: "긴급한 건은 김 선임에게 연락해 주세요." },
    { id: 776, day: 12, en: "The minutes will be distributed within 24 hours.", ko: "회의록은 24시간 이내에 배포됩니다." },
    { id: 777, day: 12, en: "Please update your section in the shared document.", ko: "공유 문서에서 본인 섹션을 업데이트해 주세요." },
    { id: 778, day: 12, en: "The deadline has been extended by one week.", ko: "마감일이 1주일 연장되었습니다." },
    { id: 779, day: 12, en: "This supersedes the previous version dated February 10.", ko: "이것은 2월 10일 자 이전 버전을 대체합니다." },
    { id: 780, day: 12, en: "Please disregard my previous email.", ko: "이전 이메일은 무시해 주세요." },
    { id: 781, day: 12, en: "I made a mistake in the attached file.", ko: "첨부 파일에 오류가 있었습니다." },
    { id: 782, day: 12, en: "Here is the corrected version.", ko: "수정된 버전입니다." },
    { id: 783, day: 12, en: "Thank you for pointing out the error.", ko: "오류를 지적해 주셔서 감사합니다." },
    { id: 784, day: 12, en: "The issue has been resolved and documented.", ko: "문제가 해결되었고 문서화되었습니다." },
    { id: 785, day: 12, en: "Please add your signature to the approval form.", ko: "승인 양식에 서명을 추가해 주세요." },
    { id: 786, day: 12, en: "The open issue list has 8 remaining items.", ko: "오픈 이슈 리스트에 8개 항목이 남아 있습니다." },
    { id: 787, day: 12, en: "We need a status report from each team by Monday.", ko: "월요일까지 각 팀의 현황 보고서가 필요합니다." },
    { id: 788, day: 12, en: "The monthly report is due on the first business day.", ko: "월간 보고서는 첫 영업일에 마감입니다." },
    { id: 789, day: 12, en: "I summarized the test results in the attached Excel file.", ko: "테스트 결과를 첨부된 엑셀 파일에 요약했습니다." },
    { id: 790, day: 12, en: "Please reply to all so everyone stays informed.", ko: "모두에게 답장해 주셔서 모두가 공유하도록 해주세요." }
);

DAY_NAMES[11] = "소프트웨어 & 제어";
DAY_NAMES[12] = "이메일 & 문서";
DAY_NAMES_EN[11] = "Software & Control";
DAY_NAMES_EN[12] = "Email & Documentation";
