// Day 6: EPS 모터 & 제어기 기술 토론 (EPS Motor & Controller Technical) - 301~370
SENTENCES.push(
    { id: 301, day: 6, en: "The torque ripple is too high at low speed.", ko: "저속에서 토크 리플이 너무 높습니다." },
    { id: 302, day: 6, en: "We need to optimize the winding configuration.", ko: "권선 구성을 최적화해야 합니다." },
    { id: 303, day: 6, en: "The back-EMF waveform looks abnormal.", ko: "역기전력 파형이 비정상적으로 보입니다." },
    { id: 304, day: 6, en: "Have you checked the magnet temperature during the test?", ko: "테스트 중 자석 온도를 확인하셨나요?" },
    { id: 305, day: 6, en: "The demagnetization risk increases above 150 degrees.", ko: "150도 이상에서 감자 리스크가 증가합니다." },
    { id: 306, day: 6, en: "We should consider using a higher grade magnet.", ko: "더 높은 등급의 자석 사용을 고려해야 합니다." },
    { id: 307, day: 6, en: "The cogging torque needs to be reduced.", ko: "코깅 토크를 줄여야 합니다." },
    { id: 308, day: 6, en: "Can you show us the FEA simulation results?", ko: "FEA 시뮬레이션 결과를 보여주시겠어요?" },
    { id: 309, day: 6, en: "The motor efficiency at rated load is 92 percent.", ko: "정격 부하에서 모터 효율은 92%입니다." },
    { id: 310, day: 6, en: "We are targeting a maximum current of 80 amps.", ko: "최대 전류 80A를 목표로 하고 있습니다." },
    { id: 311, day: 6, en: "The stator lamination thickness is 0.35mm.", ko: "고정자 적층 두께는 0.35mm입니다." },
    { id: 312, day: 6, en: "There is interference between the rotor and the housing.", ko: "로터와 하우징 사이에 간섭이 있습니다." },
    { id: 313, day: 6, en: "The air gap is within the acceptable range.", ko: "에어갭이 허용 범위 내에 있습니다." },
    { id: 314, day: 6, en: "We detected bearing noise during the endurance test.", ko: "내구 테스트 중 베어링 소음이 감지되었습니다." },
    { id: 315, day: 6, en: "The resolver signal shows some offset error.", ko: "레졸버 신호에 오프셋 오차가 보입니다." },
    { id: 316, day: 6, en: "The ECU is overheating under full load conditions.", ko: "풀 로드 조건에서 ECU가 과열되고 있습니다." },
    { id: 317, day: 6, en: "We need to add a heat sink to the MOSFET.", ko: "MOSFET에 히트싱크를 추가해야 합니다." },
    { id: 318, day: 6, en: "The PWM frequency is set to 20 kHz.", ko: "PWM 주파수는 20kHz로 설정되어 있습니다." },
    { id: 319, day: 6, en: "Can we increase the switching frequency to reduce noise?", ko: "소음 저감을 위해 스위칭 주파수를 높일 수 있나요?" },
    { id: 320, day: 6, en: "The CAN bus communication is showing intermittent errors.", ko: "CAN 버스 통신에 간헐적 오류가 발생합니다." },
    { id: 321, day: 6, en: "The steering angle sensor needs recalibration.", ko: "조향각 센서를 재교정해야 합니다." },
    { id: 322, day: 6, en: "The assist torque map needs to be updated.", ko: "어시스트 토크 맵을 업데이트해야 합니다." },
    { id: 323, day: 6, en: "We are seeing a phase current imbalance.", ko: "상전류 불균형이 보이고 있습니다." },
    { id: 324, day: 6, en: "The motor constant meets the specification.", ko: "모터 상수가 사양을 충족합니다." },
    { id: 325, day: 6, en: "Please check the winding resistance value.", ko: "권선 저항값을 확인해 주세요." },
    { id: 326, day: 6, en: "The inductance measurement shows a 5% deviation.", ko: "인덕턴스 측정에서 5% 편차가 보입니다." },
    { id: 327, day: 6, en: "We should verify the thermal model with actual data.", ko: "실제 데이터로 열 모델을 검증해야 합니다." },
    { id: 328, day: 6, en: "The connector pin assignment has been changed.", ko: "커넥터 핀 배치가 변경되었습니다." },
    { id: 329, day: 6, en: "The PCB layout needs revision for EMC compliance.", ko: "EMC 준수를 위해 PCB 레이아웃 수정이 필요합니다." },
    { id: 330, day: 6, en: "The power supply voltage range is 9V to 16V.", ko: "전원 전압 범위는 9V에서 16V입니다." },
    { id: 331, day: 6, en: "We are using a three-phase brushless DC motor.", ko: "3상 브러시리스 DC 모터를 사용하고 있습니다." },
    { id: 332, day: 6, en: "The pole pair number is 4.", ko: "극쌍수는 4입니다." },
    { id: 333, day: 6, en: "The rated torque output is 5 Newton-meters.", ko: "정격 토크 출력은 5Nm입니다." },
    { id: 334, day: 6, en: "We are considering a dual winding motor for redundancy.", ko: "이중화를 위해 듀얼 권선 모터를 고려하고 있습니다." },
    { id: 335, day: 6, en: "The column type EPS has space constraints.", ko: "컬럼형 EPS는 공간 제약이 있습니다." },
    { id: 336, day: 6, en: "Let me share the torque-speed characteristic curve.", ko: "토크-속도 특성 곡선을 공유하겠습니다." },
    { id: 337, day: 6, en: "The iron loss is dominant at high speed operation.", ko: "고속 운전 시 철손이 지배적입니다." },
    { id: 338, day: 6, en: "The copper loss increases with the current squared.", ko: "동손은 전류의 제곱에 비례하여 증가합니다." },
    { id: 339, day: 6, en: "We achieved the target noise level of 45 decibels.", ko: "목표 소음 레벨인 45데시벨을 달성했습니다." },
    { id: 340, day: 6, en: "The vibration order analysis shows a 12th order component.", ko: "진동 차수 분석에서 12차 성분이 보입니다." },
    { id: 341, day: 6, en: "The shaft runout exceeds the tolerance.", ko: "축 흔들림이 공차를 초과합니다." },
    { id: 342, day: 6, en: "We need to tighten the press-fit tolerance.", ko: "압입 공차를 더 조여야 합니다." },
    { id: 343, day: 6, en: "The motor housing needs additional ribs for stiffness.", ko: "모터 하우징에 강성을 위한 리브를 추가해야 합니다." },
    { id: 344, day: 6, en: "The O-ring seal is leaking under pressure test.", ko: "O링 씰이 가압 테스트에서 누출됩니다." },
    { id: 345, day: 6, en: "The IP67 protection rating must be maintained.", ko: "IP67 보호 등급을 유지해야 합니다." },
    { id: 346, day: 6, en: "The bus bar connection shows high contact resistance.", ko: "버스바 연결부에서 높은 접촉 저항이 나타납니다." },
    { id: 347, day: 6, en: "We will use injection molding for the sensor housing.", ko: "센서 하우징에 사출 성형을 적용하겠습니다." },
    { id: 348, day: 6, en: "The die-casting process needs to be optimized.", ko: "다이캐스팅 공정을 최적화해야 합니다." },
    { id: 349, day: 6, en: "The rotor position is detected using a Hall sensor.", ko: "로터 위치는 홀 센서로 검출합니다." },
    { id: 350, day: 6, en: "We are switching from Hall sensors to a resolver.", ko: "홀 센서에서 레졸버로 변경하고 있습니다." },
    { id: 351, day: 6, en: "The sensorless algorithm is under development.", ko: "센서리스 알고리즘을 개발 중입니다." },
    { id: 352, day: 6, en: "The field-oriented control is implemented in the DSP.", ko: "자계 지향 제어가 DSP에 구현되어 있습니다." },
    { id: 353, day: 6, en: "The dead time compensation needs fine-tuning.", ko: "데드 타임 보상을 미세 조정해야 합니다." },
    { id: 354, day: 6, en: "The current loop bandwidth is 2 kHz.", ko: "전류 루프 대역폭은 2kHz입니다." },
    { id: 355, day: 6, en: "We need to improve the transient response.", ko: "과도 응답을 개선해야 합니다." },
    { id: 356, day: 6, en: "The torque sensor calibration data looks inconsistent.", ko: "토크 센서 교정 데이터가 일관성이 없어 보입니다." },
    { id: 357, day: 6, en: "The steering returnability test failed.", ko: "조향 복원성 테스트에 실패했습니다." },
    { id: 358, day: 6, en: "The on-center feel needs improvement.", ko: "온센터 필링을 개선해야 합니다." },
    { id: 359, day: 6, en: "The assist curve is too aggressive at highway speed.", ko: "고속도로 속도에서 어시스트 곡선이 너무 급합니다." },
    { id: 360, day: 6, en: "The parking torque requirement is 6 Nm.", ko: "주차 토크 요구사항은 6Nm입니다." },
    { id: 361, day: 6, en: "We are doing a bench test with the EPS system.", ko: "EPS 시스템으로 벤치 테스트를 진행하고 있습니다." },
    { id: 362, day: 6, en: "The vehicle integration test is scheduled for next month.", ko: "차량 통합 테스트는 다음 달로 예정되어 있습니다." },
    { id: 363, day: 6, en: "The EMC test results are within the limit.", ko: "EMC 테스트 결과가 한도 내에 있습니다." },
    { id: 364, day: 6, en: "We passed the conducted emission test.", ko: "전도 방사 테스트를 통과했습니다." },
    { id: 365, day: 6, en: "The radiated immunity test needs to be repeated.", ko: "방사 내성 테스트를 반복해야 합니다." },
    { id: 366, day: 6, en: "The surge protection circuit is not functioning properly.", ko: "서지 보호 회로가 제대로 작동하지 않습니다." },
    { id: 367, day: 6, en: "The reverse polarity protection needs to be verified.", ko: "역극성 보호 기능을 검증해야 합니다." },
    { id: 368, day: 6, en: "The software watchdog timer is set to 10 milliseconds.", ko: "소프트웨어 워치독 타이머는 10ms로 설정되어 있습니다." },
    { id: 369, day: 6, en: "The fail-safe mode activates when the sensor fails.", ko: "센서 고장 시 페일세이프 모드가 활성화됩니다." },
    { id: 370, day: 6, en: "The ASIL D requirements must be fully met.", ko: "ASIL D 요구사항을 완전히 충족해야 합니다." }
);

// Day 7: NVH & 시험 평가 (NVH & Testing) - 371~440
SENTENCES.push(
    { id: 371, day: 7, en: "The vibration level exceeds the customer requirement.", ko: "진동 레벨이 고객 요구사항을 초과합니다." },
    { id: 372, day: 7, en: "We need to perform a modal analysis.", ko: "모달 해석을 수행해야 합니다." },
    { id: 373, day: 7, en: "The natural frequency of the housing is 1200 Hz.", ko: "하우징의 고유 진동수는 1200Hz입니다." },
    { id: 374, day: 7, en: "The acceleration sensor data shows a peak at 800 Hz.", ko: "가속도 센서 데이터에서 800Hz에 피크가 보입니다." },
    { id: 375, day: 7, en: "The noise is coming from the gear mesh frequency.", ko: "소음이 기어 치합 주파수에서 발생하고 있습니다." },
    { id: 376, day: 7, en: "We need to apply a damping treatment.", ko: "댐핑 처리를 적용해야 합니다." },
    { id: 377, day: 7, en: "The rubber isolation mount reduces vibration by 60%.", ko: "고무 방진 마운트가 진동을 60% 감소시킵니다." },
    { id: 378, day: 7, en: "Can we see the waterfall diagram?", ko: "워터폴 다이어그램을 볼 수 있나요?" },
    { id: 379, day: 7, en: "The Campbell diagram shows the critical speed.", ko: "캠벨 다이어그램에 임계 속도가 나타납니다." },
    { id: 380, day: 7, en: "Let me show you the FFT analysis results.", ko: "FFT 분석 결과를 보여드리겠습니다." },
    { id: 381, day: 7, en: "The order tracking analysis reveals a 6th order issue.", ko: "오더 트래킹 분석에서 6차 문제가 드러납니다." },
    { id: 382, day: 7, en: "We measured the sound pressure level at 1 meter distance.", ko: "1미터 거리에서 음압 레벨을 측정했습니다." },
    { id: 383, day: 7, en: "The A-weighted noise level is 42 dB.", ko: "A 가중 소음 레벨은 42dB입니다." },
    { id: 384, day: 7, en: "The test was conducted in a semi-anechoic chamber.", ko: "반무향실에서 테스트를 수행했습니다." },
    { id: 385, day: 7, en: "The environmental temperature during testing was 25 degrees.", ko: "테스트 중 환경 온도는 25도였습니다." },
    { id: 386, day: 7, en: "The durability test runs for 1000 hours continuously.", ko: "내구 테스트는 1000시간 연속으로 진행됩니다." },
    { id: 387, day: 7, en: "The thermal cycling test range is minus 40 to plus 85.", ko: "열 사이클 테스트 범위는 -40도에서 +85도입니다." },
    { id: 388, day: 7, en: "The humidity test follows the IEC standard.", ko: "습도 테스트는 IEC 표준을 따릅니다." },
    { id: 389, day: 7, en: "We ran the salt spray test for 96 hours.", ko: "염수 분무 테스트를 96시간 진행했습니다." },
    { id: 390, day: 7, en: "The vibration test profile follows the customer specification.", ko: "진동 테스트 프로파일은 고객 사양을 따릅니다." },
    { id: 391, day: 7, en: "The shock test resulted in a crack on the housing.", ko: "충격 테스트에서 하우징에 균열이 발생했습니다." },
    { id: 392, day: 7, en: "The power consumption at idle is below 500 milliamps.", ko: "유휴 시 소비 전력은 500mA 이하입니다." },
    { id: 393, day: 7, en: "The standby current draw must be less than 1 milliamp.", ko: "대기 전류 소모는 1mA 미만이어야 합니다." },
    { id: 394, day: 7, en: "The load test simulates real-world driving conditions.", ko: "부하 테스트는 실제 주행 조건을 시뮬레이션합니다." },
    { id: 395, day: 7, en: "The test bench needs calibration.", ko: "테스트 벤치 교정이 필요합니다." },
    { id: 396, day: 7, en: "The data acquisition system recorded at 10 kHz sampling rate.", ko: "데이터 수집 시스템에서 10kHz 샘플링으로 기록했습니다." },
    { id: 397, day: 7, en: "The test result shows 3 sigma variation.", ko: "테스트 결과에서 3 시그마 편차가 보입니다." },
    { id: 398, day: 7, en: "We need a Cpk value of at least 1.67.", ko: "Cpk 값이 최소 1.67이어야 합니다." },
    { id: 399, day: 7, en: "The measurement uncertainty is plus or minus 2%.", ko: "측정 불확도는 ±2%입니다." },
    { id: 400, day: 7, en: "Let me share the test report with the team.", ko: "팀에 테스트 리포트를 공유하겠습니다." },
    { id: 401, day: 7, en: "The prototype passed all functional tests.", ko: "프로토타입이 모든 기능 테스트를 통과했습니다." },
    { id: 402, day: 7, en: "We identified a resonance issue at 400 RPM.", ko: "400 RPM에서 공진 문제를 발견했습니다." },
    { id: 403, day: 7, en: "The structural analysis shows stress concentration here.", ko: "구조 해석에서 여기에 응력 집중이 나타납니다." },
    { id: 404, day: 7, en: "The fatigue life is estimated at 10 million cycles.", ko: "피로 수명은 천만 사이클로 추정됩니다." },
    { id: 405, day: 7, en: "The safety factor is 1.5 for this component.", ko: "이 부품의 안전 계수는 1.5입니다." },
    { id: 406, day: 7, en: "We need to increase the wall thickness by 0.3mm.", ko: "벽 두께를 0.3mm 증가시켜야 합니다." },
    { id: 407, day: 7, en: "The weight reduction target is 200 grams.", ko: "경량화 목표는 200그램입니다." },
    { id: 408, day: 7, en: "The acoustic test vehicle is ready for evaluation.", ko: "음향 테스트 차량이 평가 준비되었습니다." },
    { id: 409, day: 7, en: "The road noise test will be conducted on the proving ground.", ko: "로드 노이즈 테스트는 주행 시험장에서 수행합니다." },
    { id: 410, day: 7, en: "The judder phenomenon occurs during low speed turning.", ko: "저속 선회 시 저더 현상이 발생합니다." },
    { id: 411, day: 7, en: "The rattle noise appears at cold start.", ko: "냉간 시동 시 래틀 소음이 발생합니다." },
    { id: 412, day: 7, en: "We need to add grease to the worm gear.", ko: "웜 기어에 그리스를 추가해야 합니다." },
    { id: 413, day: 7, en: "The gear backlash is 0.05mm.", ko: "기어 백래시는 0.05mm입니다." },
    { id: 414, day: 7, en: "The HALT test revealed a weak point in the solder joint.", ko: "HALT 테스트에서 솔더 접합부의 취약점이 드러났습니다." },
    { id: 415, day: 7, en: "The HASS screening criteria need to be defined.", ko: "HASS 스크리닝 기준을 정의해야 합니다." },
    { id: 416, day: 7, en: "The sample size for validation is 30 units.", ko: "검증을 위한 샘플 수는 30개입니다." },
    { id: 417, day: 7, en: "The first article inspection report is complete.", ko: "초도품 검사 보고서가 완료되었습니다." },
    { id: 418, day: 7, en: "The dimensional inspection uses a CMM machine.", ko: "치수 검사에 CMM 장비를 사용합니다." },
    { id: 419, day: 7, en: "The surface roughness must be Ra 0.8 or better.", ko: "표면 거칠기는 Ra 0.8 이하이어야 합니다." },
    { id: 420, day: 7, en: "The hardness test result is HRC 58.", ko: "경도 테스트 결과는 HRC 58입니다." },
    { id: 421, day: 7, en: "The tensile strength of this material is 600 MPa.", ko: "이 소재의 인장 강도는 600MPa입니다." },
    { id: 422, day: 7, en: "We are using aluminum die-cast for the housing.", ko: "하우징에 알루미늄 다이캐스트를 사용하고 있습니다." },
    { id: 423, day: 7, en: "The plastic material is PA66 with 30% glass fiber.", ko: "플라스틱 소재는 PA66 유리섬유 30% 충전입니다." },
    { id: 424, day: 7, en: "The creep test under sustained load is ongoing.", ko: "지속 하중 하의 크리프 테스트가 진행 중입니다." },
    { id: 425, day: 7, en: "The corrosion test follows the GM standard.", ko: "부식 테스트는 GM 표준을 따릅니다." },
    { id: 426, day: 7, en: "The flammability rating must be UL94 V-0.", ko: "가연성 등급은 UL94 V-0이어야 합니다." },
    { id: 427, day: 7, en: "The RoHS compliance is mandatory for all materials.", ko: "모든 소재에 RoHS 준수가 의무입니다." },
    { id: 428, day: 7, en: "We received the PPAP documentation from the supplier.", ko: "공급업체로부터 PPAP 문서를 받았습니다." },
    { id: 429, day: 7, en: "The SPC data shows the process is under control.", ko: "SPC 데이터에서 공정이 관리 상태임을 보여줍니다." },
    { id: 430, day: 7, en: "The test equipment needs annual calibration.", ko: "테스트 장비는 연간 교정이 필요합니다." },
    { id: 431, day: 7, en: "The measurement system analysis is required before production.", ko: "양산 전 측정 시스템 분석이 필요합니다." },
    { id: 432, day: 7, en: "The GR&R result must be below 10%.", ko: "GR&R 결과가 10% 이하이어야 합니다." },
    { id: 433, day: 7, en: "The end-of-line test covers all safety-critical functions.", ko: "EOL 테스트가 모든 안전 핵심 기능을 커버합니다." },
    { id: 434, day: 7, en: "The functional safety assessment is in progress.", ko: "기능 안전 평가가 진행 중입니다." },
    { id: 435, day: 7, en: "The FMEA needs to be updated with the new failure mode.", ko: "새로운 고장 모드로 FMEA를 업데이트해야 합니다." },
    { id: 436, day: 7, en: "The fault tree analysis indicates a design weakness.", ko: "고장 트리 분석에서 설계 취약점이 나타납니다." },
    { id: 437, day: 7, en: "The reliability target is 10 PPM or below.", ko: "신뢰성 목표는 10 PPM 이하입니다." },
    { id: 438, day: 7, en: "The warranty claim rate for EPS is 0.1%.", ko: "EPS 보증 클레임 비율은 0.1%입니다." },
    { id: 439, day: 7, en: "The field return analysis shows a connector issue.", ko: "필드 리턴 분석에서 커넥터 문제가 나타납니다." },
    { id: 440, day: 7, en: "The root cause was identified as a manufacturing defect.", ko: "근본 원인이 제조 결함으로 확인되었습니다." }
);

DAY_NAMES[6] = "EPS 모터 & 제어기 기술";
DAY_NAMES[7] = "NVH & 시험 평가";
DAY_NAMES_EN[6] = "EPS Motor & Controller Technical";
DAY_NAMES_EN[7] = "NVH & Testing";
