// 🏥 병원 직원 영어 마스터 - 275문장 (5일 과정, 피부과 특화)
const SENTENCES_HOSPITAL = [
    // ===== Day 1: 접수 & 예약 확인 (Reception & Appointments) — 55문장 =====
    { id: 1, day: 1, en: "Hello, welcome to our clinic.", ko: "안녕하세요, 저희 클리닉에 오신 것을 환영합니다." },
    { id: 2, day: 1, en: "Do you have an appointment?", ko: "예약하셨나요?" },
    { id: 3, day: 1, en: "May I have your name, please?", ko: "성함을 알려주시겠어요?" },
    { id: 4, day: 1, en: "Could you spell your last name for me?", ko: "성을 스펠링으로 알려주시겠어요?" },
    { id: 5, day: 1, en: "What time is your appointment?", ko: "예약 시간이 몇 시인가요?" },
    { id: 6, day: 1, en: "I can see your appointment. Please have a seat.", ko: "예약 확인됐습니다. 자리에 앉아 기다려주세요." },
    { id: 7, day: 1, en: "I'm sorry, I don't see your reservation.", ko: "죄송합니다, 예약이 확인되지 않습니다." },
    { id: 8, day: 1, en: "Would you like to make an appointment?", ko: "예약하시겠어요?" },
    { id: 9, day: 1, en: "Is this your first visit?", ko: "처음 방문이신가요?" },
    { id: 10, day: 1, en: "Have you been here before?", ko: "전에 오신 적이 있으신가요?" },
    { id: 11, day: 1, en: "Please fill out this registration form.", ko: "이 접수 양식을 작성해 주세요." },
    { id: 12, day: 1, en: "Could you fill out this questionnaire?", ko: "이 설문지를 작성해 주시겠어요?" },
    { id: 13, day: 1, en: "Please write down your contact number.", ko: "연락처를 적어주세요." },
    { id: 14, day: 1, en: "Do you have any allergies?", ko: "알레르기가 있으신가요?" },
    { id: 15, day: 1, en: "Are you currently taking any medication?", ko: "현재 복용 중인 약이 있으신가요?" },
    { id: 16, day: 1, en: "Have you had any skin treatments before?", ko: "이전에 피부 시술을 받으신 적이 있나요?" },
    { id: 17, day: 1, en: "Which treatment are you interested in?", ko: "어떤 시술에 관심이 있으신가요?" },
    { id: 18, day: 1, en: "The doctor will see you shortly.", ko: "곧 의사 선생님이 진료하실 겁니다." },
    { id: 19, day: 1, en: "Please wait in the waiting area.", ko: "대기실에서 기다려주세요." },
    { id: 20, day: 1, en: "Your waiting time is about 15 minutes.", ko: "대기 시간은 약 15분 정도입니다." },
    { id: 21, day: 1, en: "We're running a little behind schedule.", ko: "일정이 조금 밀리고 있습니다." },
    { id: 22, day: 1, en: "Thank you for your patience.", ko: "기다려주셔서 감사합니다." },
    { id: 23, day: 1, en: "May I see your passport, please?", ko: "여권을 보여주시겠어요?" },
    { id: 24, day: 1, en: "We need a copy of your ID for our records.", ko: "기록을 위해 신분증 사본이 필요합니다." },
    { id: 25, day: 1, en: "Please take a number and wait to be called.", ko: "번호표를 뽑고 호출될 때까지 기다려주세요." },
    { id: 26, day: 1, en: "Your number will be called on the screen.", ko: "화면에 번호가 호출됩니다." },
    { id: 27, day: 1, en: "Could you sign here, please?", ko: "여기에 서명해 주시겠어요?" },
    { id: 28, day: 1, en: "I need your consent for the treatment.", ko: "시술 동의서가 필요합니다." },
    { id: 29, day: 1, en: "Please read this consent form carefully.", ko: "이 동의서를 꼼꼼히 읽어주세요." },
    { id: 30, day: 1, en: "Do you understand the possible side effects?", ko: "발생 가능한 부작용을 이해하셨나요?" },
    { id: 31, day: 1, en: "We can register your car for parking.", ko: "주차 등록을 해드릴 수 있습니다." },
    { id: 32, day: 1, en: "Could you give me your license plate number?", ko: "차 번호를 알려주시겠어요?" },
    { id: 33, day: 1, en: "Parking is free for our patients.", ko: "환자분들은 주차 무료입니다." },
    { id: 34, day: 1, en: "Parking is validated for up to two hours.", ko: "2시간까지 주차 인증이 됩니다." },
    { id: 35, day: 1, en: "The restroom is down the hall on the right.", ko: "화장실은 복도 끝 오른쪽에 있습니다." },
    { id: 36, day: 1, en: "Would you like something to drink while you wait?", ko: "기다리시는 동안 음료를 드릴까요?" },
    { id: 37, day: 1, en: "We have water, tea, and coffee available.", ko: "물, 차, 커피가 준비되어 있습니다." },
    { id: 38, day: 1, en: "You can connect to our Wi-Fi.", ko: "저희 와이파이에 접속하실 수 있어요." },
    { id: 39, day: 1, en: "The Wi-Fi password is on the wall.", ko: "와이파이 비밀번호는 벽에 적혀 있습니다." },
    { id: 40, day: 1, en: "We'll call your name when we're ready.", ko: "준비되면 성함을 불러드리겠습니다." },
    { id: 41, day: 1, en: "We accept walk-in patients, but there may be a wait.", ko: "예약 없이도 진료 가능하지만, 대기가 있을 수 있습니다." },
    { id: 42, day: 1, en: "I'm sorry, the doctor is fully booked today.", ko: "죄송합니다, 오늘 예약이 다 찼습니다." },
    { id: 43, day: 1, en: "The earliest available slot is next Monday.", ko: "가장 가까운 예약 가능 시간은 다음 월요일입니다." },
    { id: 44, day: 1, en: "Would you prefer a morning or afternoon appointment?", ko: "오전과 오후 중 어떤 시간이 좋으세요?" },
    { id: 45, day: 1, en: "Can I book you for 2 PM on Thursday?", ko: "목요일 오후 2시로 예약해 드릴까요?" },
    { id: 46, day: 1, en: "We'll send you a confirmation by text message.", ko: "문자로 예약 확인을 보내드리겠습니다." },
    { id: 47, day: 1, en: "Please arrive 10 minutes before your appointment.", ko: "예약 시간 10분 전에 도착해 주세요." },
    { id: 48, day: 1, en: "We require 24 hours' notice to cancel.", ko: "취소는 24시간 전에 알려주셔야 합니다." },
    { id: 49, day: 1, en: "Would you like to reschedule your appointment?", ko: "예약을 변경하시겠어요?" },
    { id: 50, day: 1, en: "Your appointment has been confirmed.", ko: "예약이 확정되었습니다." },
    { id: 51, day: 1, en: "Please bring your previous medical records.", ko: "이전 진료 기록을 가져와 주세요." },
    { id: 52, day: 1, en: "We will take some photos for your file.", ko: "차트를 위해 사진을 몇 장 찍겠습니다." },
    { id: 53, day: 1, en: "Could you remove your makeup before the consultation?", ko: "상담 전에 화장을 지워주시겠어요?" },
    { id: 54, day: 1, en: "There is a makeup removal station over there.", ko: "저쪽에 클렌징 공간이 있습니다." },
    { id: 55, day: 1, en: "The consultation will take about 20 minutes.", ko: "상담은 약 20분 정도 소요됩니다." },

    // ===== Day 2: 보험 & 서류 안내 (Insurance & Documentation) — 55문장 =====
    { id: 56, day: 2, en: "Do you have health insurance?", ko: "건강보험이 있으신가요?" },
    { id: 57, day: 2, en: "May I see your insurance card?", ko: "보험 카드를 보여주시겠어요?" },
    { id: 58, day: 2, en: "Which insurance company are you with?", ko: "어떤 보험회사 가입자이신가요?" },
    { id: 59, day: 2, en: "Is this covered by your insurance?", ko: "이 시술은 보험 적용이 되나요?" },
    { id: 60, day: 2, en: "Unfortunately, cosmetic procedures are not covered.", ko: "죄송하지만, 미용 시술은 보험 적용이 안 됩니다." },
    { id: 61, day: 2, en: "This treatment is classified as cosmetic.", ko: "이 시술은 미용 목적으로 분류됩니다." },
    { id: 62, day: 2, en: "Medical treatments are covered by insurance.", ko: "의료 목적 치료는 보험이 적용됩니다." },
    { id: 63, day: 2, en: "You'll need to pay the full amount upfront.", ko: "전액을 선결제하셔야 합니다." },
    { id: 64, day: 2, en: "We can issue a receipt for your insurance claim.", ko: "보험 청구용 영수증을 발행해 드릴 수 있습니다." },
    { id: 65, day: 2, en: "Do you have travel insurance?", ko: "여행자 보험이 있으신가요?" },
    { id: 66, day: 2, en: "We can provide a medical certificate if needed.", ko: "필요하시면 진단서를 발행해 드릴 수 있습니다." },
    { id: 67, day: 2, en: "The certificate will be ready in about three days.", ko: "진단서는 약 3일 후에 준비됩니다." },
    { id: 68, day: 2, en: "Here is a breakdown of the treatment costs.", ko: "시술 비용 내역서입니다." },
    { id: 69, day: 2, en: "The consultation fee is separate from the treatment.", ko: "상담료는 시술비와 별도입니다." },
    { id: 70, day: 2, en: "I'll explain the pricing before we proceed.", ko: "진행하기 전에 가격을 안내해 드리겠습니다." },
    { id: 71, day: 2, en: "We offer package discounts for multiple sessions.", ko: "여러 회차 패키지 할인을 제공합니다." },
    { id: 72, day: 2, en: "Would you like to see our price list?", ko: "가격표를 보시겠어요?" },
    { id: 73, day: 2, en: "We have a special promotion this month.", ko: "이번 달 특별 프로모션이 있습니다." },
    { id: 74, day: 2, en: "Do you have any questions about the procedure?", ko: "시술에 대해 궁금한 점이 있으신가요?" },
    { id: 75, day: 2, en: "The doctor will explain everything during the consultation.", ko: "상담 시 의사 선생님이 모두 설명해 드릴 겁니다." },
    { id: 76, day: 2, en: "Here are the before and after photos of similar treatments.", ko: "비슷한 시술의 전후 사진입니다." },
    { id: 77, day: 2, en: "Results may vary depending on your skin type.", ko: "피부 유형에 따라 결과가 다를 수 있습니다." },
    { id: 78, day: 2, en: "You may need multiple sessions for best results.", ko: "최상의 결과를 위해 여러 회 시술이 필요할 수 있습니다." },
    { id: 79, day: 2, en: "We recommend a series of three treatments.", ko: "3회 시술 코스를 권장합니다." },
    { id: 80, day: 2, en: "Each session should be about four weeks apart.", ko: "각 시술은 약 4주 간격으로 진행해야 합니다." },
    { id: 81, day: 2, en: "Please bring this form on your next visit.", ko: "다음 방문 시 이 서류를 가져와 주세요." },
    { id: 82, day: 2, en: "We'll keep your records in our system.", ko: "귀하의 기록은 시스템에 보관됩니다." },
    { id: 83, day: 2, en: "Your medical information is kept confidential.", ko: "귀하의 의료 정보는 비밀이 보장됩니다." },
    { id: 84, day: 2, en: "Are you pregnant or breastfeeding?", ko: "임신 중이시거나 수유 중이신가요?" },
    { id: 85, day: 2, en: "Have you had any surgery recently?", ko: "최근에 수술을 받으신 적이 있나요?" },
    { id: 86, day: 2, en: "Do you have a history of keloid scarring?", ko: "켈로이드 흉터 이력이 있으신가요?" },
    { id: 87, day: 2, en: "Are you taking any blood thinners?", ko: "혈액 희석제를 복용 중이신가요?" },
    { id: 88, day: 2, en: "Please let us know if you have diabetes.", ko: "당뇨가 있으시면 알려주세요." },
    { id: 89, day: 2, en: "We need to check your skin condition first.", ko: "먼저 피부 상태를 확인해야 합니다." },
    { id: 90, day: 2, en: "The nurse will prepare you for the treatment.", ko: "간호사가 시술 준비를 도와드릴 겁니다." },
    { id: 91, day: 2, en: "Please change into this gown.", ko: "이 가운으로 갈아입어 주세요." },
    { id: 92, day: 2, en: "You can put your belongings in this locker.", ko: "소지품은 이 사물함에 넣어주세요." },
    { id: 93, day: 2, en: "Here is the key to your locker.", ko: "사물함 열쇠입니다." },
    { id: 94, day: 2, en: "The changing room is right over there.", ko: "탈의실은 바로 저쪽에 있습니다." },
    { id: 95, day: 2, en: "Do you have any preference for the doctor?", ko: "선호하시는 의사 선생님이 있으신가요?" },
    { id: 96, day: 2, en: "Dr. Park specializes in laser treatments.", ko: "박 선생님은 레이저 시술 전문이십니다." },
    { id: 97, day: 2, en: "I'll check the doctor's schedule for you.", ko: "의사 선생님 스케줄을 확인해 드리겠습니다." },
    { id: 98, day: 2, en: "Please have a seat in consultation room 2.", ko: "2번 상담실에 앉아 기다려주세요." },
    { id: 99, day: 2, en: "The doctor is ready to see you now.", ko: "의사 선생님이 지금 진료를 보실 준비가 되셨습니다." },
    { id: 100, day: 2, en: "When was your last visit to a dermatologist?", ko: "마지막으로 피부과에 방문하신 게 언제인가요?" },
    { id: 101, day: 2, en: "Could you describe your symptoms?", ko: "증상을 설명해 주시겠어요?" },
    { id: 102, day: 2, en: "How long have you had this condition?", ko: "이 증상이 얼마나 오래됐나요?" },
    { id: 103, day: 2, en: "Does it itch or hurt?", ko: "가렵거나 아프신가요?" },
    { id: 104, day: 2, en: "I'll apply some numbing cream before the procedure.", ko: "시술 전에 마취 크림을 발라드리겠습니다." },
    { id: 105, day: 2, en: "The numbing cream will take about 30 minutes to work.", ko: "마취 크림이 효과를 나타내는 데 약 30분이 걸립니다." },
    { id: 106, day: 2, en: "Please let us know if you feel any discomfort.", ko: "불편하시면 말씀해 주세요." },
    { id: 107, day: 2, en: "We take patient safety very seriously.", ko: "저희는 환자 안전을 매우 중요하게 생각합니다." },
    { id: 108, day: 2, en: "All our equipment is sterilized.", ko: "모든 장비는 멸균 처리되어 있습니다." },
    { id: 109, day: 2, en: "Our doctors are all board-certified dermatologists.", ko: "저희 의사들은 모두 피부과 전문의입니다." },
    { id: 110, day: 2, en: "We use FDA-approved products.", ko: "저희는 FDA 승인 제품을 사용합니다." },

    // ===== Day 3: 시술 & 진료 안내 (Treatments & Procedures) — 55문장 =====
    { id: 111, day: 3, en: "We offer a variety of laser treatments.", ko: "다양한 레이저 시술을 제공합니다." },
    { id: 112, day: 3, en: "This laser targets pigmentation and dark spots.", ko: "이 레이저는 색소침착과 잡티를 치료합니다." },
    { id: 113, day: 3, en: "Would you like to try our skin brightening treatment?", ko: "미백 시술을 해보시겠어요?" },
    { id: 114, day: 3, en: "This treatment helps with acne scars.", ko: "이 시술은 여드름 흉터에 효과적입니다." },
    { id: 115, day: 3, en: "We can reduce your pores with this procedure.", ko: "이 시술로 모공을 줄일 수 있습니다." },
    { id: 116, day: 3, en: "Botox can help with fine lines and wrinkles.", ko: "보톡스는 잔주름과 주름 개선에 도움이 됩니다." },
    { id: 117, day: 3, en: "Filler can add volume to your cheeks and lips.", ko: "필러로 볼과 입술에 볼륨을 줄 수 있습니다." },
    { id: 118, day: 3, en: "The treatment takes about 30 minutes.", ko: "시술은 약 30분 정도 소요됩니다." },
    { id: 119, day: 3, en: "You may feel a slight tingling sensation.", ko: "약간의 따끔거림을 느끼실 수 있습니다." },
    { id: 120, day: 3, en: "Please keep your eyes closed during the procedure.", ko: "시술 중에는 눈을 감아주세요." },
    { id: 121, day: 3, en: "I'll put these protective goggles on for you.", ko: "보호용 고글을 씌워드리겠습니다." },
    { id: 122, day: 3, en: "Are you comfortable?", ko: "편하신가요?" },
    { id: 123, day: 3, en: "Let me know if you need a break.", ko: "쉬고 싶으시면 말씀해 주세요." },
    { id: 124, day: 3, en: "We're about halfway done.", ko: "절반 정도 진행됐습니다." },
    { id: 125, day: 3, en: "You're doing great.", ko: "잘하고 계세요." },
    { id: 126, day: 3, en: "Almost done, just a little bit more.", ko: "거의 다 됐습니다, 조금만 더요." },
    { id: 127, day: 3, en: "The procedure is finished now.", ko: "시술이 끝났습니다." },
    { id: 128, day: 3, en: "Your skin looks really good.", ko: "피부가 정말 좋아 보이세요." },
    { id: 129, day: 3, en: "There might be some redness for a few hours.", ko: "몇 시간 동안 붉은기가 있을 수 있습니다." },
    { id: 130, day: 3, en: "Swelling is normal and will go down in a few days.", ko: "부기는 정상이며 며칠 내에 빠집니다." },
    { id: 131, day: 3, en: "Avoid direct sunlight for at least one week.", ko: "최소 1주일 동안 직사광선을 피해주세요." },
    { id: 132, day: 3, en: "Please apply sunscreen daily.", ko: "매일 선크림을 발라주세요." },
    { id: 133, day: 3, en: "Do not wash your face for the next 6 hours.", ko: "이후 6시간 동안 세안을 하지 마세요." },
    { id: 134, day: 3, en: "Avoid alcohol and spicy food for 48 hours.", ko: "48시간 동안 음주와 매운 음식을 피해주세요." },
    { id: 135, day: 3, en: "Don't exercise intensely for three days.", ko: "3일 동안 격렬한 운동을 삼가주세요." },
    { id: 136, day: 3, en: "Don't touch or scratch the treated area.", ko: "시술 부위를 만지거나 긁지 마세요." },
    { id: 137, day: 3, en: "Apply the ointment twice a day.", ko: "하루에 두 번 연고를 발라주세요." },
    { id: 138, day: 3, en: "Here are your aftercare instructions.", ko: "시술 후 관리 안내서입니다." },
    { id: 139, day: 3, en: "Would you like a chemical peel?", ko: "케미컬 필링을 하시겠어요?" },
    { id: 140, day: 3, en: "This peel removes dead skin cells.", ko: "이 필링은 각질을 제거합니다." },
    { id: 141, day: 3, en: "Hydration is important after this treatment.", ko: "이 시술 후에는 수분 보충이 중요합니다." },
    { id: 142, day: 3, en: "We also offer thread lifting.", ko: "실 리프팅도 제공합니다." },
    { id: 143, day: 3, en: "Would you like to add a vitamin injection?", ko: "비타민 주사를 추가하시겠어요?" },
    { id: 144, day: 3, en: "The IV drip will take about 40 minutes.", ko: "수액은 약 40분 정도 소요됩니다." },
    { id: 145, day: 3, en: "You can relax while the IV is being administered.", ko: "수액을 맞는 동안 편히 쉬세요." },
    { id: 146, day: 3, en: "This cream will help with recovery.", ko: "이 크림이 회복에 도움이 됩니다." },
    { id: 147, day: 3, en: "You should see improvements within two weeks.", ko: "2주 내에 개선 효과를 보실 수 있습니다." },
    { id: 148, day: 3, en: "Full results will be visible after about a month.", ko: "전체 결과는 약 한 달 후에 나타납니다." },
    { id: 149, day: 3, en: "Would you like to see the treated area?", ko: "시술 부위를 보시겠어요?" },
    { id: 150, day: 3, en: "Here is a mirror.", ko: "거울 여기 있습니다." },
    { id: 151, day: 3, en: "I'll take some photos for comparison.", ko: "비교를 위해 사진을 찍겠습니다." },
    { id: 152, day: 3, en: "If you notice anything unusual, please contact us.", ko: "이상한 점이 있으시면 연락해 주세요." },
    { id: 153, day: 3, en: "Do you have any concerns about the procedure?", ko: "시술에 대해 걱정되는 점이 있으신가요?" },
    { id: 154, day: 3, en: "Is there anything else I can help you with?", ko: "더 도와드릴 일이 있으신가요?" },
    { id: 155, day: 3, en: "You can get dressed now.", ko: "이제 옷을 입으셔도 됩니다." },
    { id: 156, day: 3, en: "Would you like some cooling down time?", ko: "쿨링 시간을 가지시겠어요?" },
    { id: 157, day: 3, en: "We'll apply a soothing mask for you.", ko: "진정 마스크를 씌워드리겠습니다." },
    { id: 158, day: 3, en: "Please stay for 10 more minutes for observation.", ko: "경과 관찰을 위해 10분만 더 계셔주세요." },
    { id: 159, day: 3, en: "I'll apply some calming serum.", ko: "진정 세럼을 발라드리겠습니다." },
    { id: 160, day: 3, en: "Please use only gentle, fragrance-free products.", ko: "순하고 무향 제품만 사용해 주세요." },
    { id: 161, day: 3, en: "Avoid makeup for the next 24 hours.", ko: "24시간 동안 화장을 피해주세요." },
    { id: 162, day: 3, en: "Your skin may peel slightly. That's normal.", ko: "피부가 약간 벗겨질 수 있습니다. 정상입니다." },
    { id: 163, day: 3, en: "Ice packs can help reduce the swelling.", ko: "아이스팩이 부기를 줄이는 데 도움이 됩니다." },
    { id: 164, day: 3, en: "Please don't go to saunas or steam rooms this week.", ko: "이번 주에는 사우나나 찜질방을 가지 마세요." },
    { id: 165, day: 3, en: "I'll prescribe some medication for you.", ko: "약을 처방해 드리겠습니다." },

    // ===== Day 4: 결제 & 택스프리 (Payment & Tax-free) — 55문장 =====
    { id: 166, day: 4, en: "Please proceed to the payment counter.", ko: "결제 창구로 가주세요." },
    { id: 167, day: 4, en: "The total amount is 500,000 won.", ko: "총 금액은 50만 원입니다." },
    { id: 168, day: 4, en: "How would you like to pay?", ko: "어떻게 결제하시겠어요?" },
    { id: 169, day: 4, en: "We accept cash, credit card, and mobile payment.", ko: "현금, 신용카드, 모바일 결제가 가능합니다." },
    { id: 170, day: 4, en: "Would you like to pay in full or by installment?", ko: "일시불로 하시겠어요, 할부로 하시겠어요?" },
    { id: 171, day: 4, en: "You can pay in installments up to 12 months.", ko: "최대 12개월까지 할부가 가능합니다." },
    { id: 172, day: 4, en: "Please insert your card here.", ko: "카드를 여기에 꽂아주세요." },
    { id: 173, day: 4, en: "Could you enter your PIN, please?", ko: "비밀번호를 입력해 주시겠어요?" },
    { id: 174, day: 4, en: "Your payment has been processed successfully.", ko: "결제가 완료되었습니다." },
    { id: 175, day: 4, en: "Here is your receipt.", ko: "영수증입니다." },
    { id: 176, day: 4, en: "Would you like a printed or digital receipt?", ko: "종이 영수증과 전자 영수증 중 어떤 걸 원하세요?" },
    { id: 177, day: 4, en: "I'm sorry, your card was declined.", ko: "죄송합니다, 카드가 거절되었습니다." },
    { id: 178, day: 4, en: "Would you like to try a different card?", ko: "다른 카드로 시도해 보시겠어요?" },
    { id: 179, day: 4, en: "We also accept foreign credit cards.", ko: "해외 신용카드도 사용 가능합니다." },
    { id: 180, day: 4, en: "The currency conversion will be done automatically.", ko: "환율 변환은 자동으로 처리됩니다." },
    { id: 181, day: 4, en: "Would you like to pay in Korean won or your local currency?", ko: "한국 원화로 결제하시겠어요, 현지 통화로 하시겠어요?" },
    { id: 182, day: 4, en: "I'm sorry, but tax-free is not available for this treatment.", ko: "죄송합니다, 이 시술은 택스프리가 불가합니다." },
    { id: 183, day: 4, en: "Tax-free applies only to product purchases.", ko: "택스프리는 제품 구매에만 적용됩니다." },
    { id: 184, day: 4, en: "You can get a tax refund at the airport.", ko: "공항에서 세금 환급을 받으실 수 있습니다." },
    { id: 185, day: 4, en: "Please keep this receipt for your tax refund.", ko: "택스프리 환급을 위해 이 영수증을 보관해 주세요." },
    { id: 186, day: 4, en: "You need your passport for the tax-free process.", ko: "택스프리 처리에 여권이 필요합니다." },
    { id: 187, day: 4, en: "I'll process the tax-free form for you.", ko: "택스프리 서류를 처리해 드리겠습니다." },
    { id: 188, day: 4, en: "The tax refund is approximately 10%.", ko: "세금 환급은 약 10%입니다." },
    { id: 189, day: 4, en: "Please sign on the tax-free document.", ko: "택스프리 서류에 서명해 주세요." },
    { id: 190, day: 4, en: "We have skincare products available for purchase.", ko: "구매 가능한 스킨케어 제품이 있습니다." },
    { id: 191, day: 4, en: "This serum is recommended after your treatment.", ko: "이 세럼은 시술 후에 사용하시길 권장합니다." },
    { id: 192, day: 4, en: "Would you like to buy the aftercare kit?", ko: "사후 관리 키트를 구매하시겠어요?" },
    { id: 193, day: 4, en: "This sunscreen is specially formulated for sensitive skin.", ko: "이 선크림은 민감한 피부용으로 특별히 제조되었습니다." },
    { id: 194, day: 4, en: "We're offering a bundle discount today.", ko: "오늘은 세트 할인을 제공하고 있습니다." },
    { id: 195, day: 4, en: "You saved 30,000 won with today's discount.", ko: "오늘 할인으로 3만 원을 절약하셨습니다." },
    { id: 196, day: 4, en: "Would you like to purchase a gift card?", ko: "상품권을 구매하시겠어요?" },
    { id: 197, day: 4, en: "We can ship products to your country.", ko: "제품을 귀국으로 배송해 드릴 수 있습니다." },
    { id: 198, day: 4, en: "Shipping usually takes 5 to 7 business days.", ko: "배송은 보통 영업일 기준 5~7일 소요됩니다." },
    { id: 199, day: 4, en: "Here is a bag for your products.", ko: "제품 담을 봉투입니다." },
    { id: 200, day: 4, en: "Do you need a detailed invoice?", ko: "상세 영수증이 필요하신가요?" },
    { id: 201, day: 4, en: "I'll email the invoice to you.", ko: "영수증을 이메일로 보내드리겠습니다." },
    { id: 202, day: 4, en: "Could I have your email address?", ko: "이메일 주소를 알려주시겠어요?" },
    { id: 203, day: 4, en: "We have a membership program with special benefits.", ko: "특별 혜택이 있는 멤버십 프로그램이 있습니다." },
    { id: 204, day: 4, en: "Would you like to sign up for our membership?", ko: "멤버십에 가입하시겠어요?" },
    { id: 205, day: 4, en: "Members get 10% off on all treatments.", ko: "회원은 모든 시술에서 10% 할인을 받습니다." },
    { id: 206, day: 4, en: "You've earned loyalty points from today's visit.", ko: "오늘 방문으로 적립 포인트가 쌓였습니다." },
    { id: 207, day: 4, en: "Your points can be used on your next visit.", ko: "적립 포인트는 다음 방문 시 사용 가능합니다." },
    { id: 208, day: 4, en: "Is there anything else you'd like to purchase?", ko: "더 구매하실 것이 있으신가요?" },
    { id: 209, day: 4, en: "We provide free samples with every purchase.", ko: "구매 시 무료 샘플을 제공합니다." },
    { id: 210, day: 4, en: "Here are your free samples.", ko: "무료 샘플입니다." },
    { id: 211, day: 4, en: "A deposit is required for future bookings.", ko: "향후 예약에는 보증금이 필요합니다." },
    { id: 212, day: 4, en: "The deposit is non-refundable if canceled within 24 hours.", ko: "24시간 이내 취소 시 보증금은 환불되지 않습니다." },
    { id: 213, day: 4, en: "We'll apply today's deposit to your next treatment.", ko: "오늘의 보증금은 다음 시술에 적용됩니다." },
    { id: 214, day: 4, en: "Here's your change.", ko: "거스름돈입니다." },
    { id: 215, day: 4, en: "Would you like to round up to donate?", ko: "반올림하여 기부하시겠어요?" },
    { id: 216, day: 4, en: "Thank you for your payment.", ko: "결제해 주셔서 감사합니다." },
    { id: 217, day: 4, en: "You can review your billing details on our app.", ko: "저희 앱에서 결제 내역을 확인하실 수 있습니다." },
    { id: 218, day: 4, en: "Please download our clinic app for easy booking.", ko: "편리한 예약을 위해 클리닉 앱을 다운로드해 주세요." },
    { id: 219, day: 4, en: "You can manage your appointments through the app.", ko: "앱을 통해 예약을 관리하실 수 있습니다." },
    { id: 220, day: 4, en: "We accept WeChat Pay and Alipay as well.", ko: "위챗페이와 알리페이도 사용 가능합니다." },

    // ===== Day 5: 재진 예약 & 일반 안내 (Follow-up & General) — 55문장 =====
    { id: 221, day: 5, en: "Would you like to book a follow-up appointment?", ko: "다음 예약을 잡으시겠어요?" },
    { id: 222, day: 5, en: "We recommend a follow-up visit in two weeks.", ko: "2주 후 재진을 권장합니다." },
    { id: 223, day: 5, en: "When would be a good time for you?", ko: "어떤 시간이 편하신가요?" },
    { id: 224, day: 5, en: "Your next appointment is on March 10th at 3 PM.", ko: "다음 예약은 3월 10일 오후 3시입니다." },
    { id: 225, day: 5, en: "We'll send you a reminder before your appointment.", ko: "예약 전에 리마인더를 보내드리겠습니다." },
    { id: 226, day: 5, en: "Please don't hesitate to call if you have questions.", ko: "궁금한 점이 있으시면 언제든 전화해 주세요." },
    { id: 227, day: 5, en: "Our clinic hours are 10 AM to 7 PM, Monday through Saturday.", ko: "저희 클리닉 운영 시간은 월~토 오전 10시~오후 7시입니다." },
    { id: 228, day: 5, en: "We are closed on Sundays and public holidays.", ko: "일요일과 공휴일은 휴진입니다." },
    { id: 229, day: 5, en: "Here is our clinic's business card.", ko: "저희 클리닉 명함입니다." },
    { id: 230, day: 5, en: "You can reach us at this phone number.", ko: "이 전화번호로 연락하실 수 있습니다." },
    { id: 231, day: 5, en: "Feel free to contact us on KakaoTalk.", ko: "카카오톡으로도 연락 가능합니다." },
    { id: 232, day: 5, en: "We also have a LINE account for inquiries.", ko: "문의용 라인 계정도 있습니다." },
    { id: 233, day: 5, en: "Please leave us a review if you're satisfied.", ko: "만족하셨다면 리뷰를 남겨주세요." },
    { id: 234, day: 5, en: "Your feedback is very important to us.", ko: "고객님의 피드백은 저희에게 매우 중요합니다." },
    { id: 235, day: 5, en: "We hope to see you again soon.", ko: "곧 다시 뵙기를 바랍니다." },
    { id: 236, day: 5, en: "Thank you for choosing our clinic.", ko: "저희 클리닉을 선택해 주셔서 감사합니다." },
    { id: 237, day: 5, en: "Have a great rest of your day.", ko: "남은 하루 좋은 시간 보내세요." },
    { id: 238, day: 5, en: "Please take care and follow the aftercare instructions.", ko: "관리 잘 해주시고 사후 관리 지침을 따라주세요." },
    { id: 239, day: 5, en: "Let us know how your skin is doing next week.", ko: "다음 주에 피부 상태를 알려주세요." },
    { id: 240, day: 5, en: "If there is any unusual reaction, come back immediately.", ko: "이상 반응이 있으면 즉시 다시 방문해 주세요." },
    { id: 241, day: 5, en: "We can prescribe different medication if needed.", ko: "필요하면 다른 약을 처방해 드릴 수 있습니다." },
    { id: 242, day: 5, en: "You can pick up your prescription at any pharmacy.", ko: "처방전은 아무 약국에서 받으실 수 있습니다." },
    { id: 243, day: 5, en: "There is a pharmacy right next to our building.", ko: "저희 건물 바로 옆에 약국이 있습니다." },
    { id: 244, day: 5, en: "Take this medicine once a day after meals.", ko: "이 약은 하루 한 번 식후에 복용하세요." },
    { id: 245, day: 5, en: "Apply this ointment to the affected area morning and night.", ko: "이 연고를 아침저녁으로 환부에 발라주세요." },
    { id: 246, day: 5, en: "Please finish the entire course of antibiotics.", ko: "항생제는 처방된 기간 동안 모두 복용해 주세요." },
    { id: 247, day: 5, en: "This medication may cause drowsiness.", ko: "이 약은 졸음을 유발할 수 있습니다." },
    { id: 248, day: 5, en: "Avoid alcohol while taking this medication.", ko: "이 약 복용 중에는 음주를 삼가주세요." },
    { id: 249, day: 5, en: "Could you help me call a taxi?", ko: "택시를 불러주시겠어요?" },
    { id: 250, day: 5, en: "The elevator is to your left.", ko: "엘리베이터는 왼쪽에 있습니다." },
    { id: 251, day: 5, en: "Please be careful on the stairs.", ko: "계단에서 조심하세요." },
    { id: 252, day: 5, en: "I'll walk you to the exit.", ko: "출구까지 안내해 드리겠습니다." },
    { id: 253, day: 5, en: "Would you like an umbrella? It's raining outside.", ko: "우산을 드릴까요? 밖에 비가 오고 있어요." },
    { id: 254, day: 5, en: "Here is a map to the nearest subway station.", ko: "가장 가까운 지하철역 지도입니다." },
    { id: 255, day: 5, en: "You can take bus number 140 from the stop across the street.", ko: "길 건너편 정류장에서 140번 버스를 타실 수 있습니다." },
    { id: 256, day: 5, en: "Is someone picking you up?", ko: "누가 데리러 오시나요?" },
    { id: 257, day: 5, en: "Please sit down if you feel dizzy after the treatment.", ko: "시술 후 어지러우시면 앉아 계세요." },
    { id: 258, day: 5, en: "Would you like a cold compress to take with you?", ko: "냉찜질팩을 가져가시겠어요?" },
    { id: 259, day: 5, en: "Our clinic is on the third floor.", ko: "저희 클리닉은 3층에 있습니다." },
    { id: 260, day: 5, en: "If you're visiting from abroad, we offer interpreter services.", ko: "해외에서 오신 분들을 위해 통역 서비스를 제공합니다." },
    { id: 261, day: 5, en: "We have staff who speak English, Chinese, and Japanese.", ko: "영어, 중국어, 일본어가 가능한 직원이 있습니다." },
    { id: 262, day: 5, en: "Don't worry, we'll take good care of you.", ko: "걱정 마세요, 잘 돌봐드리겠습니다." },
    { id: 263, day: 5, en: "Your satisfaction is our top priority.", ko: "고객님의 만족이 저희의 최우선입니다." },
    { id: 264, day: 5, en: "We offer a satisfaction guarantee on all treatments.", ko: "모든 시술에 만족 보장 제도가 있습니다." },
    { id: 265, day: 5, en: "If you refer a friend, you both get a discount.", ko: "친구를 소개해 주시면 두 분 모두 할인을 받으십니다." },
    { id: 266, day: 5, en: "Follow us on Instagram for updates and promotions.", ko: "최신 소식과 프로모션은 인스타그램을 팔로우해 주세요." },
    { id: 267, day: 5, en: "We post skincare tips on our social media.", ko: "소셜 미디어에 피부 관리 팁을 게시합니다." },
    { id: 268, day: 5, en: "Would you like to subscribe to our newsletter?", ko: "뉴스레터를 구독하시겠어요?" },
    { id: 269, day: 5, en: "Please scan this QR code for our contact information.", ko: "연락처 정보는 이 QR 코드를 스캔해 주세요." },
    { id: 270, day: 5, en: "We look forward to seeing you at your next appointment.", ko: "다음 예약 때 뵙겠습니다." },
    { id: 271, day: 5, en: "It was nice meeting you today.", ko: "오늘 만나뵈서 반가웠습니다." },
    { id: 272, day: 5, en: "Please take care on your way home.", ko: "집에 가실 때 조심하세요." },
    { id: 273, day: 5, en: "Goodbye, and have a wonderful day!", ko: "안녕히 가세요, 좋은 하루 되세요!" },
    { id: 274, day: 5, en: "Safe travels!", ko: "안전한 여행 되세요!" },
    { id: 275, day: 5, en: "We hope you enjoyed your experience with us.", ko: "저희와 함께한 경험이 만족스러우셨기를 바랍니다." }
];
